<?php declare(strict_types=1);

namespace MallardDuck\MtgCardsSdk\Enums;

/**
 * @see \MallardDuck\MtgCardsSdk\Generator\Actions\GenerateCardSubtypeAction
 */
enum CardSubtype: string
{
	case Abian = 'abian';
	case Adventure = 'adventure';
	case Aetherborn = 'aetherborn';
	case Ajani = 'ajani';
	case Alara = 'alara';
	case Alicorn = 'alicorn';
	case Alien = 'alien';
	case Aminatou = 'aminatou';
	case Angel = 'angel';
	case Angrath = 'angrath';
	case Antelope = 'antelope';
	case Ape = 'ape';
	case Arcane = 'arcane';
	case Archon = 'archon';
	case Arkhos = 'arkhos';
	case Arlinn = 'arlinn';
	case Art = 'art';
	case Artificer = 'artificer';
	case Ashiok = 'ashiok';
	case AssemblyWorker = 'assembly_worker';
	case Astartes = 'astartes';
	case Atog = 'atog';
	case Attraction = 'attraction';
	case Aura = 'aura';
	case Aurochs = 'aurochs';
	case Autobot = 'autobot';
	case Avatar = 'avatar';
	case Azgol = 'azgol';
	case Azra = 'azra';
	case BOB = 'b_ob';
	case Background = 'background';
	case Badger = 'badger';
	case Bahamut = 'bahamut';
	case Basilisk = 'basilisk';
	case Basri = 'basri';
	case Bat = 'bat';
	case Bear = 'bear';
	case Beast = 'beast';
	case Beaver = 'beaver';
	case Beeble = 'beeble';
	case Beholder = 'beholder';
	case Belenon = 'belenon';
	case Berserker = 'berserker';
	case Bird = 'bird';
	case Boar = 'boar';
	case Bolas = 'bolas';
	case BolasSMeditationRealm = 'bolas_s_meditation_realm';
	case Brainiac = 'brainiac';
	case Bringer = 'bringer';
	case Brushwagg = 'brushwagg';
	case Byode = 'byode';
	case CTan = 'c_tan';
	case Calix = 'calix';
	case Camel = 'camel';
	case Cat = 'cat';
	case Centaur = 'centaur';
	case Cephalid = 'cephalid';
	case Chandra = 'chandra';
	case Chicken = 'chicken';
	case Chimera = 'chimera';
	case Clamfolk = 'clamfolk';
	case Class = 'class';
	case Cleric = 'cleric';
	case Cloud = 'cloud';
	case Clown = 'clown';
	case Clue = 'clue';
	case Cockatrice = 'cockatrice';
	case Comet = 'comet';
	case Construct = 'construct';
	case Contraption = 'contraption';
	case Cow = 'cow';
	case Crab = 'crab';
	case Crocodile = 'crocodile';
	case Custodes = 'custodes';
	case Cyborg = 'cyborg';
	case Cyclops = 'cyclops';
	case Dack = 'dack';
	case Dakkon = 'dakkon';
	case Daretti = 'daretti';
	case Dauthi = 'dauthi';
	case Davriel = 'davriel';
	case Deer = 'deer';
	case Demigod = 'demigod';
	case Demon = 'demon';
	case Desert = 'desert';
	case Devil = 'devil';
	case Dihada = 'dihada';
	case Dinosaur = 'dinosaur';
	case Djinn = 'djinn';
	case Dog = 'dog';
	case Dominaria = 'dominaria';
	case Domri = 'domri';
	case Donkey = 'donkey';
	case Dovin = 'dovin';
	case Dragon = 'dragon';
	case Drake = 'drake';
	case Dreadnought = 'dreadnought';
	case Drone = 'drone';
	case Druid = 'druid';
	case Dryad = 'dryad';
	case Duck = 'duck';
	case Dungeon = 'dungeon';
	case Dwarf = 'dwarf';
	case Efreet = 'efreet';
	case Egg = 'egg';
	case Elder = 'elder';
	case Eldrazi = 'eldrazi';
	case Elemental = 'elemental';
	case Elephant = 'elephant';
	case Elf = 'elf';
	case Elk = 'elk';
	case Ellywick = 'ellywick';
	case Elminster = 'elminster';
	case Elspeth = 'elspeth';
	case Elves = 'elves';
	case Equilor = 'equilor';
	case Equipment = 'equipment';
	case Ergamon = 'ergamon';
	case Ersta = 'ersta';
	case Estrid = 'estrid';
	case Eye = 'eye';
	case Fabacin = 'fabacin';
	case Faerie = 'faerie';
	case Ferret = 'ferret';
	case Fire = 'fire';
	case Fish = 'fish';
	case Food = 'food';
	case Forest = 'forest';
	case Fortification = 'fortification';
	case Fox = 'fox';
	case Fractal = 'fractal';
	case Freyalise = 'freyalise';
	case Frog = 'frog';
	case Fungus = 'fungus';
	case Gargoyle = 'gargoyle';
	case Garruk = 'garruk';
	case Gate = 'gate';
	case Giant = 'giant';
	case Gideon = 'gideon';
	case Gith = 'gith';
	case Gnoll = 'gnoll';
	case Gnome = 'gnome';
	case Goat = 'goat';
	case Goblin = 'goblin';
	case God = 'god';
	case Golem = 'golem';
	case Gorgon = 'gorgon';
	case Gremlin = 'gremlin';
	case Griffin = 'griffin';
	case Grist = 'grist';
	case Gus = 'gus';
	case Hag = 'hag';
	case Halfling = 'halfling';
	case Harpy = 'harpy';
	case Hellion = 'hellion';
	case Hippo = 'hippo';
	case Hippogriff = 'hippogriff';
	case Homarid = 'homarid';
	case Homunculus = 'homunculus';
	case Horror = 'horror';
	case Horse = 'horse';
	case Huatli = 'huatli';
	case Human = 'human';
	case Hydra = 'hydra';
	case Hyena = 'hyena';
	case Igpay = 'igpay';
	case Illusion = 'illusion';
	case Imp = 'imp';
	case Incarnation = 'incarnation';
	case Innistrad = 'innistrad';
	case Insect = 'insect';
	case Inzerva = 'inzerva';
	case Iquatana = 'iquatana';
	case Ir = 'ir';
	case Island = 'island';
	case Jace = 'jace';
	case Jackal = 'jackal';
	case Jared = 'jared';
	case Jaya = 'jaya';
	case Jellyfish = 'jellyfish';
	case Jeska = 'jeska';
	case Juggernaut = 'juggernaut';
	case Kaito = 'kaito';
	case Kaldheim = 'kaldheim';
	case Kamigawa = 'kamigawa';
	case Kangaroo = 'kangaroo';
	case Karn = 'karn';
	case Karsus = 'karsus';
	case Kasmina = 'kasmina';
	case Kavu = 'kavu';
	case Kaya = 'kaya';
	case Kephalai = 'kephalai';
	case Key = 'key';
	case Killbot = 'killbot';
	case Kinshala = 'kinshala';
	case Kiora = 'kiora';
	case Kirin = 'kirin';
	case Kithkin = 'kithkin';
	case Knight = 'knight';
	case Kobold = 'kobold';
	case Kolbahan = 'kolbahan';
	case Kor = 'kor';
	case Koth = 'koth';
	case Kraken = 'kraken';
	case Kyneth = 'kyneth';
	case Lady = 'lady';
	case Lair = 'lair';
	case Lamia = 'lamia';
	case Lammasu = 'lammasu';
	case Leech = 'leech';
	case Legend = 'legend';
	case Lesson = 'lesson';
	case Leviathan = 'leviathan';
	case Lhurgoyf = 'lhurgoyf';
	case Licid = 'licid';
	case Liliana = 'liliana';
	case Lizard = 'lizard';
	case Lobster = 'lobster';
	case Locus = 'locus';
	case Lolth = 'lolth';
	case Lorwyn = 'lorwyn';
	case Lukka = 'lukka';
	case Luvion = 'luvion';
	case Mammoth = 'mammoth';
	case Manticore = 'manticore';
	case Masticore = 'masticore';
	case Mercadia = 'mercadia';
	case Merfolk = 'merfolk';
	case Metathran = 'metathran';
	case Minion = 'minion';
	case Minotaur = 'minotaur';
	case Minsc = 'minsc';
	case Mirrodin = 'mirrodin';
	case Moag = 'moag';
	case Mole = 'mole';
	case Monger = 'monger';
	case Mongoose = 'mongoose';
	case Mongseng = 'mongseng';
	case Monkey = 'monkey';
	case Moonfolk = 'moonfolk';
	case Mordenkainen = 'mordenkainen';
	case Mountain = 'mountain';
	case Mouse = 'mouse';
	case Mummy = 'mummy';
	case Muraganda = 'muraganda';
	case Mutant = 'mutant';
	case Myr = 'myr';
	case Naga = 'naga';
	case Nahiri = 'nahiri';
	case Narset = 'narset';
	case Nautilus = 'nautilus';
	case Necron = 'necron';
	case Nephilim = 'nephilim';
	case NewPhyrexia = 'new_phyrexia';
	case Nightmare = 'nightmare';
	case Nightstalker = 'nightstalker';
	case Niko = 'niko';
	case Ninja = 'ninja';
	case Nissa = 'nissa';
	case Nixilis = 'nixilis';
	case Noggle = 'noggle';
	case Nomad = 'nomad';
	case Nymph = 'nymph';
	case Octopus = 'octopus';
	case Ogre = 'ogre';
	case Oko = 'oko';
	case Ooze = 'ooze';
	case Orc = 'orc';
	case Orgg = 'orgg';
	case Otter = 'otter';
	case Ouphe = 'ouphe';
	case Ox = 'ox';
	case Oyster = 'oyster';
	case Pangolin = 'pangolin';
	case Pegasus = 'pegasus';
	case Penguin = 'penguin';
	case Pest = 'pest';
	case Phelddagrif = 'phelddagrif';
	case Phoenix = 'phoenix';
	case Phyrexia = 'phyrexia';
	case Phyrexian = 'phyrexian';
	case Plains = 'plains';
	case Plant = 'plant';
	case Porcupine = 'porcupine';
	case Powerstone = 'powerstone';
	case Pyrulea = 'pyrulea';
	case Rabbit = 'rabbit';
	case Rabiah = 'rabiah';
	case Raccoon = 'raccoon';
	case Ral = 'ral';
	case Rat = 'rat';
	case Rath = 'rath';
	case Ravnica = 'ravnica';
	case Rebel = 'rebel';
	case Regatha = 'regatha';
	case Rhino = 'rhino';
	case Robot = 'robot';
	case Rogue = 'rogue';
	case Rowan = 'rowan';
	case Sable = 'sable';
	case Saga = 'saga';
	case Saheeli = 'saheeli';
	case Salamander = 'salamander';
	case Samut = 'samut';
	case Sarkhan = 'sarkhan';
	case Satyr = 'satyr';
	case Scarecrow = 'scarecrow';
	case Scorpion = 'scorpion';
	case Scout = 'scout';
	case Segovia = 'segovia';
	case Serpent = 'serpent';
	case Serra = 'serra';
	case SerraSRealm = 'serra_s_realm';
	case Shade = 'shade';
	case Shadowmoor = 'shadowmoor';
	case Shaman = 'shaman';
	case Shandalar = 'shandalar';
	case Shapeshifter = 'shapeshifter';
	case Shark = 'shark';
	case Sheep = 'sheep';
	case Ship = 'ship';
	case Shrine = 'shrine';
	case Siren = 'siren';
	case Sivitri = 'sivitri';
	case Skeleton = 'skeleton';
	case Slith = 'slith';
	case Sliver = 'sliver';
	case Slug = 'slug';
	case Snake = 'snake';
	case Soldier = 'soldier';
	case Soltari = 'soltari';
	case Sorin = 'sorin';
	case Spawn = 'spawn';
	case Specter = 'specter';
	case Spellshaper = 'spellshaper';
	case Sphere = 'sphere';
	case Sphinx = 'sphinx';
	case Spider = 'spider';
	case Spike = 'spike';
	case Spirit = 'spirit';
	case Sponge = 'sponge';
	case Squid = 'squid';
	case Squirrel = 'squirrel';
	case Starfish = 'starfish';
	case Surrakar = 'surrakar';
	case Swamp = 'swamp';
	case Szat = 'szat';
	case Tamiyo = 'tamiyo';
	case Tasha = 'tasha';
	case Teferi = 'teferi';
	case Teyo = 'teyo';
	case Tezzeret = 'tezzeret';
	case Thalakos = 'thalakos';
	case The = 'the';
	case Thopter = 'thopter';
	case Thrull = 'thrull';
	case Tibalt = 'tibalt';
	case Tiefling = 'tiefling';
	case Trap = 'trap';
	case Treasure = 'treasure';
	case Treefolk = 'treefolk';
	case Trilobite = 'trilobite';
	case Troll = 'troll';
	case Turtle = 'turtle';
	case Tyranid = 'tyranid';
	case Tyvar = 'tyvar';
	case Ugin = 'ugin';
	case Ulgrotha = 'ulgrotha';
	case Unicorn = 'unicorn';
	case Urza = 'urza';
	case UrzaS = 'urza_s';
	case Valla = 'valla';
	case Vampire = 'vampire';
	case Vampyre = 'vampyre';
	case Vedalken = 'vedalken';
	case Vehicle = 'vehicle';
	case Venser = 'venser';
	case Viashino = 'viashino';
	case Vivien = 'vivien';
	case Volver = 'volver';
	case Vraska = 'vraska';
	case Vryn = 'vryn';
	case Wall = 'wall';
	case Walrus = 'walrus';
	case Warrior = 'warrior';
	case Weird = 'weird';
	case Werewolf = 'werewolf';
	case Whale = 'whale';
	case Wildfire = 'wildfire';
	case Will = 'will';
	case Windgrace = 'windgrace';
	case Wizard = 'wizard';
	case Wolf = 'wolf';
	case Wolverine = 'wolverine';
	case Wombat = 'wombat';
	case Worm = 'worm';
	case Wraith = 'wraith';
	case Wrenn = 'wrenn';
	case Wurm = 'wurm';
	case Xenagos = 'xenagos';
	case Xerex = 'xerex';
	case Yanggu = 'yanggu';
	case Yanling = 'yanling';
	case Yeti = 'yeti';
	case Zariel = 'zariel';
	case Zendikar = 'zendikar';
	case Zombie = 'zombie';
	case Zubera = 'zubera';

	public function label(): string
	{
		return static::getLabel($this);
	}


	public static function getLabel(self $value): string
	{
		return match ($value) {
			CardSubtype::Abian => "Abian",
			CardSubtype::Adventure => "Adventure",
			CardSubtype::Aetherborn => "Aetherborn",
			CardSubtype::Ajani => "Ajani",
			CardSubtype::Alara => "Alara",
			CardSubtype::Alicorn => "Alicorn",
			CardSubtype::Alien => "Alien",
			CardSubtype::Aminatou => "Aminatou",
			CardSubtype::Angel => "Angel",
			CardSubtype::Angrath => "Angrath",
			CardSubtype::Antelope => "Antelope",
			CardSubtype::Ape => "Ape",
			CardSubtype::Arcane => "Arcane",
			CardSubtype::Archon => "Archon",
			CardSubtype::Arkhos => "Arkhos",
			CardSubtype::Arlinn => "Arlinn",
			CardSubtype::Art => "Art",
			CardSubtype::Artificer => "Artificer",
			CardSubtype::Ashiok => "Ashiok",
			CardSubtype::AssemblyWorker => "Assembly-Worker",
			CardSubtype::Astartes => "Astartes",
			CardSubtype::Atog => "Atog",
			CardSubtype::Attraction => "Attraction",
			CardSubtype::Aura => "Aura",
			CardSubtype::Aurochs => "Aurochs",
			CardSubtype::Autobot => "Autobot",
			CardSubtype::Avatar => "Avatar",
			CardSubtype::Azgol => "Azgol",
			CardSubtype::Azra => "Azra",
			CardSubtype::BOB => "B.O.B.",
			CardSubtype::Background => "Background",
			CardSubtype::Badger => "Badger",
			CardSubtype::Bahamut => "Bahamut",
			CardSubtype::Basilisk => "Basilisk",
			CardSubtype::Basri => "Basri",
			CardSubtype::Bat => "Bat",
			CardSubtype::Bear => "Bear",
			CardSubtype::Beast => "Beast",
			CardSubtype::Beaver => "Beaver",
			CardSubtype::Beeble => "Beeble",
			CardSubtype::Beholder => "Beholder",
			CardSubtype::Belenon => "Belenon",
			CardSubtype::Berserker => "Berserker",
			CardSubtype::Bird => "Bird",
			CardSubtype::Boar => "Boar",
			CardSubtype::Bolas => "Bolas",
			CardSubtype::BolasSMeditationRealm => "Bolas's Meditation Realm",
			CardSubtype::Brainiac => "Brainiac",
			CardSubtype::Bringer => "Bringer",
			CardSubtype::Brushwagg => "Brushwagg",
			CardSubtype::Byode => "Byode",
			CardSubtype::CTan => "C'tan",
			CardSubtype::Calix => "Calix",
			CardSubtype::Camel => "Camel",
			CardSubtype::Cat => "Cat",
			CardSubtype::Centaur => "Centaur",
			CardSubtype::Cephalid => "Cephalid",
			CardSubtype::Chandra => "Chandra",
			CardSubtype::Chicken => "Chicken",
			CardSubtype::Chimera => "Chimera",
			CardSubtype::Clamfolk => "Clamfolk",
			CardSubtype::Class => "Class",
			CardSubtype::Cleric => "Cleric",
			CardSubtype::Cloud => "Cloud",
			CardSubtype::Clown => "Clown",
			CardSubtype::Clue => "Clue",
			CardSubtype::Cockatrice => "Cockatrice",
			CardSubtype::Comet => "Comet",
			CardSubtype::Construct => "Construct",
			CardSubtype::Contraption => "Contraption",
			CardSubtype::Cow => "Cow",
			CardSubtype::Crab => "Crab",
			CardSubtype::Crocodile => "Crocodile",
			CardSubtype::Custodes => "Custodes",
			CardSubtype::Cyborg => "Cyborg",
			CardSubtype::Cyclops => "Cyclops",
			CardSubtype::Dack => "Dack",
			CardSubtype::Dakkon => "Dakkon",
			CardSubtype::Daretti => "Daretti",
			CardSubtype::Dauthi => "Dauthi",
			CardSubtype::Davriel => "Davriel",
			CardSubtype::Deer => "Deer",
			CardSubtype::Demigod => "Demigod",
			CardSubtype::Demon => "Demon",
			CardSubtype::Desert => "Desert",
			CardSubtype::Devil => "Devil",
			CardSubtype::Dihada => "Dihada",
			CardSubtype::Dinosaur => "Dinosaur",
			CardSubtype::Djinn => "Djinn",
			CardSubtype::Dog => "Dog",
			CardSubtype::Dominaria => "Dominaria",
			CardSubtype::Domri => "Domri",
			CardSubtype::Donkey => "Donkey",
			CardSubtype::Dovin => "Dovin",
			CardSubtype::Dragon => "Dragon",
			CardSubtype::Drake => "Drake",
			CardSubtype::Dreadnought => "Dreadnought",
			CardSubtype::Drone => "Drone",
			CardSubtype::Druid => "Druid",
			CardSubtype::Dryad => "Dryad",
			CardSubtype::Duck => "Duck",
			CardSubtype::Dungeon => "Dungeon",
			CardSubtype::Dwarf => "Dwarf",
			CardSubtype::Efreet => "Efreet",
			CardSubtype::Egg => "Egg",
			CardSubtype::Elder => "Elder",
			CardSubtype::Eldrazi => "Eldrazi",
			CardSubtype::Elemental => "Elemental",
			CardSubtype::Elephant => "Elephant",
			CardSubtype::Elf => "Elf",
			CardSubtype::Elk => "Elk",
			CardSubtype::Ellywick => "Ellywick",
			CardSubtype::Elminster => "Elminster",
			CardSubtype::Elspeth => "Elspeth",
			CardSubtype::Elves => "Elves",
			CardSubtype::Equilor => "Equilor",
			CardSubtype::Equipment => "Equipment",
			CardSubtype::Ergamon => "Ergamon",
			CardSubtype::Ersta => "Ersta",
			CardSubtype::Estrid => "Estrid",
			CardSubtype::Eye => "Eye",
			CardSubtype::Fabacin => "Fabacin",
			CardSubtype::Faerie => "Faerie",
			CardSubtype::Ferret => "Ferret",
			CardSubtype::Fire => "Fire",
			CardSubtype::Fish => "Fish",
			CardSubtype::Food => "Food",
			CardSubtype::Forest => "Forest",
			CardSubtype::Fortification => "Fortification",
			CardSubtype::Fox => "Fox",
			CardSubtype::Fractal => "Fractal",
			CardSubtype::Freyalise => "Freyalise",
			CardSubtype::Frog => "Frog",
			CardSubtype::Fungus => "Fungus",
			CardSubtype::Gargoyle => "Gargoyle",
			CardSubtype::Garruk => "Garruk",
			CardSubtype::Gate => "Gate",
			CardSubtype::Giant => "Giant",
			CardSubtype::Gideon => "Gideon",
			CardSubtype::Gith => "Gith",
			CardSubtype::Gnoll => "Gnoll",
			CardSubtype::Gnome => "Gnome",
			CardSubtype::Goat => "Goat",
			CardSubtype::Goblin => "Goblin",
			CardSubtype::God => "God",
			CardSubtype::Golem => "Golem",
			CardSubtype::Gorgon => "Gorgon",
			CardSubtype::Gremlin => "Gremlin",
			CardSubtype::Griffin => "Griffin",
			CardSubtype::Grist => "Grist",
			CardSubtype::Gus => "Gus",
			CardSubtype::Hag => "Hag",
			CardSubtype::Halfling => "Halfling",
			CardSubtype::Harpy => "Harpy",
			CardSubtype::Hellion => "Hellion",
			CardSubtype::Hippo => "Hippo",
			CardSubtype::Hippogriff => "Hippogriff",
			CardSubtype::Homarid => "Homarid",
			CardSubtype::Homunculus => "Homunculus",
			CardSubtype::Horror => "Horror",
			CardSubtype::Horse => "Horse",
			CardSubtype::Huatli => "Huatli",
			CardSubtype::Human => "Human",
			CardSubtype::Hydra => "Hydra",
			CardSubtype::Hyena => "Hyena",
			CardSubtype::Igpay => "Igpay",
			CardSubtype::Illusion => "Illusion",
			CardSubtype::Imp => "Imp",
			CardSubtype::Incarnation => "Incarnation",
			CardSubtype::Innistrad => "Innistrad",
			CardSubtype::Insect => "Insect",
			CardSubtype::Inzerva => "Inzerva",
			CardSubtype::Iquatana => "Iquatana",
			CardSubtype::Ir => "Ir",
			CardSubtype::Island => "Island",
			CardSubtype::Jace => "Jace",
			CardSubtype::Jackal => "Jackal",
			CardSubtype::Jared => "Jared",
			CardSubtype::Jaya => "Jaya",
			CardSubtype::Jellyfish => "Jellyfish",
			CardSubtype::Jeska => "Jeska",
			CardSubtype::Juggernaut => "Juggernaut",
			CardSubtype::Kaito => "Kaito",
			CardSubtype::Kaldheim => "Kaldheim",
			CardSubtype::Kamigawa => "Kamigawa",
			CardSubtype::Kangaroo => "Kangaroo",
			CardSubtype::Karn => "Karn",
			CardSubtype::Karsus => "Karsus",
			CardSubtype::Kasmina => "Kasmina",
			CardSubtype::Kavu => "Kavu",
			CardSubtype::Kaya => "Kaya",
			CardSubtype::Kephalai => "Kephalai",
			CardSubtype::Key => "Key",
			CardSubtype::Killbot => "Killbot",
			CardSubtype::Kinshala => "Kinshala",
			CardSubtype::Kiora => "Kiora",
			CardSubtype::Kirin => "Kirin",
			CardSubtype::Kithkin => "Kithkin",
			CardSubtype::Knight => "Knight",
			CardSubtype::Kobold => "Kobold",
			CardSubtype::Kolbahan => "Kolbahan",
			CardSubtype::Kor => "Kor",
			CardSubtype::Koth => "Koth",
			CardSubtype::Kraken => "Kraken",
			CardSubtype::Kyneth => "Kyneth",
			CardSubtype::Lady => "Lady",
			CardSubtype::Lair => "Lair",
			CardSubtype::Lamia => "Lamia",
			CardSubtype::Lammasu => "Lammasu",
			CardSubtype::Leech => "Leech",
			CardSubtype::Legend => "Legend",
			CardSubtype::Lesson => "Lesson",
			CardSubtype::Leviathan => "Leviathan",
			CardSubtype::Lhurgoyf => "Lhurgoyf",
			CardSubtype::Licid => "Licid",
			CardSubtype::Liliana => "Liliana",
			CardSubtype::Lizard => "Lizard",
			CardSubtype::Lobster => "Lobster",
			CardSubtype::Locus => "Locus",
			CardSubtype::Lolth => "Lolth",
			CardSubtype::Lorwyn => "Lorwyn",
			CardSubtype::Lukka => "Lukka",
			CardSubtype::Luvion => "Luvion",
			CardSubtype::Mammoth => "Mammoth",
			CardSubtype::Manticore => "Manticore",
			CardSubtype::Masticore => "Masticore",
			CardSubtype::Mercadia => "Mercadia",
			CardSubtype::Merfolk => "Merfolk",
			CardSubtype::Metathran => "Metathran",
			CardSubtype::Minion => "Minion",
			CardSubtype::Minotaur => "Minotaur",
			CardSubtype::Minsc => "Minsc",
			CardSubtype::Mirrodin => "Mirrodin",
			CardSubtype::Moag => "Moag",
			CardSubtype::Mole => "Mole",
			CardSubtype::Monger => "Monger",
			CardSubtype::Mongoose => "Mongoose",
			CardSubtype::Mongseng => "Mongseng",
			CardSubtype::Monkey => "Monkey",
			CardSubtype::Moonfolk => "Moonfolk",
			CardSubtype::Mordenkainen => "Mordenkainen",
			CardSubtype::Mountain => "Mountain",
			CardSubtype::Mouse => "Mouse",
			CardSubtype::Mummy => "Mummy",
			CardSubtype::Muraganda => "Muraganda",
			CardSubtype::Mutant => "Mutant",
			CardSubtype::Myr => "Myr",
			CardSubtype::Naga => "Naga",
			CardSubtype::Nahiri => "Nahiri",
			CardSubtype::Narset => "Narset",
			CardSubtype::Nautilus => "Nautilus",
			CardSubtype::Necron => "Necron",
			CardSubtype::Nephilim => "Nephilim",
			CardSubtype::NewPhyrexia => "New Phyrexia",
			CardSubtype::Nightmare => "Nightmare",
			CardSubtype::Nightstalker => "Nightstalker",
			CardSubtype::Niko => "Niko",
			CardSubtype::Ninja => "Ninja",
			CardSubtype::Nissa => "Nissa",
			CardSubtype::Nixilis => "Nixilis",
			CardSubtype::Noggle => "Noggle",
			CardSubtype::Nomad => "Nomad",
			CardSubtype::Nymph => "Nymph",
			CardSubtype::Octopus => "Octopus",
			CardSubtype::Ogre => "Ogre",
			CardSubtype::Oko => "Oko",
			CardSubtype::Ooze => "Ooze",
			CardSubtype::Orc => "Orc",
			CardSubtype::Orgg => "Orgg",
			CardSubtype::Otter => "Otter",
			CardSubtype::Ouphe => "Ouphe",
			CardSubtype::Ox => "Ox",
			CardSubtype::Oyster => "Oyster",
			CardSubtype::Pangolin => "Pangolin",
			CardSubtype::Pegasus => "Pegasus",
			CardSubtype::Penguin => "Penguin",
			CardSubtype::Pest => "Pest",
			CardSubtype::Phelddagrif => "Phelddagrif",
			CardSubtype::Phoenix => "Phoenix",
			CardSubtype::Phyrexia => "Phyrexia",
			CardSubtype::Phyrexian => "Phyrexian",
			CardSubtype::Plains => "Plains",
			CardSubtype::Plant => "Plant",
			CardSubtype::Porcupine => "Porcupine",
			CardSubtype::Powerstone => "Powerstone",
			CardSubtype::Pyrulea => "Pyrulea",
			CardSubtype::Rabbit => "Rabbit",
			CardSubtype::Rabiah => "Rabiah",
			CardSubtype::Raccoon => "Raccoon",
			CardSubtype::Ral => "Ral",
			CardSubtype::Rat => "Rat",
			CardSubtype::Rath => "Rath",
			CardSubtype::Ravnica => "Ravnica",
			CardSubtype::Rebel => "Rebel",
			CardSubtype::Regatha => "Regatha",
			CardSubtype::Rhino => "Rhino",
			CardSubtype::Robot => "Robot",
			CardSubtype::Rogue => "Rogue",
			CardSubtype::Rowan => "Rowan",
			CardSubtype::Sable => "Sable",
			CardSubtype::Saga => "Saga",
			CardSubtype::Saheeli => "Saheeli",
			CardSubtype::Salamander => "Salamander",
			CardSubtype::Samut => "Samut",
			CardSubtype::Sarkhan => "Sarkhan",
			CardSubtype::Satyr => "Satyr",
			CardSubtype::Scarecrow => "Scarecrow",
			CardSubtype::Scorpion => "Scorpion",
			CardSubtype::Scout => "Scout",
			CardSubtype::Segovia => "Segovia",
			CardSubtype::Serpent => "Serpent",
			CardSubtype::Serra => "Serra",
			CardSubtype::SerraSRealm => "Serra's Realm",
			CardSubtype::Shade => "Shade",
			CardSubtype::Shadowmoor => "Shadowmoor",
			CardSubtype::Shaman => "Shaman",
			CardSubtype::Shandalar => "Shandalar",
			CardSubtype::Shapeshifter => "Shapeshifter",
			CardSubtype::Shark => "Shark",
			CardSubtype::Sheep => "Sheep",
			CardSubtype::Ship => "Ship",
			CardSubtype::Shrine => "Shrine",
			CardSubtype::Siren => "Siren",
			CardSubtype::Sivitri => "Sivitri",
			CardSubtype::Skeleton => "Skeleton",
			CardSubtype::Slith => "Slith",
			CardSubtype::Sliver => "Sliver",
			CardSubtype::Slug => "Slug",
			CardSubtype::Snake => "Snake",
			CardSubtype::Soldier => "Soldier",
			CardSubtype::Soltari => "Soltari",
			CardSubtype::Sorin => "Sorin",
			CardSubtype::Spawn => "Spawn",
			CardSubtype::Specter => "Specter",
			CardSubtype::Spellshaper => "Spellshaper",
			CardSubtype::Sphere => "Sphere",
			CardSubtype::Sphinx => "Sphinx",
			CardSubtype::Spider => "Spider",
			CardSubtype::Spike => "Spike",
			CardSubtype::Spirit => "Spirit",
			CardSubtype::Sponge => "Sponge",
			CardSubtype::Squid => "Squid",
			CardSubtype::Squirrel => "Squirrel",
			CardSubtype::Starfish => "Starfish",
			CardSubtype::Surrakar => "Surrakar",
			CardSubtype::Swamp => "Swamp",
			CardSubtype::Szat => "Szat",
			CardSubtype::Tamiyo => "Tamiyo",
			CardSubtype::Tasha => "Tasha",
			CardSubtype::Teferi => "Teferi",
			CardSubtype::Teyo => "Teyo",
			CardSubtype::Tezzeret => "Tezzeret",
			CardSubtype::Thalakos => "Thalakos",
			CardSubtype::The => "The",
			CardSubtype::Thopter => "Thopter",
			CardSubtype::Thrull => "Thrull",
			CardSubtype::Tibalt => "Tibalt",
			CardSubtype::Tiefling => "Tiefling",
			CardSubtype::Trap => "Trap",
			CardSubtype::Treasure => "Treasure",
			CardSubtype::Treefolk => "Treefolk",
			CardSubtype::Trilobite => "Trilobite",
			CardSubtype::Troll => "Troll",
			CardSubtype::Turtle => "Turtle",
			CardSubtype::Tyranid => "Tyranid",
			CardSubtype::Tyvar => "Tyvar",
			CardSubtype::Ugin => "Ugin",
			CardSubtype::Ulgrotha => "Ulgrotha",
			CardSubtype::Unicorn => "Unicorn",
			CardSubtype::Urza => "Urza",
			CardSubtype::UrzaS => "Urza's",
			CardSubtype::Valla => "Valla",
			CardSubtype::Vampire => "Vampire",
			CardSubtype::Vampyre => "Vampyre",
			CardSubtype::Vedalken => "Vedalken",
			CardSubtype::Vehicle => "Vehicle",
			CardSubtype::Venser => "Venser",
			CardSubtype::Viashino => "Viashino",
			CardSubtype::Vivien => "Vivien",
			CardSubtype::Volver => "Volver",
			CardSubtype::Vraska => "Vraska",
			CardSubtype::Vryn => "Vryn",
			CardSubtype::Wall => "Wall",
			CardSubtype::Walrus => "Walrus",
			CardSubtype::Warrior => "Warrior",
			CardSubtype::Weird => "Weird",
			CardSubtype::Werewolf => "Werewolf",
			CardSubtype::Whale => "Whale",
			CardSubtype::Wildfire => "Wildfire",
			CardSubtype::Will => "Will",
			CardSubtype::Windgrace => "Windgrace",
			CardSubtype::Wizard => "Wizard",
			CardSubtype::Wolf => "Wolf",
			CardSubtype::Wolverine => "Wolverine",
			CardSubtype::Wombat => "Wombat",
			CardSubtype::Worm => "Worm",
			CardSubtype::Wraith => "Wraith",
			CardSubtype::Wrenn => "Wrenn",
			CardSubtype::Wurm => "Wurm",
			CardSubtype::Xenagos => "Xenagos",
			CardSubtype::Xerex => "Xerex",
			CardSubtype::Yanggu => "Yanggu",
			CardSubtype::Yanling => "Yanling",
			CardSubtype::Yeti => "Yeti",
			CardSubtype::Zariel => "Zariel",
			CardSubtype::Zendikar => "Zendikar",
			CardSubtype::Zombie => "Zombie",
			CardSubtype::Zubera => "Zubera",
		}
		;
	}
}
