<?php declare(strict_types=1);

namespace MallardDuck\MtgCardsSdk\Enums;

/**
 * @see \MallardDuck\MtgCardsSdk\Generator\Actions\GenerateCardKeywordAction
 */
enum CardKeyword: string
{
	case AThousandSoulsDieEveryDay = 'a_thousand_souls_die_every_day';
	case AberrantTinkering = 'aberrant_tinkering';
	case Adamant = 'adamant';
	case Adapt = 'adapt';
	case Addendum = 'addendum';
	case AdvancedSpecies = 'advanced_species';
	case AegisOfTheEmperor = 'aegis_of_the_emperor';
	case Affinity = 'affinity';
	case Afflict = 'afflict';
	case Afterlife = 'afterlife';
	case Aftermath = 'aftermath';
	case AimForTheCursedAmulet = 'aim_for_the_cursed_amulet';
	case Alliance = 'alliance';
	case AllureOfSlaanesh = 'allure_of_slaanesh';
	case Amass = 'amass';
	case Amplify = 'amplify';
	case AnimateChains = 'animate_chains';
	case Annihilator = 'annihilator';
	case ArchitectOfDeception = 'architect_of_deception';
	case ArmourOfShriekingSouls = 'armour_of_shrieking_souls';
	case Ascend = 'ascend';
	case Assemble = 'assemble';
	case Assist = 'assist';
	case AtomicTransmutation = 'atomic_transmutation';
	case Augment = 'augment';
	case AuraSwap = 'aura_swap';
	case Avoidance = 'avoidance';
	case Awaken = 'awaken';
	case Banding = 'banding';
	case BasicLandcycling = 'basic_landcycling';
	case Battalion = 'battalion';
	case BattleCannon = 'battle_cannon';
	case BattleCry = 'battle_cry';
	case BenedictionOfTheOmnissiah = 'benediction_of_the_omnissiah';
	case Berzerker = 'berzerker';
	case Bestow = 'bestow';
	case BigbySHand = 'bigby_s_hand';
	case BioPlasmicBarrage = 'bio_plasmic_barrage';
	case BioPlasmicScream = 'bio_plasmic_scream';
	case Blitz = 'blitz';
	case BloodChalice = 'blood_chalice';
	case BloodDrain = 'blood_drain';
	case Bloodrush = 'bloodrush';
	case Bloodthirst = 'bloodthirst';
	case Boast = 'boast';
	case BodyThief = 'body_thief';
	case Bolster = 'bolster';
	case BribeTheGuards = 'bribe_the_guards';
	case BringItDown = 'bring_it_down';
	case BroodTelepathy = 'brood_telepathy';
	case Bushido = 'bushido';
	case BuyInformation = 'buy_information';
	case Buyback = 'buyback';
	case CalimSBreath = 'calim_s_breath';
	case CallForAid = 'call_for_aid';
	case Cascade = 'cascade';
	case Casualty = 'casualty';
	case Ceremorphosis = 'ceremorphosis';
	case Chainsword = 'chainsword';
	case Champion = 'champion';
	case Changeling = 'changeling';
	case Channel = 'channel';
	case ChapterMaster = 'chapter_master';
	case ChildrenOfTheCult = 'children_of_the_cult';
	case Chroma = 'chroma';
	case Cipher = 'cipher';
	case Clash = 'clash';
	case Cleave = 'cleave';
	case Cohort = 'cohort';
	case CommandProtocols = 'command_protocols';
	case CommanderNinjutsu = 'commander_ninjutsu';
	case Companion = 'companion';
	case Compleated = 'compleated';
	case ConcealedPosition = 'concealed_position';
	case ConfoundingClouds = 'confounding_clouds';
	case Conjure = 'conjure';
	case Connive = 'connive';
	case Conspire = 'conspire';
	case Constellation = 'constellation';
	case Converge = 'converge';
	case Convert = 'convert';
	case Convoke = 'convoke';
	case Corrupted = 'corrupted';
	case CoruscatingFlames = 'coruscating_flames';
	case CouncilSDilemma = 'council_s_dilemma';
	case Coven = 'coven';
	case Crew = 'crew';
	case CrownOfMadness = 'crown_of_madness';
	case CrushingTeeth = 'crushing_teeth';
	case CumulativeUpkeep = 'cumulative_upkeep';
	case CurseOfTheWalkingPox = 'curse_of_the_walking_pox';
	case Cycling = 'cycling';
	case DaemonSword = 'daemon_sword';
	case Dash = 'dash';
	case Daybound = 'daybound';
	case DeathFrenzy = 'death_frenzy';
	case DeathRay = 'death_ray';
	case Deathtouch = 'deathtouch';
	case Defender = 'defender';
	case Delirium = 'delirium';
	case Delve = 'delve';
	case Demonstrate = 'demonstrate';
	case Desertwalk = 'desertwalk';
	case Detain = 'detain';
	case Dethrone = 'dethrone';
	case DevastatingCharge = 'devastating_charge';
	case Devoid = 'devoid';
	case Devour = 'devour';
	case DevourerOfSouls = 'devourer_of_souls';
	case DevouringMonster = 'devouring_monster';
	case Disturb = 'disturb';
	case Domain = 'domain';
	case DoubleAgenda = 'double_agenda';
	case DoubleStrike = 'double_strike';
	case DrainLife = 'drain_life';
	case Dredge = 'dredge';
	case DynasticAdvisor = 'dynastic_advisor';
	case DynasticCodes = 'dynastic_codes';
	case DynasticCommandNode = 'dynastic_command_node';
	case Echo = 'echo';
	case EliteTroops = 'elite_troops';
	case Embalm = 'embalm';
	case Emerge = 'emerge';
	case Eminence = 'eminence';
	case Enchant = 'enchant';
	case Encore = 'encore';
	case EndlessSwarm = 'endless_swarm';
	case Endurant = 'endurant';
	case Enlist = 'enlist';
	case EnmiticExterminator = 'enmitic_exterminator';
	case Enrage = 'enrage';
	case EnthrallingPerformance = 'enthralling_performance';
	case Entwine = 'entwine';
	case Epic = 'epic';
	case Equip = 'equip';
	case Escalate = 'escalate';
	case Escape = 'escape';
	case Eternalize = 'eternalize';
	case Evoke = 'evoke';
	case Evolve = 'evolve';
	case Exalted = 'exalted';
	case ExecutionerRound = 'executioner_round';
	case Exert = 'exert';
	case ExileCannon = 'exile_cannon';
	case Exploit = 'exploit';
	case Explore = 'explore';
	case Extort = 'extort';
	case Fabricate = 'fabricate';
	case FabricatorClawArray = 'fabricator_claw_array';
	case Fading = 'fading';
	case FallenWarrior = 'fallen_warrior';
	case FastHealing = 'fast_healing';
	case FatefulHour = 'fateful_hour';
	case Fateseal = 'fateseal';
	case Fear = 'fear';
	case FeederMandibles = 'feeder_mandibles';
	case Ferocious = 'ferocious';
	case FieldReprogramming = 'field_reprogramming';
	case Fight = 'fight';
	case FireOfTzeentch = 'fire_of_tzeentch';
	case FirstStrike = 'first_strike';
	case Flanking = 'flanking';
	case Flash = 'flash';
	case Flashback = 'flashback';
	case FleshFlayer = 'flesh_flayer';
	case Flying = 'flying';
	case Forecast = 'forecast';
	case Forestcycling = 'forestcycling';
	case Forestwalk = 'forestwalk';
	case Foretell = 'foretell';
	case Formidable = 'formidable';
	case Fortify = 'fortify';
	case FrenziedMetabolism = 'frenzied_metabolism';
	case FrenziedRampage = 'frenzied_rampage';
	case Frenzy = 'frenzy';
	case FriendsForever = 'friends_forever';
	case Fuse = 'fuse';
	case GatherYourCourage = 'gather_your_courage';
	case GatheredSwarm = 'gathered_swarm';
	case GenomicEnhancement = 'genomic_enhancement';
	case GiftOfChaos = 'gift_of_chaos';
	case GiftOfTiamat = 'gift_of_tiamat';
	case Goad = 'goad';
	case Graft = 'graft';
	case GrandStrategist = 'grand_strategist';
	case Grandeur = 'grandeur';
	case GravCannon = 'grav_cannon';
	case Gravestorm = 'gravestorm';
	case GuardianProtocols = 'guardian_protocols';
	case GustOfWind = 'gust_of_wind';
	case Haste = 'haste';
	case Haunt = 'haunt';
	case HeavyPowerHammer = 'heavy_power_hammer';
	case HeavyRockCutter = 'heavy_rock_cutter';
	case Hellbent = 'hellbent';
	case HeroSReward = 'hero_s_reward';
	case Heroic = 'heroic';
	case Hexproof = 'hexproof';
	case HiddenAgenda = 'hidden_agenda';
	case Hideaway = 'hideaway';
	case HiveMind = 'hive_mind';
	case HomunculusServant = 'homunculus_servant';
	case HorrificSymbiosis = 'horrific_symbiosis';
	case Horsemanship = 'horsemanship';
	case HuntForHeresy = 'hunt_for_heresy';
	case Imprint = 'imprint';
	case Improvise = 'improvise';
	case Indestructible = 'indestructible';
	case Infect = 'infect';
	case InfestingSpores = 'infesting_spores';
	case Inspired = 'inspired';
	case Intensity = 'intensity';
	case Intimidate = 'intimidate';
	case Investigate = 'investigate';
	case Islandwalk = 'islandwalk';
	case JoinForces = 'join_forces';
	case JollyGutpipes = 'jolly_gutpipes';
	case JumpStart = 'jump_start';
	case Kicker = 'kicker';
	case Kinfall = 'kinfall';
	case Kinship = 'kinship';
	case Landfall = 'landfall';
	case Landwalk = 'landwalk';
	case LeadingFromTheFront = 'leading_from_the_front';
	case Learn = 'learn';
	case Legacy = 'legacy';
	case LevelUp = 'level_up';
	case Lieutenant = 'lieutenant';
	case Lifelink = 'lifelink';
	case LocusOfSlaanesh = 'locus_of_slaanesh';
	case LordOfChaos = 'lord_of_chaos';
	case LordOfThePyrrhianLegions = 'lord_of_the_pyrrhian_legions';
	case LoudRuckus = 'loud_ruckus';
	case Madness = 'madness';
	case Magecraft = 'magecraft';
	case MamaSComing = 'mama_s_coming';
	case Manifest = 'manifest';
	case MarkOfChaosAscendant = 'mark_of_chaos_ascendant';
	case Martyrdom = 'martyrdom';
	case MasterOfMachines = 'master_of_machines';
	case MedicusMinistorum = 'medicus_ministorum';
	case Megamorph = 'megamorph';
	case Meld = 'meld';
	case Melee = 'melee';
	case Menace = 'menace';
	case Mentor = 'mentor';
	case Metalcraft = 'metalcraft';
	case Mill = 'mill';
	case Miracle = 'miracle';
	case Modular = 'modular';
	case MoltingExoskeleton = 'molting_exoskeleton';
	case Monstrosity = 'monstrosity';
	case Morbid = 'morbid';
	case Morph = 'morph';
	case Mountaincycling = 'mountaincycling';
	case Mountainwalk = 'mountainwalk';
	case MultiThreatEliminator = 'multi_threat_eliminator';
	case Multikicker = 'multikicker';
	case Mutate = 'mutate';
	case Myriad = 'myriad';
	case NeurotraumalRod = 'neurotraumal_rod';
	case Nightbound = 'nightbound';
	case Ninjutsu = 'ninjutsu';
	case Offering = 'offering';
	case OpenAnAttraction = 'open_an_attraction';
	case Outlast = 'outlast';
	case Overload = 'overload';
	case PackTactics = 'pack_tactics';
	case Parley = 'parley';
	case Partner = 'partner';
	case Persist = 'persist';
	case PhalanxCommander = 'phalanx_commander';
	case Phasing = 'phasing';
	case Plainscycling = 'plainscycling';
	case Plainswalk = 'plainswalk';
	case Populate = 'populate';
	case PrayForProtection = 'pray_for_protection';
	case ProclamatorHailer = 'proclamator_hailer';
	case Proliferate = 'proliferate';
	case Protection = 'protection';
	case ProtectionFightingStyle = 'protection_fighting_style';
	case Protector = 'protector';
	case Prototype = 'prototype';
	case Provoke = 'provoke';
	case Prowess = 'prowess';
	case Prowl = 'prowl';
	case PsionicAdept = 'psionic_adept';
	case PsychicBlades = 'psychic_blades';
	case PsychicStimulus = 'psychic_stimulus';
	case Radiance = 'radiance';
	case Raid = 'raid';
	case Rally = 'rally';
	case Rampage = 'rampage';
	case RapidRegeneration = 'rapid_regeneration';
	case Ravenous = 'ravenous';
	case Reach = 'reach';
	case ReadAhead = 'read_ahead';
	case Rebound = 'rebound';
	case Reconfigure = 'reconfigure';
	case Recover = 'recover';
	case Reinforce = 'reinforce';
	case RelentlessMarch = 'relentless_march';
	case Renown = 'renown';
	case Replicate = 'replicate';
	case Retrace = 'retrace';
	case ReverberatingSummons = 'reverberating_summons';
	case Revolt = 'revolt';
	case Riot = 'riot';
	case Ripple = 'ripple';
	case RogueTrader = 'rogue_trader';
	case RollToVisitYourAttractions = 'roll_to_visit_your_attractions';
	case Scavenge = 'scavenge';
	case ScorchingRay = 'scorching_ray';
	case Scry = 'scry';
	case SecretsOfTheSoul = 'secrets_of_the_soul';
	case Seek = 'seek';
	case Shadow = 'shadow';
	case Shroud = 'shroud';
	case Skulk = 'skulk';
	case SleightOfHand = 'sleight_of_hand';
	case Slivercycling = 'slivercycling';
	case Soulbond = 'soulbond';
	case Soulshift = 'soulshift';
	case Spectacle = 'spectacle';
	case SpellMastery = 'spell_mastery';
	case SpikedRetribution = 'spiked_retribution';
	case Splice = 'splice';
	case SplitSecond = 'split_second';
	case Squad = 'squad';
	case Storm = 'storm';
	case StrategicCoordinator = 'strategic_coordinator';
	case Strive = 'strive';
	case SubterraneanAssault = 'subterranean_assault';
	case Sunburst = 'sunburst';
	case Support = 'support';
	case Surge = 'surge';
	case Surveil = 'surveil';
	case Suspend = 'suspend';
	case Swampcycling = 'swampcycling';
	case Swampwalk = 'swampwalk';
	case Sweep = 'sweep';
	case TargetingRelay = 'targeting_relay';
	case TemptingOffer = 'tempting_offer';
	case ThreeAutostubs = 'three_autostubs';
	case Threshold = 'threshold';
	case Toxic = 'toxic';
	case Training = 'training';
	case Trample = 'trample';
	case TransdimensionalScout = 'transdimensional_scout';
	case Transfigure = 'transfigure';
	case Transform = 'transform';
	case Transmute = 'transmute';
	case Tribute = 'tribute';
	case Undaunted = 'undaunted';
	case Undergrowth = 'undergrowth';
	case Undying = 'undying';
	case Unearth = 'unearth';
	case Unleash = 'unleash';
	case VanguardSpecies = 'vanguard_species';
	case Vanishing = 'vanishing';
	case VeilOfTime = 'veil_of_time';
	case VentureIntoTheDungeon = 'venture_into_the_dungeon';
	case Vigilance = 'vigilance';
	case Ward = 'ward';
	case WeirdInsight = 'weird_insight';
	case WillOfTheCouncil = 'will_of_the_council';
	case WindWalk = 'wind_walk';
	case Wither = 'wither';
	case Wizardcycling = 'wizardcycling';

	public function label(): string
	{
		return static::getLabel($this);
	}


	public static function getLabel(self $value): string
	{
		return match ($value) {
			CardKeyword::AThousandSoulsDieEveryDay => "A Thousand Souls Die Every Day",
			CardKeyword::AberrantTinkering => "Aberrant Tinkering",
			CardKeyword::Adamant => "Adamant",
			CardKeyword::Adapt => "Adapt",
			CardKeyword::Addendum => "Addendum",
			CardKeyword::AdvancedSpecies => "Advanced Species",
			CardKeyword::AegisOfTheEmperor => "Aegis of the Emperor",
			CardKeyword::Affinity => "Affinity",
			CardKeyword::Afflict => "Afflict",
			CardKeyword::Afterlife => "Afterlife",
			CardKeyword::Aftermath => "Aftermath",
			CardKeyword::AimForTheCursedAmulet => "Aim for the Cursed Amulet",
			CardKeyword::Alliance => "Alliance",
			CardKeyword::AllureOfSlaanesh => "Allure of Slaanesh",
			CardKeyword::Amass => "Amass",
			CardKeyword::Amplify => "Amplify",
			CardKeyword::AnimateChains => "Animate Chains",
			CardKeyword::Annihilator => "Annihilator",
			CardKeyword::ArchitectOfDeception => "Architect of Deception",
			CardKeyword::ArmourOfShriekingSouls => "Armour of Shrieking Souls",
			CardKeyword::Ascend => "Ascend",
			CardKeyword::Assemble => "Assemble",
			CardKeyword::Assist => "Assist",
			CardKeyword::AtomicTransmutation => "Atomic Transmutation",
			CardKeyword::Augment => "Augment",
			CardKeyword::AuraSwap => "Aura Swap",
			CardKeyword::Avoidance => "Avoidance",
			CardKeyword::Awaken => "Awaken",
			CardKeyword::Banding => "Banding",
			CardKeyword::BasicLandcycling => "Basic landcycling",
			CardKeyword::Battalion => "Battalion",
			CardKeyword::BattleCannon => "Battle Cannon",
			CardKeyword::BattleCry => "Battle Cry",
			CardKeyword::BenedictionOfTheOmnissiah => "Benediction of the Omnissiah",
			CardKeyword::Berzerker => "Berzerker",
			CardKeyword::Bestow => "Bestow",
			CardKeyword::BigbySHand => "Bigby's Hand",
			CardKeyword::BioPlasmicBarrage => "Bio-plasmic Barrage",
			CardKeyword::BioPlasmicScream => "Bio-Plasmic Scream",
			CardKeyword::Blitz => "Blitz",
			CardKeyword::BloodChalice => "Blood Chalice",
			CardKeyword::BloodDrain => "Blood Drain",
			CardKeyword::Bloodrush => "Bloodrush",
			CardKeyword::Bloodthirst => "Bloodthirst",
			CardKeyword::Boast => "Boast",
			CardKeyword::BodyThief => "Body Thief",
			CardKeyword::Bolster => "Bolster",
			CardKeyword::BribeTheGuards => "Bribe the Guards",
			CardKeyword::BringItDown => "Bring it Down!",
			CardKeyword::BroodTelepathy => "Brood Telepathy",
			CardKeyword::Bushido => "Bushido",
			CardKeyword::BuyInformation => "Buy Information",
			CardKeyword::Buyback => "Buyback",
			CardKeyword::CalimSBreath => "Calim's Breath",
			CardKeyword::CallForAid => "Call for Aid",
			CardKeyword::Cascade => "Cascade",
			CardKeyword::Casualty => "Casualty",
			CardKeyword::Ceremorphosis => "Ceremorphosis",
			CardKeyword::Chainsword => "Chainsword",
			CardKeyword::Champion => "Champion",
			CardKeyword::Changeling => "Changeling",
			CardKeyword::Channel => "Channel",
			CardKeyword::ChapterMaster => "Chapter Master",
			CardKeyword::ChildrenOfTheCult => "Children of the Cult",
			CardKeyword::Chroma => "Chroma",
			CardKeyword::Cipher => "Cipher",
			CardKeyword::Clash => "Clash",
			CardKeyword::Cleave => "Cleave",
			CardKeyword::Cohort => "Cohort",
			CardKeyword::CommandProtocols => "Command Protocols",
			CardKeyword::CommanderNinjutsu => "Commander ninjutsu",
			CardKeyword::Companion => "Companion",
			CardKeyword::Compleated => "Compleated",
			CardKeyword::ConcealedPosition => "Concealed Position",
			CardKeyword::ConfoundingClouds => "Confounding Clouds",
			CardKeyword::Conjure => "Conjure",
			CardKeyword::Connive => "Connive",
			CardKeyword::Conspire => "Conspire",
			CardKeyword::Constellation => "Constellation",
			CardKeyword::Converge => "Converge",
			CardKeyword::Convert => "Convert",
			CardKeyword::Convoke => "Convoke",
			CardKeyword::Corrupted => "Corrupted",
			CardKeyword::CoruscatingFlames => "Coruscating Flames",
			CardKeyword::CouncilSDilemma => "Council's dilemma",
			CardKeyword::Coven => "Coven",
			CardKeyword::Crew => "Crew",
			CardKeyword::CrownOfMadness => "Crown of Madness",
			CardKeyword::CrushingTeeth => "Crushing Teeth",
			CardKeyword::CumulativeUpkeep => "Cumulative upkeep",
			CardKeyword::CurseOfTheWalkingPox => "Curse of the Walking Pox",
			CardKeyword::Cycling => "Cycling",
			CardKeyword::DaemonSword => "Daemon Sword",
			CardKeyword::Dash => "Dash",
			CardKeyword::Daybound => "Daybound",
			CardKeyword::DeathFrenzy => "Death Frenzy",
			CardKeyword::DeathRay => "Death Ray",
			CardKeyword::Deathtouch => "Deathtouch",
			CardKeyword::Defender => "Defender",
			CardKeyword::Delirium => "Delirium",
			CardKeyword::Delve => "Delve",
			CardKeyword::Demonstrate => "Demonstrate",
			CardKeyword::Desertwalk => "Desertwalk",
			CardKeyword::Detain => "Detain",
			CardKeyword::Dethrone => "Dethrone",
			CardKeyword::DevastatingCharge => "Devastating Charge",
			CardKeyword::Devoid => "Devoid",
			CardKeyword::Devour => "Devour",
			CardKeyword::DevourerOfSouls => "Devourer of Souls",
			CardKeyword::DevouringMonster => "Devouring Monster",
			CardKeyword::Disturb => "Disturb",
			CardKeyword::Domain => "Domain",
			CardKeyword::DoubleAgenda => "Double agenda",
			CardKeyword::DoubleStrike => "Double strike",
			CardKeyword::DrainLife => "Drain Life",
			CardKeyword::Dredge => "Dredge",
			CardKeyword::DynasticAdvisor => "Dynastic Advisor",
			CardKeyword::DynasticCodes => "Dynastic Codes",
			CardKeyword::DynasticCommandNode => "Dynastic Command Node",
			CardKeyword::Echo => "Echo",
			CardKeyword::EliteTroops => "Elite Troops",
			CardKeyword::Embalm => "Embalm",
			CardKeyword::Emerge => "Emerge",
			CardKeyword::Eminence => "Eminence",
			CardKeyword::Enchant => "Enchant",
			CardKeyword::Encore => "Encore",
			CardKeyword::EndlessSwarm => "Endless Swarm",
			CardKeyword::Endurant => "Endurant",
			CardKeyword::Enlist => "Enlist",
			CardKeyword::EnmiticExterminator => "Enmitic Exterminator",
			CardKeyword::Enrage => "Enrage",
			CardKeyword::EnthrallingPerformance => "Enthralling Performance",
			CardKeyword::Entwine => "Entwine",
			CardKeyword::Epic => "Epic",
			CardKeyword::Equip => "Equip",
			CardKeyword::Escalate => "Escalate",
			CardKeyword::Escape => "Escape",
			CardKeyword::Eternalize => "Eternalize",
			CardKeyword::Evoke => "Evoke",
			CardKeyword::Evolve => "Evolve",
			CardKeyword::Exalted => "Exalted",
			CardKeyword::ExecutionerRound => "Executioner Round",
			CardKeyword::Exert => "Exert",
			CardKeyword::ExileCannon => "Exile Cannon",
			CardKeyword::Exploit => "Exploit",
			CardKeyword::Explore => "Explore",
			CardKeyword::Extort => "Extort",
			CardKeyword::Fabricate => "Fabricate",
			CardKeyword::FabricatorClawArray => "Fabricator Claw Array",
			CardKeyword::Fading => "Fading",
			CardKeyword::FallenWarrior => "Fallen Warrior",
			CardKeyword::FastHealing => "Fast Healing",
			CardKeyword::FatefulHour => "Fateful hour",
			CardKeyword::Fateseal => "Fateseal",
			CardKeyword::Fear => "Fear",
			CardKeyword::FeederMandibles => "Feeder Mandibles",
			CardKeyword::Ferocious => "Ferocious",
			CardKeyword::FieldReprogramming => "Field Reprogramming",
			CardKeyword::Fight => "Fight",
			CardKeyword::FireOfTzeentch => "Fire of Tzeentch",
			CardKeyword::FirstStrike => "First strike",
			CardKeyword::Flanking => "Flanking",
			CardKeyword::Flash => "Flash",
			CardKeyword::Flashback => "Flashback",
			CardKeyword::FleshFlayer => "Flesh Flayer",
			CardKeyword::Flying => "Flying",
			CardKeyword::Forecast => "Forecast",
			CardKeyword::Forestcycling => "Forestcycling",
			CardKeyword::Forestwalk => "Forestwalk",
			CardKeyword::Foretell => "Foretell",
			CardKeyword::Formidable => "Formidable",
			CardKeyword::Fortify => "Fortify",
			CardKeyword::FrenziedMetabolism => "Frenzied Metabolism",
			CardKeyword::FrenziedRampage => "Frenzied Rampage",
			CardKeyword::Frenzy => "Frenzy",
			CardKeyword::FriendsForever => "Friends forever",
			CardKeyword::Fuse => "Fuse",
			CardKeyword::GatherYourCourage => "Gather Your Courage",
			CardKeyword::GatheredSwarm => "Gathered Swarm",
			CardKeyword::GenomicEnhancement => "Genomic Enhancement",
			CardKeyword::GiftOfChaos => "Gift of Chaos",
			CardKeyword::GiftOfTiamat => "Gift of Tiamat",
			CardKeyword::Goad => "Goad",
			CardKeyword::Graft => "Graft",
			CardKeyword::GrandStrategist => "Grand Strategist",
			CardKeyword::Grandeur => "Grandeur",
			CardKeyword::GravCannon => "Grav-cannon",
			CardKeyword::Gravestorm => "Gravestorm",
			CardKeyword::GuardianProtocols => "Guardian Protocols",
			CardKeyword::GustOfWind => "Gust of Wind",
			CardKeyword::Haste => "Haste",
			CardKeyword::Haunt => "Haunt",
			CardKeyword::HeavyPowerHammer => "Heavy Power Hammer",
			CardKeyword::HeavyRockCutter => "Heavy Rock Cutter",
			CardKeyword::Hellbent => "Hellbent",
			CardKeyword::HeroSReward => "Hero's Reward",
			CardKeyword::Heroic => "Heroic",
			CardKeyword::Hexproof => "Hexproof",
			CardKeyword::HiddenAgenda => "Hidden agenda",
			CardKeyword::Hideaway => "Hideaway",
			CardKeyword::HiveMind => "Hive Mind",
			CardKeyword::HomunculusServant => "Homunculus Servant",
			CardKeyword::HorrificSymbiosis => "Horrific Symbiosis",
			CardKeyword::Horsemanship => "Horsemanship",
			CardKeyword::HuntForHeresy => "Hunt for Heresy",
			CardKeyword::Imprint => "Imprint",
			CardKeyword::Improvise => "Improvise",
			CardKeyword::Indestructible => "Indestructible",
			CardKeyword::Infect => "Infect",
			CardKeyword::InfestingSpores => "Infesting Spores",
			CardKeyword::Inspired => "Inspired",
			CardKeyword::Intensity => "Intensity",
			CardKeyword::Intimidate => "Intimidate",
			CardKeyword::Investigate => "Investigate",
			CardKeyword::Islandwalk => "Islandwalk",
			CardKeyword::JoinForces => "Join forces",
			CardKeyword::JollyGutpipes => "Jolly Gutpipes",
			CardKeyword::JumpStart => "Jump-start",
			CardKeyword::Kicker => "Kicker",
			CardKeyword::Kinfall => "Kinfall",
			CardKeyword::Kinship => "Kinship",
			CardKeyword::Landfall => "Landfall",
			CardKeyword::Landwalk => "Landwalk",
			CardKeyword::LeadingFromTheFront => "Leading from the Front",
			CardKeyword::Learn => "Learn",
			CardKeyword::Legacy => "Legacy",
			CardKeyword::LevelUp => "Level Up",
			CardKeyword::Lieutenant => "Lieutenant",
			CardKeyword::Lifelink => "Lifelink",
			CardKeyword::LocusOfSlaanesh => "Locus of Slaanesh",
			CardKeyword::LordOfChaos => "Lord of Chaos",
			CardKeyword::LordOfThePyrrhianLegions => "Lord of the Pyrrhian Legions",
			CardKeyword::LoudRuckus => "Loud Ruckus",
			CardKeyword::Madness => "Madness",
			CardKeyword::Magecraft => "Magecraft",
			CardKeyword::MamaSComing => "Mama's Coming",
			CardKeyword::Manifest => "Manifest",
			CardKeyword::MarkOfChaosAscendant => "Mark of Chaos Ascendant",
			CardKeyword::Martyrdom => "Martyrdom",
			CardKeyword::MasterOfMachines => "Master of Machines",
			CardKeyword::MedicusMinistorum => "Medicus Ministorum",
			CardKeyword::Megamorph => "Megamorph",
			CardKeyword::Meld => "Meld",
			CardKeyword::Melee => "Melee",
			CardKeyword::Menace => "Menace",
			CardKeyword::Mentor => "Mentor",
			CardKeyword::Metalcraft => "Metalcraft",
			CardKeyword::Mill => "Mill",
			CardKeyword::Miracle => "Miracle",
			CardKeyword::Modular => "Modular",
			CardKeyword::MoltingExoskeleton => "Molting Exoskeleton",
			CardKeyword::Monstrosity => "Monstrosity",
			CardKeyword::Morbid => "Morbid",
			CardKeyword::Morph => "Morph",
			CardKeyword::Mountaincycling => "Mountaincycling",
			CardKeyword::Mountainwalk => "Mountainwalk",
			CardKeyword::MultiThreatEliminator => "Multi-threat Eliminator",
			CardKeyword::Multikicker => "Multikicker",
			CardKeyword::Mutate => "Mutate",
			CardKeyword::Myriad => "Myriad",
			CardKeyword::NeurotraumalRod => "Neurotraumal Rod",
			CardKeyword::Nightbound => "Nightbound",
			CardKeyword::Ninjutsu => "Ninjutsu",
			CardKeyword::Offering => "Offering",
			CardKeyword::OpenAnAttraction => "Open an Attraction",
			CardKeyword::Outlast => "Outlast",
			CardKeyword::Overload => "Overload",
			CardKeyword::PackTactics => "Pack tactics",
			CardKeyword::Parley => "Parley",
			CardKeyword::Partner => "Partner",
			CardKeyword::Persist => "Persist",
			CardKeyword::PhalanxCommander => "Phalanx Commander",
			CardKeyword::Phasing => "Phasing",
			CardKeyword::Plainscycling => "Plainscycling",
			CardKeyword::Plainswalk => "Plainswalk",
			CardKeyword::Populate => "Populate",
			CardKeyword::PrayForProtection => "Pray for Protection",
			CardKeyword::ProclamatorHailer => "Proclamator Hailer",
			CardKeyword::Proliferate => "Proliferate",
			CardKeyword::Protection => "Protection",
			CardKeyword::ProtectionFightingStyle => "Protection Fighting Style",
			CardKeyword::Protector => "Protector",
			CardKeyword::Prototype => "Prototype",
			CardKeyword::Provoke => "Provoke",
			CardKeyword::Prowess => "Prowess",
			CardKeyword::Prowl => "Prowl",
			CardKeyword::PsionicAdept => "Psionic Adept",
			CardKeyword::PsychicBlades => "Psychic Blades",
			CardKeyword::PsychicStimulus => "Psychic Stimulus",
			CardKeyword::Radiance => "Radiance",
			CardKeyword::Raid => "Raid",
			CardKeyword::Rally => "Rally",
			CardKeyword::Rampage => "Rampage",
			CardKeyword::RapidRegeneration => "Rapid Regeneration",
			CardKeyword::Ravenous => "Ravenous",
			CardKeyword::Reach => "Reach",
			CardKeyword::ReadAhead => "Read Ahead",
			CardKeyword::Rebound => "Rebound",
			CardKeyword::Reconfigure => "Reconfigure",
			CardKeyword::Recover => "Recover",
			CardKeyword::Reinforce => "Reinforce",
			CardKeyword::RelentlessMarch => "Relentless March",
			CardKeyword::Renown => "Renown",
			CardKeyword::Replicate => "Replicate",
			CardKeyword::Retrace => "Retrace",
			CardKeyword::ReverberatingSummons => "Reverberating Summons",
			CardKeyword::Revolt => "Revolt",
			CardKeyword::Riot => "Riot",
			CardKeyword::Ripple => "Ripple",
			CardKeyword::RogueTrader => "Rogue Trader",
			CardKeyword::RollToVisitYourAttractions => "Roll to Visit Your Attractions",
			CardKeyword::Scavenge => "Scavenge",
			CardKeyword::ScorchingRay => "Scorching Ray",
			CardKeyword::Scry => "Scry",
			CardKeyword::SecretsOfTheSoul => "Secrets of the Soul",
			CardKeyword::Seek => "Seek",
			CardKeyword::Shadow => "Shadow",
			CardKeyword::Shroud => "Shroud",
			CardKeyword::Skulk => "Skulk",
			CardKeyword::SleightOfHand => "Sleight of Hand",
			CardKeyword::Slivercycling => "Slivercycling",
			CardKeyword::Soulbond => "Soulbond",
			CardKeyword::Soulshift => "Soulshift",
			CardKeyword::Spectacle => "Spectacle",
			CardKeyword::SpellMastery => "Spell mastery",
			CardKeyword::SpikedRetribution => "Spiked Retribution",
			CardKeyword::Splice => "Splice",
			CardKeyword::SplitSecond => "Split second",
			CardKeyword::Squad => "Squad",
			CardKeyword::Storm => "Storm",
			CardKeyword::StrategicCoordinator => "Strategic Coordinator",
			CardKeyword::Strive => "Strive",
			CardKeyword::SubterraneanAssault => "Subterranean Assault",
			CardKeyword::Sunburst => "Sunburst",
			CardKeyword::Support => "Support",
			CardKeyword::Surge => "Surge",
			CardKeyword::Surveil => "Surveil",
			CardKeyword::Suspend => "Suspend",
			CardKeyword::Swampcycling => "Swampcycling",
			CardKeyword::Swampwalk => "Swampwalk",
			CardKeyword::Sweep => "Sweep",
			CardKeyword::TargetingRelay => "Targeting Relay",
			CardKeyword::TemptingOffer => "Tempting offer",
			CardKeyword::ThreeAutostubs => "Three Autostubs",
			CardKeyword::Threshold => "Threshold",
			CardKeyword::Toxic => "Toxic",
			CardKeyword::Training => "Training",
			CardKeyword::Trample => "Trample",
			CardKeyword::TransdimensionalScout => "Transdimensional Scout",
			CardKeyword::Transfigure => "Transfigure",
			CardKeyword::Transform => "Transform",
			CardKeyword::Transmute => "Transmute",
			CardKeyword::Tribute => "Tribute",
			CardKeyword::Undaunted => "Undaunted",
			CardKeyword::Undergrowth => "Undergrowth",
			CardKeyword::Undying => "Undying",
			CardKeyword::Unearth => "Unearth",
			CardKeyword::Unleash => "Unleash",
			CardKeyword::VanguardSpecies => "Vanguard Species",
			CardKeyword::Vanishing => "Vanishing",
			CardKeyword::VeilOfTime => "Veil of Time",
			CardKeyword::VentureIntoTheDungeon => "Venture into the dungeon",
			CardKeyword::Vigilance => "Vigilance",
			CardKeyword::Ward => "Ward",
			CardKeyword::WeirdInsight => "Weird Insight",
			CardKeyword::WillOfTheCouncil => "Will of the council",
			CardKeyword::WindWalk => "Wind Walk",
			CardKeyword::Wither => "Wither",
			CardKeyword::Wizardcycling => "Wizardcycling",
		}
		;
	}
}
