<?php

declare(strict_types=1);

namespace MallardDuck\MtgCardsSdk\Enums;

use function Symfony\Component\String\u;

/**
 * @see \MallardDuck\MtgCardsSdk\Generator\Actions\GenerateSetCodeAction
 */
enum SetCode: string
{
    public const CODE_NAME_MAP = [
        'afr' => 'Adventures in the Forgotten Realms',
        'aafr' => 'Adventures in the Forgotten Realms Art Series',
        'mafr' => 'Adventures in the Forgotten Realms Minigames',
        'pafr' => 'Adventures in the Forgotten Realms Promos',
        'aer' => 'Aether Revolt',
        'paer' => 'Aether Revolt Promos',
        'arb' => 'Alara Reborn',
        'parb' => 'Alara Reborn Promos',
        'ydmu' => 'Alchemy: Dominaria',
        'hbg' => 'Alchemy Horizons: Baldur\'s Gate',
        'ymid' => 'Alchemy: Innistrad',
        'yneo' => 'Alchemy: Kamigawa',
        'ysnc' => 'Alchemy: New Capenna',
        'yone' => 'Alchemy: Phyrexia',
        'ybro' => 'Alchemy: The Brothers\' War',
        'all' => 'Alliances',
        'akh' => 'Amonkhet',
        'm_p2' => 'Amonkhet Invocations',
        'pakh' => 'Amonkhet Promos',
        'akr' => 'Amonkhet Remastered',
        'ath' => 'Anthologies',
        'atq' => 'Antiquities',
        'apc' => 'Apocalypse',
        'papc' => 'Apocalypse Promos',
        'arn' => 'Arabian Nights',
        'arc' => 'Archenemy',
        'e01' => 'Archenemy: Nicol Bolas',
        'o_e01' => 'Archenemy: Nicol Bolas Schemes',
        'parc' => 'Archenemy Promos',
        'oarc' => 'Archenemy Schemes',
        'anb' => 'Arena Beginner Set',
        'parl' => 'Arena League 1996',
        'pal99' => 'Arena League 1999',
        'pal00' => 'Arena League 2000',
        'pal01' => 'Arena League 2001',
        'pal02' => 'Arena League 2002',
        'pal03' => 'Arena League 2003',
        'pal04' => 'Arena League 2004',
        'pal05' => 'Arena League 2005',
        'pal06' => 'Arena League 2006',
        'ana' => 'Arena New Player Experience',
        'oana' => 'Arena New Player Experience Cards',
        'xana' => 'Arena New Player Experience Extras',
        'palp' => 'Asia Pacific Land Program',
        'past' => 'Astral Cards',
        'avr' => 'Avacyn Restored',
        'pavr' => 'Avacyn Restored Promos',
        'pss1' => 'BFZ Standard Series',
        'aclb' => 'Battle for Baldur\'s Gate Art Series',
        'pclb' => 'Battle for Baldur\'s Gate Promos',
        'bfz' => 'Battle for Zendikar',
        'pbfz' => 'Battle for Zendikar Promos',
        'brb' => 'Battle Royale Box Set',
        'tbth' => 'Battle the Horde',
        'bbd' => 'Battlebond',
        'pbbd' => 'Battlebond Promos',
        'btd' => 'Beatdown Box Set',
        'bok' => 'Betrayers of Kamigawa',
        'pbok' => 'Betrayers of Kamigawa Promos',
        'bng' => 'Born of the Gods',
        'thp2' => 'Born of the Gods Hero\'s Path',
        'pbng' => 'Born of the Gods Promos',
        'pcel' => 'Celebration Cards',
        'q07' => 'Challenger Decks 2022',
        'chk' => 'Champions of Kamigawa',
        'pchk' => 'Champions of Kamigawa Promos',
        'pcmp' => 'Champs and States',
        'chr' => 'Chronicles',
        '6_ed' => 'Classic Sixth Edition',
        'csp' => 'Coldsnap',
        'pcsp' => 'Coldsnap Promos',
        'cst' => 'Coldsnap Theme Decks',
        'ced' => 'Collectors’ Edition',
        'cmd' => 'Commander 2011',
        'pcmd' => 'Commander 2011 Launch Party',
        'ocmd' => 'Commander 2011 Oversized',
        'c13' => 'Commander 2013',
        'o_c13' => 'Commander 2013 Oversized',
        'c14' => 'Commander 2014',
        'o_c14' => 'Commander 2014 Oversized',
        'c15' => 'Commander 2015',
        'o_c15' => 'Commander 2015 Oversized',
        'c16' => 'Commander 2016',
        'o_c16' => 'Commander 2016 Oversized',
        'c17' => 'Commander 2017',
        'o_c17' => 'Commander 2017 Oversized',
        'c18' => 'Commander 2018',
        'o_c18' => 'Commander 2018 Oversized',
        'c19' => 'Commander 2019',
        'o_c19' => 'Commander 2019 Oversized',
        'c20' => 'Commander 2020',
        'o_c20' => 'Commander 2020 Oversized',
        'c21' => 'Commander 2021',
        'o_c21' => 'Commander 2021 Display Commanders',
        'cma' => 'Commander Anthology',
        'c_m2' => 'Commander Anthology Volume II',
        'c_c2' => 'Commander Collection: Black',
        'c_c1' => 'Commander Collection: Green',
        'cmr' => 'Commander Legends',
        'clb' => 'Commander Legends: Battle for Baldur\'s Gate',
        'mclb' => 'Commander Legends: Battle for Baldur\'s Gate Minigames',
        'cmm' => 'Commander Masters',
        'c_m1' => 'Commander\'s Arsenal',
        'ocm1' => 'Commander\'s Arsenal Oversized',
        'con' => 'Conflux',
        'pcon' => 'Conflux Promos',
        'cns' => 'Conspiracy',
        'pcns' => 'Conspiracy Promos',
        'c_n2' => 'Conspiracy: Take the Crown',
        'm19' => 'Core Set 2019',
        'p_m19' => 'Core Set 2019 Promos',
        'm20' => 'Core Set 2020',
        'p_m20' => 'Core Set 2020 Promos',
        'm21' => 'Core Set 2021',
        'p_m21' => 'Core Set 2021 Promos',
        'avow' => 'Crimson Vow Art Series',
        'voc' => 'Crimson Vow Commander',
        'ovoc' => 'Crimson Vow Commander Display Commanders',
        'plgm' => 'DCI Legend Membership',
        'pdci' => 'DCI Promos',
        'dka' => 'Dark Ascension',
        'pdka' => 'Dark Ascension Promos',
        'dst' => 'Darksteel',
        'pdst' => 'Darksteel Promos',
        'dkm' => 'Deckmasters',
        'tdag' => 'Defeat a God',
        'dis' => 'Dissension',
        'pdis' => 'Dissension Promos',
        'dom' => 'Dominaria',
        'pdom' => 'Dominaria Promos',
        'dmr' => 'Dominaria Remastered',
        'dmu' => 'Dominaria United',
        'admu' => 'Dominaria United Art Series',
        'dmc' => 'Dominaria United Commander',
        'wdmu' => 'Dominaria United Japanese Promo Tokens',
        'mdmu' => 'Dominaria United Minigames',
        'pdmu' => 'Dominaria United Promos',
        '2_xm' => 'Double Masters',
        '2_x2' => 'Double Masters 2022',
        'pdrc' => 'Dragon Con',
        'dgm' => 'Dragon\'s Maze',
        'pdgm' => 'Dragon\'s Maze Promos',
        'dtk' => 'Dragons of Tarkir',
        'pdtk' => 'Dragons of Tarkir Promos',
        'ddh' => 'Duel Decks: Ajani vs. Nicol Bolas',
        'dvd' => 'Duel Decks Anthology: Divine vs. Demonic',
        'evg' => 'Duel Decks Anthology: Elves vs. Goblins',
        'gvl' => 'Duel Decks Anthology: Garruk vs. Liliana',
        'jvc' => 'Duel Decks Anthology: Jace vs. Chandra',
        'ddq' => 'Duel Decks: Blessed vs. Cursed',
        'ddc' => 'Duel Decks: Divine vs. Demonic',
        'ddo' => 'Duel Decks: Elspeth vs. Kiora',
        'ddf' => 'Duel Decks: Elspeth vs. Tezzeret',
        'd_d1' => 'Duel Decks: Elves vs. Goblins',
        'ddu' => 'Duel Decks: Elves vs. Inventors',
        'ddd' => 'Duel Decks: Garruk vs. Liliana',
        'ddl' => 'Duel Decks: Heroes vs. Monsters',
        'ddj' => 'Duel Decks: Izzet vs. Golgari',
        'd_d2' => 'Duel Decks: Jace vs. Chandra',
        'ddm' => 'Duel Decks: Jace vs. Vraska',
        'ddg' => 'Duel Decks: Knights vs. Dragons',
        'ddt' => 'Duel Decks: Merfolk vs. Goblins',
        'dds' => 'Duel Decks: Mind vs. Might',
        't_d2' => 'Duel Decks: Mirrodin Pure vs. New Phyrexia',
        'ddr' => 'Duel Decks: Nissa vs. Ob Nixilis',
        'dde' => 'Duel Decks: Phyrexia vs. the Coalition',
        'ddk' => 'Duel Decks: Sorin vs. Tibalt',
        'ddn' => 'Duel Decks: Speed vs. Cunning',
        'ddi' => 'Duel Decks: Venser vs. Koth',
        'ddp' => 'Duel Decks: Zendikar vs. Eldrazi',
        'dpa' => 'Duels of the Planeswalkers',
        'pdtp' => 'Duels of the Planeswalkers 2009 Promos',
        'pdp10' => 'Duels of the Planeswalkers 2010 Promos',
        'pdp12' => 'Duels of the Planeswalkers 2012 Promos',
        'pdp13' => 'Duels of the Planeswalkers 2013 Promos',
        'pdp14' => 'Duels of the Planeswalkers 2014 Promos',
        'pdp15' => 'Duels of the Planeswalkers 2015 Promos',
        '8_ed' => 'Eighth Edition',
        'p8_ed' => 'Eighth Edition Promos',
        'emn' => 'Eldritch Moon',
        'pemn' => 'Eldritch Moon Promos',
        'ema' => 'Eternal Masters',
        'pewk' => 'Eternal Weekend 2022',
        'pelp' => 'European Land Program',
        'eve' => 'Eventide',
        'peve' => 'Eventide Promos',
        'exo' => 'Exodus',
        'pexo' => 'Exodus Promos',
        'e_a1' => 'Explorer Anthology 1',
        'e_a2' => 'Explorer Anthology 2',
        'e02' => 'Explorers of Ixalan',
        'bchr' => 'FBB Chronicles',
        'tfth' => 'Face the Hydra',
        'fem' => 'Fallen Empires',
        'frf' => 'Fate Reforged',
        'c_p2' => 'Fate Reforged Clash Pack',
        'pfrf' => 'Fate Reforged Promos',
        'p15_a' => '15th Anniversary Cards',
        '5_dn' => 'Fifth Dawn',
        'p5_dn' => 'Fifth Dawn Promos',
        '5_ed' => 'Fifth Edition',
        'fbb' => 'Foreign Black Border',
        'afc' => 'Forgotten Realms Commander',
        'oafc' => 'Forgotten Realms Commander Display Commanders',
        '4_ed' => 'Fourth Edition',
        '4_bb' => 'Fourth Edition Foreign Black Border',
        'fnm' => 'Friday Night Magic 2000',
        'f01' => 'Friday Night Magic 2001',
        'f02' => 'Friday Night Magic 2002',
        'f03' => 'Friday Night Magic 2003',
        'f04' => 'Friday Night Magic 2004',
        'f05' => 'Friday Night Magic 2005',
        'f06' => 'Friday Night Magic 2006',
        'f07' => 'Friday Night Magic 2007',
        'f08' => 'Friday Night Magic 2008',
        'f09' => 'Friday Night Magic 2009',
        'f10' => 'Friday Night Magic 2010',
        'f11' => 'Friday Night Magic 2011',
        'f12' => 'Friday Night Magic 2012',
        'f13' => 'Friday Night Magic 2013',
        'f14' => 'Friday Night Magic 2014',
        'f15' => 'Friday Night Magic 2015',
        'f16' => 'Friday Night Magic 2016',
        'f17' => 'Friday Night Magic 2017',
        'f18' => 'Friday Night Magic 2018',
        'v15' => 'From the Vault: Angels',
        'v14' => 'From the Vault: Annihilation',
        'drb' => 'From the Vault: Dragons',
        'v09' => 'From the Vault: Exiled',
        'v11' => 'From the Vault: Legends',
        'v16' => 'From the Vault: Lore',
        'v12' => 'From the Vault: Realms',
        'v10' => 'From the Vault: Relics',
        'v17' => 'From the Vault: Transform',
        'v13' => 'From the Vault: Twenty',
        'fut' => 'Future Sight',
        'pfut' => 'Future Sight Promos',
        'g_k1' => 'GRN Guild Kit',
        'prwk' => 'GRN Ravnica Weekend',
        'gdy' => 'Game Day Promos',
        'gnt' => 'Game Night',
        'g_n2' => 'Game Night 2019',
        'g_n3' => 'Game Night: Free-for-All',
        'gtc' => 'Gatecrash',
        'pgtc' => 'Gatecrash Promos',
        'pgtw' => 'Gateway 2006',
        'p_g07' => 'Gateway 2007',
        'p_g08' => 'Gateway 2008',
        'g_s1' => 'Global Series Jiang Yanggu & Mu Yanling',
        'pgpx' => 'Grand Prix Promos',
        'gpt' => 'Guildpact',
        'pgpt' => 'Guildpact Promos',
        'grn' => 'Guilds of Ravnica',
        'pgrn' => 'Guilds of Ravnica Promos',
        'pgru' => 'Guru',
        'phuk' => 'Hachette UK',
        'hho' => 'Happy Holidays',
        'phpr' => 'HarperPrism Book Promos',
        'h17' => 'HasCon 2017',
        'phed' => 'Heads I Win, Tails You Lose',
        'h_a1' => 'Historic Anthology 1',
        'h_a2' => 'Historic Anthology 2',
        'h_a3' => 'Historic Anthology 3',
        'h_a4' => 'Historic Anthology 4',
        'h_a5' => 'Historic Anthology 5',
        'h_a6' => 'Historic Anthology 6',
        'phj' => 'Hobby Japan Promos',
        'hml' => 'Homelands',
        'hou' => 'Hour of Devastation',
        'phou' => 'Hour of Devastation Promos',
        'p_i13' => 'IDW Comics 2013',
        'p_i14' => 'IDW Comics 2014',
        'pidw' => 'IDW Comics Inserts',
        'ice' => 'Ice Age',
        'ima' => 'Iconic Masters',
        'iko' => 'Ikoria: Lair of Behemoths',
        'piko' => 'Ikoria: Lair of Behemoths Promos',
        'isd' => 'Innistrad',
        'vow' => 'Innistrad: Crimson Vow',
        'mvow' => 'Innistrad: Crimson Vow Minigames',
        'pvow' => 'Innistrad: Crimson Vow Promos',
        'svow' => 'Innistrad: Crimson Vow Substitute Cards',
        'dbl' => 'Innistrad: Double Feature',
        'mid' => 'Innistrad: Midnight Hunt',
        'mmid' => 'Innistrad: Midnight Hunt Minigames',
        'pmid' => 'Innistrad: Midnight Hunt Promos',
        'smid' => 'Innistrad: Midnight Hunt Substitute Cards',
        'pisd' => 'Innistrad Promos',
        'cei' => 'Intl. Collectors’ Edition',
        'itp' => 'Introductory Two-Player Set',
        'inv' => 'Invasion',
        'pinv' => 'Invasion Promos',
        'xln' => 'Ixalan',
        'pxln' => 'Ixalan Promos',
        'pjjt' => 'Japan Junior Tournament',
        'jou' => 'Journey into Nyx',
        'thp3' => 'Journey into Nyx Hero\'s Path',
        'pjou' => 'Journey into Nyx Promos',
        'jgp' => 'Judge Gift Cards 1998',
        'g99' => 'Judge Gift Cards 1999',
        'g00' => 'Judge Gift Cards 2000',
        'g01' => 'Judge Gift Cards 2001',
        'g02' => 'Judge Gift Cards 2002',
        'g03' => 'Judge Gift Cards 2003',
        'g04' => 'Judge Gift Cards 2004',
        'g05' => 'Judge Gift Cards 2005',
        'g06' => 'Judge Gift Cards 2006',
        'g07' => 'Judge Gift Cards 2007',
        'g08' => 'Judge Gift Cards 2008',
        'g09' => 'Judge Gift Cards 2009',
        'g10' => 'Judge Gift Cards 2010',
        'g11' => 'Judge Gift Cards 2011',
        'j12' => 'Judge Gift Cards 2012',
        'j13' => 'Judge Gift Cards 2013',
        'j14' => 'Judge Gift Cards 2014',
        'j15' => 'Judge Gift Cards 2015',
        'j16' => 'Judge Gift Cards 2016',
        'j17' => 'Judge Gift Cards 2017',
        'j18' => 'Judge Gift Cards 2018',
        'j19' => 'Judge Gift Cards 2019',
        'j20' => 'Judge Gift Cards 2020',
        'p_j21' => 'Judge Gift Cards 2021',
        'p22' => 'Judge Gift Cards 2022',
        'p23' => 'Judge Gift Cards 2023',
        'jud' => 'Judgment',
        'pjud' => 'Judgment Promos',
        'jmp' => 'Jumpstart',
        'j22' => 'Jumpstart 2022',
        'f_j22' => 'Jumpstart 2022 Front Cards',
        'ajmp' => 'Jumpstart Arena Exclusives',
        'fjmp' => 'Jumpstart Front Cards',
        'j21' => 'Jumpstart: Historic Horizons',
        'pjas' => 'Junior APAC Series',
        'pjse' => 'Junior Series Europe',
        'psus' => 'Junior Super Series',
        'kld' => 'Kaladesh',
        'mps' => 'Kaladesh Inventions',
        'pkld' => 'Kaladesh Promos',
        'klr' => 'Kaladesh Remastered',
        'khm' => 'Kaldheim',
        'akhm' => 'Kaldheim Art Series',
        'khc' => 'Kaldheim Commander',
        'mkhm' => 'Kaldheim Minigames',
        'pkhm' => 'Kaldheim Promos',
        'skhm' => 'Kaldheim Substitute Cards',
        'neo' => 'Kamigawa: Neon Dynasty',
        'mneo' => 'Kamigawa: Neon Dynasty Minigames',
        'pneo' => 'Kamigawa: Neon Dynasty Promos',
        'sneo' => 'Kamigawa: Neon Dynasty Substitute Cards',
        'ktk' => 'Khans of Tarkir',
        'pktk' => 'Khans of Tarkir Promos',
        'l12' => 'League Tokens 2012',
        'l13' => 'League Tokens 2013',
        'l14' => 'League Tokens 2014',
        'l15' => 'League Tokens 2015',
        'l16' => 'League Tokens 2016',
        'l17' => 'League Tokens 2017',
        'olgc' => 'Legacy Championship',
        'p_z1' => 'Legendary Cube Prize Pack',
        'leg' => 'Legends',
        'lgn' => 'Legions',
        'plgn' => 'Legions Promos',
        'lea' => 'Limited Edition Alpha',
        'leb' => 'Limited Edition Beta',
        'ltr' => 'Lord of the Rings: Tales of Middle-Earth',
        'lrw' => 'Lorwyn',
        'plrw' => 'Lorwyn Promos',
        'plg20' => 'Love Your LGS 2020',
        'plg21' => 'Love Your LGS 2021',
        'plg22' => 'Love Your LGS 2022',
        'plny' => 'Lunar New Year 2018',
        'ppc1' => 'M15 Prerelease Challenge',
        'g18' => 'M19 Gift Pack',
        'pss3' => 'M19 Standard Showdown',
        'ppp1' => 'M20 Promo Packs',
        'pana' => 'MTG Arena Promos',
        'm10' => 'Magic 2010',
        'p_m10' => 'Magic 2010 Promos',
        'm11' => 'Magic 2011',
        'p_m11' => 'Magic 2011 Promos',
        'm12' => 'Magic 2012',
        'p_m12' => 'Magic 2012 Promos',
        'm13' => 'Magic 2013',
        'p_m13' => 'Magic 2013 Promos',
        'm14' => 'Magic 2014',
        'p_m14' => 'Magic 2014 Promos',
        'm15' => 'Magic 2015',
        'c_p1' => 'Magic 2015 Clash Pack',
        'p_m15' => 'Magic 2015 Promos',
        'p_f19' => 'MagicFest 2019',
        'p_f20' => 'MagicFest 2020',
        'p_f21' => 'MagicFest 2021',
        'pmoa' => 'Magic Online Avatars',
        'prm' => 'Magic Online Promos',
        't_d0' => 'Magic Online Theme Decks',
        'ori' => 'Magic Origins',
        'c_p3' => 'Magic Origins Clash Pack',
        'pori' => 'Magic Origins Promos',
        'mpr' => 'Magic Player Rewards 2001',
        'p_r2' => 'Magic Player Rewards 2002',
        'p03' => 'Magic Player Rewards 2003',
        'p04' => 'Magic Player Rewards 2004',
        'p05' => 'Magic Player Rewards 2005',
        'p06' => 'Magic Player Rewards 2006',
        'p07' => 'Magic Player Rewards 2007',
        'p08' => 'Magic Player Rewards 2008',
        'p09' => 'Magic Player Rewards 2009',
        'p10' => 'Magic Player Rewards 2010',
        'p11' => 'Magic Player Rewards 2011',
        'pmps' => 'Magic Premiere Shop 2005',
        'pmps06' => 'Magic Premiere Shop 2006',
        'pmps07' => 'Magic Premiere Shop 2007',
        'pmps08' => 'Magic Premiere Shop 2008',
        'pmps09' => 'Magic Premiere Shop 2009',
        'pmps10' => 'Magic Premiere Shop 2010',
        'pmps11' => 'Magic Premiere Shop 2011',
        'mom' => 'March of the Machine',
        'moc' => 'March of the Machine Commander',
        'mat' => 'March of the Machine: The Aftermath',
        'a25' => 'Masters 25',
        'm_e1' => 'Masters Edition',
        'm_e2' => 'Masters Edition II',
        'm_e3' => 'Masters Edition III',
        'm_e4' => 'Masters Edition IV',
        'pmei' => 'Media Inserts',
        'mmq' => 'Mercadian Masques',
        'pmmq' => 'Mercadian Masques Promos',
        'pmic' => 'MicroProse Promos',
        'amid' => 'Midnight Hunt Art Series',
        'mic' => 'Midnight Hunt Commander',
        'omic' => 'Midnight Hunt Commander Display Commanders',
        'mir' => 'Mirage',
        'mrd' => 'Mirrodin',
        'mbs' => 'Mirrodin Besieged',
        'pmbs' => 'Mirrodin Besieged Promos',
        'pmrd' => 'Mirrodin Promos',
        'pbook' => 'Miscellaneous Book Promos',
        'm_d1' => 'Modern Event Deck 2014',
        'm_h1' => 'Modern Horizons',
        'h1_r' => 'Modern Horizons 1 Timeshifts',
        'm_h2' => 'Modern Horizons 2',
        'amh2' => 'Modern Horizons 2 Art Series',
        'mmh2' => 'Modern Horizons 2 Minigames',
        'pmh2' => 'Modern Horizons 2 Promos',
        'amh1' => 'Modern Horizons Art Series',
        'pmh1' => 'Modern Horizons Promos',
        'mma' => 'Modern Masters',
        'm_m2' => 'Modern Masters 2015',
        'm_m3' => 'Modern Masters 2017',
        'mor' => 'Morningtide',
        'pmor' => 'Morningtide Promos',
        'mgb' => 'Multiverse Gift Box',
        'mul' => 'Multiverse Legends',
        'm_b1' => 'Mystery Booster',
        'cmb1' => 'Mystery Booster Playtest Cards 2019',
        'cmb2' => 'Mystery Booster Playtest Cards 2021',
        'fmb1' => 'Mystery Booster Retail Edition Foils',
        'med' => 'Mythic Edition',
        'pnat' => 'Nationals Promos',
        'nem' => 'Nemesis',
        'pnem' => 'Nemesis Promos',
        'aneo' => 'Neon Dynasty Art Series',
        'nec' => 'Neon Dynasty Commander',
        'asnc' => 'New Capenna Art Series',
        'ncc' => 'New Capenna Commander',
        'pncc' => 'New Capenna Commander Promos',
        'nph' => 'New Phyrexia',
        'pnph' => 'New Phyrexia Promos',
        '9_ed' => 'Ninth Edition',
        'p9_ed' => 'Ninth Edition Promos',
        'ogw' => 'Oath of the Gatewatch',
        'pogw' => 'Oath of the Gatewatch Promos',
        'ody' => 'Odyssey',
        'pody' => 'Odyssey Promos',
        'ons' => 'Onslaught',
        'pons' => 'Onslaught Promos',
        'phel' => 'Open the Helvault',
        'o90_p' => 'Oversized 90\'s Promos',
        'olep' => 'Oversized League Prizes',
        'one' => 'Phyrexia: All Will Be One',
        'aone' => 'Phyrexia: All Will Be One Art Series',
        'onc' => 'Phyrexia: All Will Be One Commander',
        'wone' => 'Phyrexia: All Will Be One Japanese Promo Tokens',
        'fone' => 'Phyrexia: All Will Be One Jumpstart Front Cards',
        'mone' => 'Phyrexia: All Will Be One Minigames',
        'pone' => 'Phyrexia: All Will Be One Promos',
        'q06' => 'Pioneer Challenger Decks 2021',
        'q08' => 'Pioneer Challenger Decks 2022',
        'plc' => 'Planar Chaos',
        'pplc' => 'Planar Chaos Promos',
        'hop' => 'Planechase',
        'p_c2' => 'Planechase 2012',
        'opc2' => 'Planechase 2012 Planes',
        'pca' => 'Planechase Anthology',
        'opca' => 'Planechase Anthology Planes',
        'ohop' => 'Planechase Planes',
        'phop' => 'Planechase Promos',
        'pls' => 'Planeshift',
        'ppls' => 'Planeshift Promos',
        'pwcs' => 'Planeswalker Championship Promos',
        'ptg' => 'Ponies: The Galloping',
        'por' => 'Portal',
        'p02' => 'Portal Second Age',
        'ptk' => 'Portal Three Kingdoms',
        'pptk' => 'Portal: Three Kingdoms Promos',
        'p_d2' => 'Premium Deck Series: Fire and Lightning',
        'p_d3' => 'Premium Deck Series: Graveborn',
        'h09' => 'Premium Deck Series: Slivers',
        'ptc' => 'Pro Tour Collector Set',
        'ppro' => 'Pro Tour Promos',
        'pcy' => 'Prophecy',
        'ppcy' => 'Prophecy Promos',
        'g_k2' => 'RNA Guild Kit',
        'prw2' => 'RNA Ravnica Weekend',
        'rna' => 'Ravnica Allegiance',
        'prna' => 'Ravnica Allegiance Promos',
        'rav' => 'Ravnica: City of Guilds',
        'prav' => 'Ravnica: City of Guilds Promos',
        'pred' => 'Redemption Program',
        'prcq' => 'Regional Championship Qualifiers 2022',
        'p_r23' => 'Regional Championship Qualifiers 2023',
        'ren' => 'Renaissance',
        'pres' => 'Resale Promos',
        'rtr' => 'Return to Ravnica',
        'prtr' => 'Return to Ravnica Promos',
        '3_ed' => 'Revised Edition',
        'rin' => 'Rinascimento',
        'roe' => 'Rise of the Eldrazi',
        'proe' => 'Rise of the Eldrazi Promos',
        'rix' => 'Rivals of Ixalan',
        'prix' => 'Rivals of Ixalan Promos',
        'rqs' => 'Rivals Quick Start Set',
        'psal' => 'Salvat 2005',
        'p_s11' => 'Salvat 2011',
        'psdc' => 'San Diego Comic-Con 2013',
        'p_s14' => 'San Diego Comic-Con 2014',
        'p_s15' => 'San Diego Comic-Con 2015',
        'p_s16' => 'San Diego Comic-Con 2016',
        'p_s17' => 'San Diego Comic-Con 2017',
        'p_s18' => 'San Diego Comic-Con 2018',
        'p_s19' => 'San Diego Comic-Con 2019',
        'sok' => 'Saviors of Kamigawa',
        'psok' => 'Saviors of Kamigawa Promos',
        'som' => 'Scars of Mirrodin',
        'psom' => 'Scars of Mirrodin Promos',
        'scg' => 'Scourge',
        'pscg' => 'Scourge Promos',
        'slc' => 'Secret Lair 30th Anniversary Countdown Kit',
        'sld' => 'Secret Lair Drop',
        'slp' => 'Secret Lair Showdown',
        'slu' => 'Secret Lair: Ultimate Edition',
        'psdg' => 'Sega Dreamcast Cards',
        '7_ed' => 'Seventh Edition',
        'shm' => 'Shadowmoor',
        'pshm' => 'Shadowmoor Promos',
        'soi' => 'Shadows over Innistrad',
        'psoi' => 'Shadows over Innistrad Promos',
        'sir' => 'Shadows Over Innistrad Remastered',
        'ala' => 'Shards of Alara',
        'pala' => 'Shards of Alara Promos',
        's_s3' => 'Signature Spellbook: Chandra',
        's_s2' => 'Signature Spellbook: Gideon',
        's_s1' => 'Signature Spellbook: Jace',
        's99' => 'Starter 1999',
        's00' => 'Starter 2000',
        'scd' => 'Starter Commander Decks',
        'sch' => 'Store Championships',
        'snc' => 'Streets of New Capenna',
        'msnc' => 'Streets of New Capenna Minigames',
        'psnc' => 'Streets of New Capenna Promos',
        'ptsnc' => 'Streets of New Capenna Southeast Asia Tokens',
        'astx' => 'Strixhaven Art Series',
        'sta' => 'Strixhaven Mystical Archive',
        'stx' => 'Strixhaven: School of Mages',
        'mstx' => 'Strixhaven: School of Mages Minigames',
        'pstx' => 'Strixhaven: School of Mages Promos',
        'sstx' => 'Strixhaven: School of Mages Substitute Cards',
        'sth' => 'Stronghold',
        'psth' => 'Stronghold Promos',
        'sum' => 'Summer Magic / Edgar',
        'psum' => 'Summer of Magic',
        'psvc' => 'Summer Vacation Promos 2022',
        'ptkdf' => 'Tarkir Dragonfury',
        'tmp' => 'Tempest',
        'ptmp' => 'Tempest Promos',
        'tpr' => 'Tempest Remastered',
        '10_e' => 'Tenth Edition',
        'p10_e' => 'Tenth Edition Promos',
        'bro' => 'The Brothers\' War',
        'abro' => 'The Brothers\' War Art Series',
        'brc' => 'The Brothers\' War Commander',
        'mbro' => 'The Brothers\' War Minigames',
        'pbro' => 'The Brothers\' War Promos',
        'brr' => 'The Brothers\' War Retro Artifacts',
        'drk' => 'The Dark',
        'plist' => 'The List',
        'uplist' => 'The List (Unfinity Foil Edition)',
        'ths' => 'Theros',
        'thb' => 'Theros Beyond Death',
        'pthb' => 'Theros Beyond Death Promos',
        'thp1' => 'Theros Hero\'s Path',
        'pths' => 'Theros Promos',
        '30_a' => '30th Anniversary Edition',
        'p30_h' => '30th Anniversary History Promos',
        'p30_a' => '30th Anniversary Play Promos',
        'eld' => 'Throne of Eldraine',
        'peld' => 'Throne of Eldraine Promos',
        'tsp' => 'Time Spiral',
        'ptsp' => 'Time Spiral Promos',
        'tsr' => 'Time Spiral Remastered',
        'tsb' => 'Time Spiral Timeshifted',
        'tor' => 'Torment',
        'ptor' => 'Torment Promos',
        'bot' => 'Transformers',
        'p_z2' => 'Treasure Chest',
        'p2_hg' => 'Two-Headed Giant Tournament',
        'p_h18' => '2018 Heroes of the Realm',
        'p_h19' => '2019 Heroes of the Realm',
        'g17' => '2017 Gift Pack',
        'p_h17' => '2017 Heroes of the Realm',
        'phtr' => '2016 Heroes of the Realm',
        'p_h20' => '2020 Heroes of the Realm',
        'p_h21' => '2021 Heroes of the Realm',
        'purl' => 'URL/Convention Promos',
        'ugin' => 'Ugin\'s Fate',
        'puma' => 'Ultimate Box Topper',
        'uma' => 'Ultimate Masters',
        'unf' => 'Unfinity',
        'sunf' => 'Unfinity Sticker Sheets',
        'ugl' => 'Unglued',
        'unh' => 'Unhinged',
        'punh' => 'Unhinged Promos',
        'slx' => 'Universes Within',
        '2_ed' => 'Unlimited Edition',
        'und' => 'Unsanctioned',
        'ust' => 'Unstable',
        'pust' => 'Unstable Promos',
        'uds' => 'Urza\'s Destiny',
        'puds' => 'Urza\'s Destiny Promos',
        'ulg' => 'Urza\'s Legacy',
        'pulg' => 'Urza\'s Legacy Promos',
        'usg' => 'Urza\'s Saga',
        'pusg' => 'Urza\'s Saga Promos',
        'pvan' => 'Vanguard Series',
        'ovnt' => 'Vintage Championship',
        'vma' => 'Vintage Masters',
        'vis' => 'Visions',
        'war' => 'War of the Spark',
        'pwar' => 'War of the Spark Promos',
        '40_k' => 'Warhammer 40,000 Commander',
        'wth' => 'Weatherlight',
        'w16' => 'Welcome Deck 2016',
        'w17' => 'Welcome Deck 2017',
        'pwos' => 'Wizards of the Coast Online Store',
        'pwpn' => 'Wizards Play Network 2008',
        'p_w09' => 'Wizards Play Network 2009',
        'p_w10' => 'Wizards Play Network 2010',
        'p_w11' => 'Wizards Play Network 2011',
        'p_w12' => 'Wizards Play Network 2012',
        'p_w21' => 'Wizards Play Network 2021',
        'p_w22' => 'Wizards Play Network 2022',
        'p_w23' => 'Wizards Play Network 2023',
        'w_c97' => 'World Championship Decks 1997',
        'w_c98' => 'World Championship Decks 1998',
        'w_c99' => 'World Championship Decks 1999',
        'w_c00' => 'World Championship Decks 2000',
        'w_c01' => 'World Championship Decks 2001',
        'w_c02' => 'World Championship Decks 2002',
        'w_c03' => 'World Championship Decks 2003',
        'w_c04' => 'World Championship Decks 2004',
        'pwor' => 'World Championship Promos',
        'wmc' => 'World Magic Cup Qualifiers',
        'wwk' => 'Worldwake',
        'pwwk' => 'Worldwake Promos',
        'pss2' => 'XLN Standard Showdown',
        'pxtc' => 'XLN Treasure Chest',
        'p_l21' => 'Year of the Ox 2021',
        'p_l23' => 'Year of the Rabbit 2023',
        'p_l22' => 'Year of the Tiger 2022',
        'zen' => 'Zendikar',
        'exp' => 'Zendikar Expeditions',
        'pzen' => 'Zendikar Promos',
        'znr' => 'Zendikar Rising',
        'aznr' => 'Zendikar Rising Art Series',
        'znc' => 'Zendikar Rising Commander',
        'zne' => 'Zendikar Rising Expeditions',
        'mznr' => 'Zendikar Rising Minigames',
        'pznr' => 'Zendikar Rising Promos',
        'sznr' => 'Zendikar Rising Substitute Cards',
    ];

    case AdventuresInTheForgottenRealms = 'afr';
    case AdventuresInTheForgottenRealmsArtSeries = 'aafr';
    case AdventuresInTheForgottenRealmsMinigames = 'mafr';
    case AdventuresInTheForgottenRealmsPromos = 'pafr';
    case AetherRevolt = 'aer';
    case AetherRevoltPromos = 'paer';
    case AlaraReborn = 'arb';
    case AlaraRebornPromos = 'parb';
    case AlchemyDominaria = 'ydmu';
    case AlchemyHorizonsBaldurSGate = 'hbg';
    case AlchemyInnistrad = 'ymid';
    case AlchemyKamigawa = 'yneo';
    case AlchemyNewCapenna = 'ysnc';
    case AlchemyPhyrexia = 'yone';
    case AlchemyTheBrothersWar = 'ybro';
    case Alliances = 'all';
    case Amonkhet = 'akh';
    case AmonkhetInvocations = 'm_p2';
    case AmonkhetPromos = 'pakh';
    case AmonkhetRemastered = 'akr';
    case Anthologies = 'ath';
    case Antiquities = 'atq';
    case Apocalypse = 'apc';
    case ApocalypsePromos = 'papc';
    case ArabianNights = 'arn';
    case Archenemy = 'arc';
    case ArchenemyNicolBolas = 'e01';
    case ArchenemyNicolBolasSchemes = 'o_e01';
    case ArchenemyPromos = 'parc';
    case ArchenemySchemes = 'oarc';
    case ArenaBeginnerSet = 'anb';
    case ArenaLeague1996 = 'parl';
    case ArenaLeague1999 = 'pal99';
    case ArenaLeague2000 = 'pal00';
    case ArenaLeague2001 = 'pal01';
    case ArenaLeague2002 = 'pal02';
    case ArenaLeague2003 = 'pal03';
    case ArenaLeague2004 = 'pal04';
    case ArenaLeague2005 = 'pal05';
    case ArenaLeague2006 = 'pal06';
    case ArenaNewPlayerExperience = 'ana';
    case ArenaNewPlayerExperienceCards = 'oana';
    case ArenaNewPlayerExperienceExtras = 'xana';
    case AsiaPacificLandProgram = 'palp';
    case AstralCards = 'past';
    case AvacynRestored = 'avr';
    case AvacynRestoredPromos = 'pavr';
    case BFZStandardSeries = 'pss1';
    case BattleForBaldurSGateArtSeries = 'aclb';
    case BattleForBaldurSGatePromos = 'pclb';
    case BattleForZendikar = 'bfz';
    case BattleForZendikarPromos = 'pbfz';
    case BattleRoyaleBoxSet = 'brb';
    case BattleTheHorde = 'tbth';
    case Battlebond = 'bbd';
    case BattlebondPromos = 'pbbd';
    case BeatdownBoxSet = 'btd';
    case BetrayersOfKamigawa = 'bok';
    case BetrayersOfKamigawaPromos = 'pbok';
    case BornOfTheGods = 'bng';
    case BornOfTheGodsHeroSPath = 'thp2';
    case BornOfTheGodsPromos = 'pbng';
    case CelebrationCards = 'pcel';
    case ChallengerDecks2022 = 'q07';
    case ChampionsOfKamigawa = 'chk';
    case ChampionsOfKamigawaPromos = 'pchk';
    case ChampsAndStates = 'pcmp';
    case Chronicles = 'chr';
    case ClassicSixthEdition = '6_ed';
    case Coldsnap = 'csp';
    case ColdsnapPromos = 'pcsp';
    case ColdsnapThemeDecks = 'cst';
    case CollectorsEdition = 'ced';
    case Commander2011 = 'cmd';
    case Commander2011LaunchParty = 'pcmd';
    case Commander2011Oversized = 'ocmd';
    case Commander2013 = 'c13';
    case Commander2013Oversized = 'o_c13';
    case Commander2014 = 'c14';
    case Commander2014Oversized = 'o_c14';
    case Commander2015 = 'c15';
    case Commander2015Oversized = 'o_c15';
    case Commander2016 = 'c16';
    case Commander2016Oversized = 'o_c16';
    case Commander2017 = 'c17';
    case Commander2017Oversized = 'o_c17';
    case Commander2018 = 'c18';
    case Commander2018Oversized = 'o_c18';
    case Commander2019 = 'c19';
    case Commander2019Oversized = 'o_c19';
    case Commander2020 = 'c20';
    case Commander2020Oversized = 'o_c20';
    case Commander2021 = 'c21';
    case Commander2021DisplayCommanders = 'o_c21';
    case CommanderAnthology = 'cma';
    case CommanderAnthologyVolumeII = 'c_m2';
    case CommanderCollectionBlack = 'c_c2';
    case CommanderCollectionGreen = 'c_c1';
    case CommanderLegends = 'cmr';
    case CommanderLegendsBattleForBaldurSGate = 'clb';
    case CommanderLegendsBattleForBaldurSGateMinigames = 'mclb';
    case CommanderMasters = 'cmm';
    case CommanderSArsenal = 'c_m1';
    case CommanderSArsenalOversized = 'ocm1';
    case Conflux = 'con';
    case ConfluxPromos = 'pcon';
    case Conspiracy = 'cns';
    case ConspiracyPromos = 'pcns';
    case ConspiracyTakeTheCrown = 'c_n2';
    case CoreSet2019 = 'm19';
    case CoreSet2019Promos = 'p_m19';
    case CoreSet2020 = 'm20';
    case CoreSet2020Promos = 'p_m20';
    case CoreSet2021 = 'm21';
    case CoreSet2021Promos = 'p_m21';
    case CrimsonVowArtSeries = 'avow';
    case CrimsonVowCommander = 'voc';
    case CrimsonVowCommanderDisplayCommanders = 'ovoc';
    case DCILegendMembership = 'plgm';
    case DCIPromos = 'pdci';
    case DarkAscension = 'dka';
    case DarkAscensionPromos = 'pdka';
    case Darksteel = 'dst';
    case DarksteelPromos = 'pdst';
    case Deckmasters = 'dkm';
    case DefeatAGod = 'tdag';
    case Dissension = 'dis';
    case DissensionPromos = 'pdis';
    case Dominaria = 'dom';
    case DominariaPromos = 'pdom';
    case DominariaRemastered = 'dmr';
    case DominariaUnited = 'dmu';
    case DominariaUnitedArtSeries = 'admu';
    case DominariaUnitedCommander = 'dmc';
    case DominariaUnitedJapanesePromoTokens = 'wdmu';
    case DominariaUnitedMinigames = 'mdmu';
    case DominariaUnitedPromos = 'pdmu';
    case DoubleMasters = '2_xm';
    case DoubleMasters2022 = '2_x2';
    case DragonCon = 'pdrc';
    case DragonSMaze = 'dgm';
    case DragonSMazePromos = 'pdgm';
    case DragonsOfTarkir = 'dtk';
    case DragonsOfTarkirPromos = 'pdtk';
    case DuelDecksAjaniVsNicolBolas = 'ddh';
    case DuelDecksAnthologyDivineVsDemonic = 'dvd';
    case DuelDecksAnthologyElvesVsGoblins = 'evg';
    case DuelDecksAnthologyGarrukVsLiliana = 'gvl';
    case DuelDecksAnthologyJaceVsChandra = 'jvc';
    case DuelDecksBlessedVsCursed = 'ddq';
    case DuelDecksDivineVsDemonic = 'ddc';
    case DuelDecksElspethVsKiora = 'ddo';
    case DuelDecksElspethVsTezzeret = 'ddf';
    case DuelDecksElvesVsGoblins = 'd_d1';
    case DuelDecksElvesVsInventors = 'ddu';
    case DuelDecksGarrukVsLiliana = 'ddd';
    case DuelDecksHeroesVsMonsters = 'ddl';
    case DuelDecksIzzetVsGolgari = 'ddj';
    case DuelDecksJaceVsChandra = 'd_d2';
    case DuelDecksJaceVsVraska = 'ddm';
    case DuelDecksKnightsVsDragons = 'ddg';
    case DuelDecksMerfolkVsGoblins = 'ddt';
    case DuelDecksMindVsMight = 'dds';
    case DuelDecksMirrodinPureVsNewPhyrexia = 't_d2';
    case DuelDecksNissaVsObNixilis = 'ddr';
    case DuelDecksPhyrexiaVsTheCoalition = 'dde';
    case DuelDecksSorinVsTibalt = 'ddk';
    case DuelDecksSpeedVsCunning = 'ddn';
    case DuelDecksVenserVsKoth = 'ddi';
    case DuelDecksZendikarVsEldrazi = 'ddp';
    case DuelsOfThePlaneswalkers = 'dpa';
    case DuelsOfThePlaneswalkers2009Promos = 'pdtp';
    case DuelsOfThePlaneswalkers2010Promos = 'pdp10';
    case DuelsOfThePlaneswalkers2012Promos = 'pdp12';
    case DuelsOfThePlaneswalkers2013Promos = 'pdp13';
    case DuelsOfThePlaneswalkers2014Promos = 'pdp14';
    case DuelsOfThePlaneswalkers2015Promos = 'pdp15';
    case EighthEdition = '8_ed';
    case EighthEditionPromos = 'p8_ed';
    case EldritchMoon = 'emn';
    case EldritchMoonPromos = 'pemn';
    case EternalMasters = 'ema';
    case EternalWeekend2022 = 'pewk';
    case EuropeanLandProgram = 'pelp';
    case Eventide = 'eve';
    case EventidePromos = 'peve';
    case Exodus = 'exo';
    case ExodusPromos = 'pexo';
    case ExplorerAnthology1 = 'e_a1';
    case ExplorerAnthology2 = 'e_a2';
    case ExplorersOfIxalan = 'e02';
    case FBBChronicles = 'bchr';
    case FaceTheHydra = 'tfth';
    case FallenEmpires = 'fem';
    case FateReforged = 'frf';
    case FateReforgedClashPack = 'c_p2';
    case FateReforgedPromos = 'pfrf';
    case FifteenthAnniversaryCards = 'p15_a';
    case FifthDawn = '5_dn';
    case FifthDawnPromos = 'p5_dn';
    case FifthEdition = '5_ed';
    case ForeignBlackBorder = 'fbb';
    case ForgottenRealmsCommander = 'afc';
    case ForgottenRealmsCommanderDisplayCommanders = 'oafc';
    case FourthEdition = '4_ed';
    case FourthEditionForeignBlackBorder = '4_bb';
    case FridayNightMagic2000 = 'fnm';
    case FridayNightMagic2001 = 'f01';
    case FridayNightMagic2002 = 'f02';
    case FridayNightMagic2003 = 'f03';
    case FridayNightMagic2004 = 'f04';
    case FridayNightMagic2005 = 'f05';
    case FridayNightMagic2006 = 'f06';
    case FridayNightMagic2007 = 'f07';
    case FridayNightMagic2008 = 'f08';
    case FridayNightMagic2009 = 'f09';
    case FridayNightMagic2010 = 'f10';
    case FridayNightMagic2011 = 'f11';
    case FridayNightMagic2012 = 'f12';
    case FridayNightMagic2013 = 'f13';
    case FridayNightMagic2014 = 'f14';
    case FridayNightMagic2015 = 'f15';
    case FridayNightMagic2016 = 'f16';
    case FridayNightMagic2017 = 'f17';
    case FridayNightMagic2018 = 'f18';
    case FromTheVaultAngels = 'v15';
    case FromTheVaultAnnihilation = 'v14';
    case FromTheVaultDragons = 'drb';
    case FromTheVaultExiled = 'v09';
    case FromTheVaultLegends = 'v11';
    case FromTheVaultLore = 'v16';
    case FromTheVaultRealms = 'v12';
    case FromTheVaultRelics = 'v10';
    case FromTheVaultTransform = 'v17';
    case FromTheVaultTwenty = 'v13';
    case FutureSight = 'fut';
    case FutureSightPromos = 'pfut';
    case GRNGuildKit = 'g_k1';
    case GRNRavnicaWeekend = 'prwk';
    case GameDayPromos = 'gdy';
    case GameNight = 'gnt';
    case GameNight2019 = 'g_n2';
    case GameNightFreeForAll = 'g_n3';
    case Gatecrash = 'gtc';
    case GatecrashPromos = 'pgtc';
    case Gateway2006 = 'pgtw';
    case Gateway2007 = 'p_g07';
    case Gateway2008 = 'p_g08';
    case GlobalSeriesJiangYangguMuYanling = 'g_s1';
    case GrandPrixPromos = 'pgpx';
    case Guildpact = 'gpt';
    case GuildpactPromos = 'pgpt';
    case GuildsOfRavnica = 'grn';
    case GuildsOfRavnicaPromos = 'pgrn';
    case Guru = 'pgru';
    case HachetteUK = 'phuk';
    case HappyHolidays = 'hho';
    case HarperPrismBookPromos = 'phpr';
    case HasCon2017 = 'h17';
    case HeadsIWinTailsYouLose = 'phed';
    case HistoricAnthology1 = 'h_a1';
    case HistoricAnthology2 = 'h_a2';
    case HistoricAnthology3 = 'h_a3';
    case HistoricAnthology4 = 'h_a4';
    case HistoricAnthology5 = 'h_a5';
    case HistoricAnthology6 = 'h_a6';
    case HobbyJapanPromos = 'phj';
    case Homelands = 'hml';
    case HourOfDevastation = 'hou';
    case HourOfDevastationPromos = 'phou';
    case IDWComics2013 = 'p_i13';
    case IDWComics2014 = 'p_i14';
    case IDWComicsInserts = 'pidw';
    case IceAge = 'ice';
    case IconicMasters = 'ima';
    case IkoriaLairOfBehemoths = 'iko';
    case IkoriaLairOfBehemothsPromos = 'piko';
    case Innistrad = 'isd';
    case InnistradCrimsonVow = 'vow';
    case InnistradCrimsonVowMinigames = 'mvow';
    case InnistradCrimsonVowPromos = 'pvow';
    case InnistradCrimsonVowSubstituteCards = 'svow';
    case InnistradDoubleFeature = 'dbl';
    case InnistradMidnightHunt = 'mid';
    case InnistradMidnightHuntMinigames = 'mmid';
    case InnistradMidnightHuntPromos = 'pmid';
    case InnistradMidnightHuntSubstituteCards = 'smid';
    case InnistradPromos = 'pisd';
    case IntlCollectorsEdition = 'cei';
    case IntroductoryTwoPlayerSet = 'itp';
    case Invasion = 'inv';
    case InvasionPromos = 'pinv';
    case Ixalan = 'xln';
    case IxalanPromos = 'pxln';
    case JapanJuniorTournament = 'pjjt';
    case JourneyIntoNyx = 'jou';
    case JourneyIntoNyxHeroSPath = 'thp3';
    case JourneyIntoNyxPromos = 'pjou';
    case JudgeGiftCards1998 = 'jgp';
    case JudgeGiftCards1999 = 'g99';
    case JudgeGiftCards2000 = 'g00';
    case JudgeGiftCards2001 = 'g01';
    case JudgeGiftCards2002 = 'g02';
    case JudgeGiftCards2003 = 'g03';
    case JudgeGiftCards2004 = 'g04';
    case JudgeGiftCards2005 = 'g05';
    case JudgeGiftCards2006 = 'g06';
    case JudgeGiftCards2007 = 'g07';
    case JudgeGiftCards2008 = 'g08';
    case JudgeGiftCards2009 = 'g09';
    case JudgeGiftCards2010 = 'g10';
    case JudgeGiftCards2011 = 'g11';
    case JudgeGiftCards2012 = 'j12';
    case JudgeGiftCards2013 = 'j13';
    case JudgeGiftCards2014 = 'j14';
    case JudgeGiftCards2015 = 'j15';
    case JudgeGiftCards2016 = 'j16';
    case JudgeGiftCards2017 = 'j17';
    case JudgeGiftCards2018 = 'j18';
    case JudgeGiftCards2019 = 'j19';
    case JudgeGiftCards2020 = 'j20';
    case JudgeGiftCards2021 = 'p_j21';
    case JudgeGiftCards2022 = 'p22';
    case JudgeGiftCards2023 = 'p23';
    case Judgment = 'jud';
    case JudgmentPromos = 'pjud';
    case Jumpstart = 'jmp';
    case Jumpstart2022 = 'j22';
    case Jumpstart2022FrontCards = 'f_j22';
    case JumpstartArenaExclusives = 'ajmp';
    case JumpstartFrontCards = 'fjmp';
    case JumpstartHistoricHorizons = 'j21';
    case JuniorAPACSeries = 'pjas';
    case JuniorSeriesEurope = 'pjse';
    case JuniorSuperSeries = 'psus';
    case Kaladesh = 'kld';
    case KaladeshInventions = 'mps';
    case KaladeshPromos = 'pkld';
    case KaladeshRemastered = 'klr';
    case Kaldheim = 'khm';
    case KaldheimArtSeries = 'akhm';
    case KaldheimCommander = 'khc';
    case KaldheimMinigames = 'mkhm';
    case KaldheimPromos = 'pkhm';
    case KaldheimSubstituteCards = 'skhm';
    case KamigawaNeonDynasty = 'neo';
    case KamigawaNeonDynastyMinigames = 'mneo';
    case KamigawaNeonDynastyPromos = 'pneo';
    case KamigawaNeonDynastySubstituteCards = 'sneo';
    case KhansOfTarkir = 'ktk';
    case KhansOfTarkirPromos = 'pktk';
    case LeagueTokens2012 = 'l12';
    case LeagueTokens2013 = 'l13';
    case LeagueTokens2014 = 'l14';
    case LeagueTokens2015 = 'l15';
    case LeagueTokens2016 = 'l16';
    case LeagueTokens2017 = 'l17';
    case LegacyChampionship = 'olgc';
    case LegendaryCubePrizePack = 'p_z1';
    case Legends = 'leg';
    case Legions = 'lgn';
    case LegionsPromos = 'plgn';
    case LimitedEditionAlpha = 'lea';
    case LimitedEditionBeta = 'leb';
    case LordOfTheRingsTalesOfMiddleEarth = 'ltr';
    case Lorwyn = 'lrw';
    case LorwynPromos = 'plrw';
    case LoveYourLGS2020 = 'plg20';
    case LoveYourLGS2021 = 'plg21';
    case LoveYourLGS2022 = 'plg22';
    case LunarNewYear2018 = 'plny';
    case M15PrereleaseChallenge = 'ppc1';
    case M19GiftPack = 'g18';
    case M19StandardShowdown = 'pss3';
    case M20PromoPacks = 'ppp1';
    case MTGArenaPromos = 'pana';
    case Magic2010 = 'm10';
    case Magic2010Promos = 'p_m10';
    case Magic2011 = 'm11';
    case Magic2011Promos = 'p_m11';
    case Magic2012 = 'm12';
    case Magic2012Promos = 'p_m12';
    case Magic2013 = 'm13';
    case Magic2013Promos = 'p_m13';
    case Magic2014 = 'm14';
    case Magic2014Promos = 'p_m14';
    case Magic2015 = 'm15';
    case Magic2015ClashPack = 'c_p1';
    case Magic2015Promos = 'p_m15';
    case MagicFest2019 = 'p_f19';
    case MagicFest2020 = 'p_f20';
    case MagicFest2021 = 'p_f21';
    case MagicOnlineAvatars = 'pmoa';
    case MagicOnlinePromos = 'prm';
    case MagicOnlineThemeDecks = 't_d0';
    case MagicOrigins = 'ori';
    case MagicOriginsClashPack = 'c_p3';
    case MagicOriginsPromos = 'pori';
    case MagicPlayerRewards2001 = 'mpr';
    case MagicPlayerRewards2002 = 'p_r2';
    case MagicPlayerRewards2003 = 'p03';
    case MagicPlayerRewards2004 = 'p04';
    case MagicPlayerRewards2005 = 'p05';
    case MagicPlayerRewards2006 = 'p06';
    case MagicPlayerRewards2007 = 'p07';
    case MagicPlayerRewards2008 = 'p08';
    case MagicPlayerRewards2009 = 'p09';
    case MagicPlayerRewards2010 = 'p10';
    case MagicPlayerRewards2011 = 'p11';
    case MagicPremiereShop2005 = 'pmps';
    case MagicPremiereShop2006 = 'pmps06';
    case MagicPremiereShop2007 = 'pmps07';
    case MagicPremiereShop2008 = 'pmps08';
    case MagicPremiereShop2009 = 'pmps09';
    case MagicPremiereShop2010 = 'pmps10';
    case MagicPremiereShop2011 = 'pmps11';
    case MarchOfTheMachine = 'mom';
    case MarchOfTheMachineCommander = 'moc';
    case MarchOfTheMachineTheAftermath = 'mat';
    case Masters25 = 'a25';
    case MastersEdition = 'm_e1';
    case MastersEditionII = 'm_e2';
    case MastersEditionIII = 'm_e3';
    case MastersEditionIV = 'm_e4';
    case MediaInserts = 'pmei';
    case MercadianMasques = 'mmq';
    case MercadianMasquesPromos = 'pmmq';
    case MicroProsePromos = 'pmic';
    case MidnightHuntArtSeries = 'amid';
    case MidnightHuntCommander = 'mic';
    case MidnightHuntCommanderDisplayCommanders = 'omic';
    case Mirage = 'mir';
    case Mirrodin = 'mrd';
    case MirrodinBesieged = 'mbs';
    case MirrodinBesiegedPromos = 'pmbs';
    case MirrodinPromos = 'pmrd';
    case MiscellaneousBookPromos = 'pbook';
    case ModernEventDeck2014 = 'm_d1';
    case ModernHorizons = 'm_h1';
    case ModernHorizons1Timeshifts = 'h1_r';
    case ModernHorizons2 = 'm_h2';
    case ModernHorizons2ArtSeries = 'amh2';
    case ModernHorizons2Minigames = 'mmh2';
    case ModernHorizons2Promos = 'pmh2';
    case ModernHorizonsArtSeries = 'amh1';
    case ModernHorizonsPromos = 'pmh1';
    case ModernMasters = 'mma';
    case ModernMasters2015 = 'm_m2';
    case ModernMasters2017 = 'm_m3';
    case Morningtide = 'mor';
    case MorningtidePromos = 'pmor';
    case MultiverseGiftBox = 'mgb';
    case MultiverseLegends = 'mul';
    case MysteryBooster = 'm_b1';
    case MysteryBoosterPlaytestCards2019 = 'cmb1';
    case MysteryBoosterPlaytestCards2021 = 'cmb2';
    case MysteryBoosterRetailEditionFoils = 'fmb1';
    case MythicEdition = 'med';
    case NationalsPromos = 'pnat';
    case Nemesis = 'nem';
    case NemesisPromos = 'pnem';
    case NeonDynastyArtSeries = 'aneo';
    case NeonDynastyCommander = 'nec';
    case NewCapennaArtSeries = 'asnc';
    case NewCapennaCommander = 'ncc';
    case NewCapennaCommanderPromos = 'pncc';
    case NewPhyrexia = 'nph';
    case NewPhyrexiaPromos = 'pnph';
    case NinthEdition = '9_ed';
    case NinthEditionPromos = 'p9_ed';
    case OathOfTheGatewatch = 'ogw';
    case OathOfTheGatewatchPromos = 'pogw';
    case Odyssey = 'ody';
    case OdysseyPromos = 'pody';
    case Onslaught = 'ons';
    case OnslaughtPromos = 'pons';
    case OpenTheHelvault = 'phel';
    case Oversized90SPromos = 'o90_p';
    case OversizedLeaguePrizes = 'olep';
    case PhyrexiaAllWillBeOne = 'one';
    case PhyrexiaAllWillBeOneArtSeries = 'aone';
    case PhyrexiaAllWillBeOneCommander = 'onc';
    case PhyrexiaAllWillBeOneJapanesePromoTokens = 'wone';
    case PhyrexiaAllWillBeOneJumpstartFrontCards = 'fone';
    case PhyrexiaAllWillBeOneMinigames = 'mone';
    case PhyrexiaAllWillBeOnePromos = 'pone';
    case PioneerChallengerDecks2021 = 'q06';
    case PioneerChallengerDecks2022 = 'q08';
    case PlanarChaos = 'plc';
    case PlanarChaosPromos = 'pplc';
    case Planechase = 'hop';
    case Planechase2012 = 'p_c2';
    case Planechase2012Planes = 'opc2';
    case PlanechaseAnthology = 'pca';
    case PlanechaseAnthologyPlanes = 'opca';
    case PlanechasePlanes = 'ohop';
    case PlanechasePromos = 'phop';
    case Planeshift = 'pls';
    case PlaneshiftPromos = 'ppls';
    case PlaneswalkerChampionshipPromos = 'pwcs';
    case PoniesTheGalloping = 'ptg';
    case Portal = 'por';
    case PortalSecondAge = 'p02';
    case PortalThreeKingdoms = 'ptk';
    case PortalThreeKingdomsPromos = 'pptk';
    case PremiumDeckSeriesFireAndLightning = 'p_d2';
    case PremiumDeckSeriesGraveborn = 'p_d3';
    case PremiumDeckSeriesSlivers = 'h09';
    case ProTourCollectorSet = 'ptc';
    case ProTourPromos = 'ppro';
    case Prophecy = 'pcy';
    case ProphecyPromos = 'ppcy';
    case RNAGuildKit = 'g_k2';
    case RNARavnicaWeekend = 'prw2';
    case RavnicaAllegiance = 'rna';
    case RavnicaAllegiancePromos = 'prna';
    case RavnicaCityOfGuilds = 'rav';
    case RavnicaCityOfGuildsPromos = 'prav';
    case RedemptionProgram = 'pred';
    case RegionalChampionshipQualifiers2022 = 'prcq';
    case RegionalChampionshipQualifiers2023 = 'p_r23';
    case Renaissance = 'ren';
    case ResalePromos = 'pres';
    case ReturnToRavnica = 'rtr';
    case ReturnToRavnicaPromos = 'prtr';
    case RevisedEdition = '3_ed';
    case Rinascimento = 'rin';
    case RiseOfTheEldrazi = 'roe';
    case RiseOfTheEldraziPromos = 'proe';
    case RivalsOfIxalan = 'rix';
    case RivalsOfIxalanPromos = 'prix';
    case RivalsQuickStartSet = 'rqs';
    case Salvat2005 = 'psal';
    case Salvat2011 = 'p_s11';
    case SanDiegoComicCon2013 = 'psdc';
    case SanDiegoComicCon2014 = 'p_s14';
    case SanDiegoComicCon2015 = 'p_s15';
    case SanDiegoComicCon2016 = 'p_s16';
    case SanDiegoComicCon2017 = 'p_s17';
    case SanDiegoComicCon2018 = 'p_s18';
    case SanDiegoComicCon2019 = 'p_s19';
    case SaviorsOfKamigawa = 'sok';
    case SaviorsOfKamigawaPromos = 'psok';
    case ScarsOfMirrodin = 'som';
    case ScarsOfMirrodinPromos = 'psom';
    case Scourge = 'scg';
    case ScourgePromos = 'pscg';
    case SecretLair30thAnniversaryCountdownKit = 'slc';
    case SecretLairDrop = 'sld';
    case SecretLairShowdown = 'slp';
    case SecretLairUltimateEdition = 'slu';
    case SegaDreamcastCards = 'psdg';
    case SeventhEdition = '7_ed';
    case Shadowmoor = 'shm';
    case ShadowmoorPromos = 'pshm';
    case ShadowsOverInnistrad = 'soi';
    case ShadowsOverInnistradPromos = 'psoi';
    case ShadowsOverInnistradRemastered = 'sir';
    case ShardsOfAlara = 'ala';
    case ShardsOfAlaraPromos = 'pala';
    case SignatureSpellbookChandra = 's_s3';
    case SignatureSpellbookGideon = 's_s2';
    case SignatureSpellbookJace = 's_s1';
    case Starter1999 = 's99';
    case Starter2000 = 's00';
    case StarterCommanderDecks = 'scd';
    case StoreChampionships = 'sch';
    case StreetsOfNewCapenna = 'snc';
    case StreetsOfNewCapennaMinigames = 'msnc';
    case StreetsOfNewCapennaPromos = 'psnc';
    case StreetsOfNewCapennaSoutheastAsiaTokens = 'ptsnc';
    case StrixhavenArtSeries = 'astx';
    case StrixhavenMysticalArchive = 'sta';
    case StrixhavenSchoolOfMages = 'stx';
    case StrixhavenSchoolOfMagesMinigames = 'mstx';
    case StrixhavenSchoolOfMagesPromos = 'pstx';
    case StrixhavenSchoolOfMagesSubstituteCards = 'sstx';
    case Stronghold = 'sth';
    case StrongholdPromos = 'psth';
    case SummerMagicEdgar = 'sum';
    case SummerOfMagic = 'psum';
    case SummerVacationPromos2022 = 'psvc';
    case TarkirDragonfury = 'ptkdf';
    case Tempest = 'tmp';
    case TempestPromos = 'ptmp';
    case TempestRemastered = 'tpr';
    case TenthEdition = '10_e';
    case TenthEditionPromos = 'p10_e';
    case TheBrothersWar = 'bro';
    case TheBrothersWarArtSeries = 'abro';
    case TheBrothersWarCommander = 'brc';
    case TheBrothersWarMinigames = 'mbro';
    case TheBrothersWarPromos = 'pbro';
    case TheBrothersWarRetroArtifacts = 'brr';
    case TheDark = 'drk';
    case TheList = 'plist';
    case TheListUnfinityFoilEdition = 'uplist';
    case Theros = 'ths';
    case TherosBeyondDeath = 'thb';
    case TherosBeyondDeathPromos = 'pthb';
    case TherosHeroSPath = 'thp1';
    case TherosPromos = 'pths';
    case ThirtythAnniversaryEdition = '30_a';
    case ThirtythAnniversaryHistoryPromos = 'p30_h';
    case ThirtythAnniversaryPlayPromos = 'p30_a';
    case ThroneOfEldraine = 'eld';
    case ThroneOfEldrainePromos = 'peld';
    case TimeSpiral = 'tsp';
    case TimeSpiralPromos = 'ptsp';
    case TimeSpiralRemastered = 'tsr';
    case TimeSpiralTimeshifted = 'tsb';
    case Torment = 'tor';
    case TormentPromos = 'ptor';
    case Transformers = 'bot';
    case TreasureChest = 'p_z2';
    case TwoHeadedGiantTournament = 'p2_hg';
    case TwoThousandEighteenHeroesOfTheRealm = 'p_h18';
    case TwoThousandNineteenHeroesOfTheRealm = 'p_h19';
    case TwoThousandSeventeenGiftPack = 'g17';
    case TwoThousandSeventeenHeroesOfTheRealm = 'p_h17';
    case TwoThousandSixteenHeroesOfTheRealm = 'phtr';
    case TwoThousandTwentyHeroesOfTheRealm = 'p_h20';
    case TwoThousandTwentyOneHeroesOfTheRealm = 'p_h21';
    case URLConventionPromos = 'purl';
    case UginSFate = 'ugin';
    case UltimateBoxTopper = 'puma';
    case UltimateMasters = 'uma';
    case Unfinity = 'unf';
    case UnfinityStickerSheets = 'sunf';
    case Unglued = 'ugl';
    case Unhinged = 'unh';
    case UnhingedPromos = 'punh';
    case UniversesWithin = 'slx';
    case UnlimitedEdition = '2_ed';
    case Unsanctioned = 'und';
    case Unstable = 'ust';
    case UnstablePromos = 'pust';
    case UrzaSDestiny = 'uds';
    case UrzaSDestinyPromos = 'puds';
    case UrzaSLegacy = 'ulg';
    case UrzaSLegacyPromos = 'pulg';
    case UrzaSSaga = 'usg';
    case UrzaSSagaPromos = 'pusg';
    case VanguardSeries = 'pvan';
    case VintageChampionship = 'ovnt';
    case VintageMasters = 'vma';
    case Visions = 'vis';
    case WarOfTheSpark = 'war';
    case WarOfTheSparkPromos = 'pwar';
    case Warhammer40000Commander = '40_k';
    case Weatherlight = 'wth';
    case WelcomeDeck2016 = 'w16';
    case WelcomeDeck2017 = 'w17';
    case WizardsOfTheCoastOnlineStore = 'pwos';
    case WizardsPlayNetwork2008 = 'pwpn';
    case WizardsPlayNetwork2009 = 'p_w09';
    case WizardsPlayNetwork2010 = 'p_w10';
    case WizardsPlayNetwork2011 = 'p_w11';
    case WizardsPlayNetwork2012 = 'p_w12';
    case WizardsPlayNetwork2021 = 'p_w21';
    case WizardsPlayNetwork2022 = 'p_w22';
    case WizardsPlayNetwork2023 = 'p_w23';
    case WorldChampionshipDecks1997 = 'w_c97';
    case WorldChampionshipDecks1998 = 'w_c98';
    case WorldChampionshipDecks1999 = 'w_c99';
    case WorldChampionshipDecks2000 = 'w_c00';
    case WorldChampionshipDecks2001 = 'w_c01';
    case WorldChampionshipDecks2002 = 'w_c02';
    case WorldChampionshipDecks2003 = 'w_c03';
    case WorldChampionshipDecks2004 = 'w_c04';
    case WorldChampionshipPromos = 'pwor';
    case WorldMagicCupQualifiers = 'wmc';
    case Worldwake = 'wwk';
    case WorldwakePromos = 'pwwk';
    case XLNStandardShowdown = 'pss2';
    case XLNTreasureChest = 'pxtc';
    case YearOfTheOx2021 = 'p_l21';
    case YearOfTheRabbit2023 = 'p_l23';
    case YearOfTheTiger2022 = 'p_l22';
    case Zendikar = 'zen';
    case ZendikarExpeditions = 'exp';
    case ZendikarPromos = 'pzen';
    case ZendikarRising = 'znr';
    case ZendikarRisingArtSeries = 'aznr';
    case ZendikarRisingCommander = 'znc';
    case ZendikarRisingExpeditions = 'zne';
    case ZendikarRisingMinigames = 'mznr';
    case ZendikarRisingPromos = 'pznr';
    case ZendikarRisingSubstituteCards = 'sznr';

    public static function tryFromLabel(string $label): self
    {
        return SetCode::tryFrom(u($label)->snake()->toString());
    }

    public function label(): string
    {
        return SetCode::getLabel($this);
    }

    public static function getLabel(self $value): string
    {
        return match ($value) {
            SetCode::AdventuresInTheForgottenRealms => "AFR",
            SetCode::AdventuresInTheForgottenRealmsArtSeries => "AAFR",
            SetCode::AdventuresInTheForgottenRealmsMinigames => "MAFR",
            SetCode::AdventuresInTheForgottenRealmsPromos => "PAFR",
            SetCode::AetherRevolt => "AER",
            SetCode::AetherRevoltPromos => "PAER",
            SetCode::AlaraReborn => "ARB",
            SetCode::AlaraRebornPromos => "PARB",
            SetCode::AlchemyDominaria => "YDMU",
            SetCode::AlchemyHorizonsBaldurSGate => "HBG",
            SetCode::AlchemyInnistrad => "YMID",
            SetCode::AlchemyKamigawa => "YNEO",
            SetCode::AlchemyNewCapenna => "YSNC",
            SetCode::AlchemyPhyrexia => "YONE",
            SetCode::AlchemyTheBrothersWar => "YBRO",
            SetCode::Alliances => "ALL",
            SetCode::Amonkhet => "AKH",
            SetCode::AmonkhetInvocations => "MP2",
            SetCode::AmonkhetPromos => "PAKH",
            SetCode::AmonkhetRemastered => "AKR",
            SetCode::Anthologies => "ATH",
            SetCode::Antiquities => "ATQ",
            SetCode::Apocalypse => "APC",
            SetCode::ApocalypsePromos => "PAPC",
            SetCode::ArabianNights => "ARN",
            SetCode::Archenemy => "ARC",
            SetCode::ArchenemyNicolBolas => "E01",
            SetCode::ArchenemyNicolBolasSchemes => "OE01",
            SetCode::ArchenemyPromos => "PARC",
            SetCode::ArchenemySchemes => "OARC",
            SetCode::ArenaBeginnerSet => "ANB",
            SetCode::ArenaLeague1996 => "PARL",
            SetCode::ArenaLeague1999 => "PAL99",
            SetCode::ArenaLeague2000 => "PAL00",
            SetCode::ArenaLeague2001 => "PAL01",
            SetCode::ArenaLeague2002 => "PAL02",
            SetCode::ArenaLeague2003 => "PAL03",
            SetCode::ArenaLeague2004 => "PAL04",
            SetCode::ArenaLeague2005 => "PAL05",
            SetCode::ArenaLeague2006 => "PAL06",
            SetCode::ArenaNewPlayerExperience => "ANA",
            SetCode::ArenaNewPlayerExperienceCards => "OANA",
            SetCode::ArenaNewPlayerExperienceExtras => "XANA",
            SetCode::AsiaPacificLandProgram => "PALP",
            SetCode::AstralCards => "PAST",
            SetCode::AvacynRestored => "AVR",
            SetCode::AvacynRestoredPromos => "PAVR",
            SetCode::BFZStandardSeries => "PSS1",
            SetCode::BattleForBaldurSGateArtSeries => "ACLB",
            SetCode::BattleForBaldurSGatePromos => "PCLB",
            SetCode::BattleForZendikar => "BFZ",
            SetCode::BattleForZendikarPromos => "PBFZ",
            SetCode::BattleRoyaleBoxSet => "BRB",
            SetCode::BattleTheHorde => "TBTH",
            SetCode::Battlebond => "BBD",
            SetCode::BattlebondPromos => "PBBD",
            SetCode::BeatdownBoxSet => "BTD",
            SetCode::BetrayersOfKamigawa => "BOK",
            SetCode::BetrayersOfKamigawaPromos => "PBOK",
            SetCode::BornOfTheGods => "BNG",
            SetCode::BornOfTheGodsHeroSPath => "THP2",
            SetCode::BornOfTheGodsPromos => "PBNG",
            SetCode::CelebrationCards => "PCEL",
            SetCode::ChallengerDecks2022 => "Q07",
            SetCode::ChampionsOfKamigawa => "CHK",
            SetCode::ChampionsOfKamigawaPromos => "PCHK",
            SetCode::ChampsAndStates => "PCMP",
            SetCode::Chronicles => "CHR",
            SetCode::ClassicSixthEdition => "6ED",
            SetCode::Coldsnap => "CSP",
            SetCode::ColdsnapPromos => "PCSP",
            SetCode::ColdsnapThemeDecks => "CST",
            SetCode::CollectorsEdition => "CED",
            SetCode::Commander2011 => "CMD",
            SetCode::Commander2011LaunchParty => "PCMD",
            SetCode::Commander2011Oversized => "OCMD",
            SetCode::Commander2013 => "C13",
            SetCode::Commander2013Oversized => "OC13",
            SetCode::Commander2014 => "C14",
            SetCode::Commander2014Oversized => "OC14",
            SetCode::Commander2015 => "C15",
            SetCode::Commander2015Oversized => "OC15",
            SetCode::Commander2016 => "C16",
            SetCode::Commander2016Oversized => "OC16",
            SetCode::Commander2017 => "C17",
            SetCode::Commander2017Oversized => "OC17",
            SetCode::Commander2018 => "C18",
            SetCode::Commander2018Oversized => "OC18",
            SetCode::Commander2019 => "C19",
            SetCode::Commander2019Oversized => "OC19",
            SetCode::Commander2020 => "C20",
            SetCode::Commander2020Oversized => "OC20",
            SetCode::Commander2021 => "C21",
            SetCode::Commander2021DisplayCommanders => "OC21",
            SetCode::CommanderAnthology => "CMA",
            SetCode::CommanderAnthologyVolumeII => "CM2",
            SetCode::CommanderCollectionBlack => "CC2",
            SetCode::CommanderCollectionGreen => "CC1",
            SetCode::CommanderLegends => "CMR",
            SetCode::CommanderLegendsBattleForBaldurSGate => "CLB",
            SetCode::CommanderLegendsBattleForBaldurSGateMinigames => "MCLB",
            SetCode::CommanderMasters => "CMM",
            SetCode::CommanderSArsenal => "CM1",
            SetCode::CommanderSArsenalOversized => "OCM1",
            SetCode::Conflux => "CON",
            SetCode::ConfluxPromos => "PCON",
            SetCode::Conspiracy => "CNS",
            SetCode::ConspiracyPromos => "PCNS",
            SetCode::ConspiracyTakeTheCrown => "CN2",
            SetCode::CoreSet2019 => "M19",
            SetCode::CoreSet2019Promos => "PM19",
            SetCode::CoreSet2020 => "M20",
            SetCode::CoreSet2020Promos => "PM20",
            SetCode::CoreSet2021 => "M21",
            SetCode::CoreSet2021Promos => "PM21",
            SetCode::CrimsonVowArtSeries => "AVOW",
            SetCode::CrimsonVowCommander => "VOC",
            SetCode::CrimsonVowCommanderDisplayCommanders => "OVOC",
            SetCode::DCILegendMembership => "PLGM",
            SetCode::DCIPromos => "PDCI",
            SetCode::DarkAscension => "DKA",
            SetCode::DarkAscensionPromos => "PDKA",
            SetCode::Darksteel => "DST",
            SetCode::DarksteelPromos => "PDST",
            SetCode::Deckmasters => "DKM",
            SetCode::DefeatAGod => "TDAG",
            SetCode::Dissension => "DIS",
            SetCode::DissensionPromos => "PDIS",
            SetCode::Dominaria => "DOM",
            SetCode::DominariaPromos => "PDOM",
            SetCode::DominariaRemastered => "DMR",
            SetCode::DominariaUnited => "DMU",
            SetCode::DominariaUnitedArtSeries => "ADMU",
            SetCode::DominariaUnitedCommander => "DMC",
            SetCode::DominariaUnitedJapanesePromoTokens => "WDMU",
            SetCode::DominariaUnitedMinigames => "MDMU",
            SetCode::DominariaUnitedPromos => "PDMU",
            SetCode::DoubleMasters => "2XM",
            SetCode::DoubleMasters2022 => "2X2",
            SetCode::DragonCon => "PDRC",
            SetCode::DragonSMaze => "DGM",
            SetCode::DragonSMazePromos => "PDGM",
            SetCode::DragonsOfTarkir => "DTK",
            SetCode::DragonsOfTarkirPromos => "PDTK",
            SetCode::DuelDecksAjaniVsNicolBolas => "DDH",
            SetCode::DuelDecksAnthologyDivineVsDemonic => "DVD",
            SetCode::DuelDecksAnthologyElvesVsGoblins => "EVG",
            SetCode::DuelDecksAnthologyGarrukVsLiliana => "GVL",
            SetCode::DuelDecksAnthologyJaceVsChandra => "JVC",
            SetCode::DuelDecksBlessedVsCursed => "DDQ",
            SetCode::DuelDecksDivineVsDemonic => "DDC",
            SetCode::DuelDecksElspethVsKiora => "DDO",
            SetCode::DuelDecksElspethVsTezzeret => "DDF",
            SetCode::DuelDecksElvesVsGoblins => "DD1",
            SetCode::DuelDecksElvesVsInventors => "DDU",
            SetCode::DuelDecksGarrukVsLiliana => "DDD",
            SetCode::DuelDecksHeroesVsMonsters => "DDL",
            SetCode::DuelDecksIzzetVsGolgari => "DDJ",
            SetCode::DuelDecksJaceVsChandra => "DD2",
            SetCode::DuelDecksJaceVsVraska => "DDM",
            SetCode::DuelDecksKnightsVsDragons => "DDG",
            SetCode::DuelDecksMerfolkVsGoblins => "DDT",
            SetCode::DuelDecksMindVsMight => "DDS",
            SetCode::DuelDecksMirrodinPureVsNewPhyrexia => "TD2",
            SetCode::DuelDecksNissaVsObNixilis => "DDR",
            SetCode::DuelDecksPhyrexiaVsTheCoalition => "DDE",
            SetCode::DuelDecksSorinVsTibalt => "DDK",
            SetCode::DuelDecksSpeedVsCunning => "DDN",
            SetCode::DuelDecksVenserVsKoth => "DDI",
            SetCode::DuelDecksZendikarVsEldrazi => "DDP",
            SetCode::DuelsOfThePlaneswalkers => "DPA",
            SetCode::DuelsOfThePlaneswalkers2009Promos => "PDTP",
            SetCode::DuelsOfThePlaneswalkers2010Promos => "PDP10",
            SetCode::DuelsOfThePlaneswalkers2012Promos => "PDP12",
            SetCode::DuelsOfThePlaneswalkers2013Promos => "PDP13",
            SetCode::DuelsOfThePlaneswalkers2014Promos => "PDP14",
            SetCode::DuelsOfThePlaneswalkers2015Promos => "PDP15",
            SetCode::EighthEdition => "8ED",
            SetCode::EighthEditionPromos => "P8ED",
            SetCode::EldritchMoon => "EMN",
            SetCode::EldritchMoonPromos => "PEMN",
            SetCode::EternalMasters => "EMA",
            SetCode::EternalWeekend2022 => "PEWK",
            SetCode::EuropeanLandProgram => "PELP",
            SetCode::Eventide => "EVE",
            SetCode::EventidePromos => "PEVE",
            SetCode::Exodus => "EXO",
            SetCode::ExodusPromos => "PEXO",
            SetCode::ExplorerAnthology1 => "EA1",
            SetCode::ExplorerAnthology2 => "EA2",
            SetCode::ExplorersOfIxalan => "E02",
            SetCode::FBBChronicles => "BCHR",
            SetCode::FaceTheHydra => "TFTH",
            SetCode::FallenEmpires => "FEM",
            SetCode::FateReforged => "FRF",
            SetCode::FateReforgedClashPack => "CP2",
            SetCode::FateReforgedPromos => "PFRF",
            SetCode::FifteenthAnniversaryCards => "P15A",
            SetCode::FifthDawn => "5DN",
            SetCode::FifthDawnPromos => "P5DN",
            SetCode::FifthEdition => "5ED",
            SetCode::ForeignBlackBorder => "FBB",
            SetCode::ForgottenRealmsCommander => "AFC",
            SetCode::ForgottenRealmsCommanderDisplayCommanders => "OAFC",
            SetCode::FourthEdition => "4ED",
            SetCode::FourthEditionForeignBlackBorder => "4BB",
            SetCode::FridayNightMagic2000 => "FNM",
            SetCode::FridayNightMagic2001 => "F01",
            SetCode::FridayNightMagic2002 => "F02",
            SetCode::FridayNightMagic2003 => "F03",
            SetCode::FridayNightMagic2004 => "F04",
            SetCode::FridayNightMagic2005 => "F05",
            SetCode::FridayNightMagic2006 => "F06",
            SetCode::FridayNightMagic2007 => "F07",
            SetCode::FridayNightMagic2008 => "F08",
            SetCode::FridayNightMagic2009 => "F09",
            SetCode::FridayNightMagic2010 => "F10",
            SetCode::FridayNightMagic2011 => "F11",
            SetCode::FridayNightMagic2012 => "F12",
            SetCode::FridayNightMagic2013 => "F13",
            SetCode::FridayNightMagic2014 => "F14",
            SetCode::FridayNightMagic2015 => "F15",
            SetCode::FridayNightMagic2016 => "F16",
            SetCode::FridayNightMagic2017 => "F17",
            SetCode::FridayNightMagic2018 => "F18",
            SetCode::FromTheVaultAngels => "V15",
            SetCode::FromTheVaultAnnihilation => "V14",
            SetCode::FromTheVaultDragons => "DRB",
            SetCode::FromTheVaultExiled => "V09",
            SetCode::FromTheVaultLegends => "V11",
            SetCode::FromTheVaultLore => "V16",
            SetCode::FromTheVaultRealms => "V12",
            SetCode::FromTheVaultRelics => "V10",
            SetCode::FromTheVaultTransform => "V17",
            SetCode::FromTheVaultTwenty => "V13",
            SetCode::FutureSight => "FUT",
            SetCode::FutureSightPromos => "PFUT",
            SetCode::GRNGuildKit => "GK1",
            SetCode::GRNRavnicaWeekend => "PRWK",
            SetCode::GameDayPromos => "GDY",
            SetCode::GameNight => "GNT",
            SetCode::GameNight2019 => "GN2",
            SetCode::GameNightFreeForAll => "GN3",
            SetCode::Gatecrash => "GTC",
            SetCode::GatecrashPromos => "PGTC",
            SetCode::Gateway2006 => "PGTW",
            SetCode::Gateway2007 => "PG07",
            SetCode::Gateway2008 => "PG08",
            SetCode::GlobalSeriesJiangYangguMuYanling => "GS1",
            SetCode::GrandPrixPromos => "PGPX",
            SetCode::Guildpact => "GPT",
            SetCode::GuildpactPromos => "PGPT",
            SetCode::GuildsOfRavnica => "GRN",
            SetCode::GuildsOfRavnicaPromos => "PGRN",
            SetCode::Guru => "PGRU",
            SetCode::HachetteUK => "PHUK",
            SetCode::HappyHolidays => "HHO",
            SetCode::HarperPrismBookPromos => "PHPR",
            SetCode::HasCon2017 => "H17",
            SetCode::HeadsIWinTailsYouLose => "PHED",
            SetCode::HistoricAnthology1 => "HA1",
            SetCode::HistoricAnthology2 => "HA2",
            SetCode::HistoricAnthology3 => "HA3",
            SetCode::HistoricAnthology4 => "HA4",
            SetCode::HistoricAnthology5 => "HA5",
            SetCode::HistoricAnthology6 => "HA6",
            SetCode::HobbyJapanPromos => "PHJ",
            SetCode::Homelands => "HML",
            SetCode::HourOfDevastation => "HOU",
            SetCode::HourOfDevastationPromos => "PHOU",
            SetCode::IDWComics2013 => "PI13",
            SetCode::IDWComics2014 => "PI14",
            SetCode::IDWComicsInserts => "PIDW",
            SetCode::IceAge => "ICE",
            SetCode::IconicMasters => "IMA",
            SetCode::IkoriaLairOfBehemoths => "IKO",
            SetCode::IkoriaLairOfBehemothsPromos => "PIKO",
            SetCode::Innistrad => "ISD",
            SetCode::InnistradCrimsonVow => "VOW",
            SetCode::InnistradCrimsonVowMinigames => "MVOW",
            SetCode::InnistradCrimsonVowPromos => "PVOW",
            SetCode::InnistradCrimsonVowSubstituteCards => "SVOW",
            SetCode::InnistradDoubleFeature => "DBL",
            SetCode::InnistradMidnightHunt => "MID",
            SetCode::InnistradMidnightHuntMinigames => "MMID",
            SetCode::InnistradMidnightHuntPromos => "PMID",
            SetCode::InnistradMidnightHuntSubstituteCards => "SMID",
            SetCode::InnistradPromos => "PISD",
            SetCode::IntlCollectorsEdition => "CEI",
            SetCode::IntroductoryTwoPlayerSet => "ITP",
            SetCode::Invasion => "INV",
            SetCode::InvasionPromos => "PINV",
            SetCode::Ixalan => "XLN",
            SetCode::IxalanPromos => "PXLN",
            SetCode::JapanJuniorTournament => "PJJT",
            SetCode::JourneyIntoNyx => "JOU",
            SetCode::JourneyIntoNyxHeroSPath => "THP3",
            SetCode::JourneyIntoNyxPromos => "PJOU",
            SetCode::JudgeGiftCards1998 => "JGP",
            SetCode::JudgeGiftCards1999 => "G99",
            SetCode::JudgeGiftCards2000 => "G00",
            SetCode::JudgeGiftCards2001 => "G01",
            SetCode::JudgeGiftCards2002 => "G02",
            SetCode::JudgeGiftCards2003 => "G03",
            SetCode::JudgeGiftCards2004 => "G04",
            SetCode::JudgeGiftCards2005 => "G05",
            SetCode::JudgeGiftCards2006 => "G06",
            SetCode::JudgeGiftCards2007 => "G07",
            SetCode::JudgeGiftCards2008 => "G08",
            SetCode::JudgeGiftCards2009 => "G09",
            SetCode::JudgeGiftCards2010 => "G10",
            SetCode::JudgeGiftCards2011 => "G11",
            SetCode::JudgeGiftCards2012 => "J12",
            SetCode::JudgeGiftCards2013 => "J13",
            SetCode::JudgeGiftCards2014 => "J14",
            SetCode::JudgeGiftCards2015 => "J15",
            SetCode::JudgeGiftCards2016 => "J16",
            SetCode::JudgeGiftCards2017 => "J17",
            SetCode::JudgeGiftCards2018 => "J18",
            SetCode::JudgeGiftCards2019 => "J19",
            SetCode::JudgeGiftCards2020 => "J20",
            SetCode::JudgeGiftCards2021 => "PJ21",
            SetCode::JudgeGiftCards2022 => "P22",
            SetCode::JudgeGiftCards2023 => "P23",
            SetCode::Judgment => "JUD",
            SetCode::JudgmentPromos => "PJUD",
            SetCode::Jumpstart => "JMP",
            SetCode::Jumpstart2022 => "J22",
            SetCode::Jumpstart2022FrontCards => "FJ22",
            SetCode::JumpstartArenaExclusives => "AJMP",
            SetCode::JumpstartFrontCards => "FJMP",
            SetCode::JumpstartHistoricHorizons => "J21",
            SetCode::JuniorAPACSeries => "PJAS",
            SetCode::JuniorSeriesEurope => "PJSE",
            SetCode::JuniorSuperSeries => "PSUS",
            SetCode::Kaladesh => "KLD",
            SetCode::KaladeshInventions => "MPS",
            SetCode::KaladeshPromos => "PKLD",
            SetCode::KaladeshRemastered => "KLR",
            SetCode::Kaldheim => "KHM",
            SetCode::KaldheimArtSeries => "AKHM",
            SetCode::KaldheimCommander => "KHC",
            SetCode::KaldheimMinigames => "MKHM",
            SetCode::KaldheimPromos => "PKHM",
            SetCode::KaldheimSubstituteCards => "SKHM",
            SetCode::KamigawaNeonDynasty => "NEO",
            SetCode::KamigawaNeonDynastyMinigames => "MNEO",
            SetCode::KamigawaNeonDynastyPromos => "PNEO",
            SetCode::KamigawaNeonDynastySubstituteCards => "SNEO",
            SetCode::KhansOfTarkir => "KTK",
            SetCode::KhansOfTarkirPromos => "PKTK",
            SetCode::LeagueTokens2012 => "L12",
            SetCode::LeagueTokens2013 => "L13",
            SetCode::LeagueTokens2014 => "L14",
            SetCode::LeagueTokens2015 => "L15",
            SetCode::LeagueTokens2016 => "L16",
            SetCode::LeagueTokens2017 => "L17",
            SetCode::LegacyChampionship => "OLGC",
            SetCode::LegendaryCubePrizePack => "PZ1",
            SetCode::Legends => "LEG",
            SetCode::Legions => "LGN",
            SetCode::LegionsPromos => "PLGN",
            SetCode::LimitedEditionAlpha => "LEA",
            SetCode::LimitedEditionBeta => "LEB",
            SetCode::LordOfTheRingsTalesOfMiddleEarth => "LTR",
            SetCode::Lorwyn => "LRW",
            SetCode::LorwynPromos => "PLRW",
            SetCode::LoveYourLGS2020 => "PLG20",
            SetCode::LoveYourLGS2021 => "PLG21",
            SetCode::LoveYourLGS2022 => "PLG22",
            SetCode::LunarNewYear2018 => "PLNY",
            SetCode::M15PrereleaseChallenge => "PPC1",
            SetCode::M19GiftPack => "G18",
            SetCode::M19StandardShowdown => "PSS3",
            SetCode::M20PromoPacks => "PPP1",
            SetCode::MTGArenaPromos => "PANA",
            SetCode::Magic2010 => "M10",
            SetCode::Magic2010Promos => "PM10",
            SetCode::Magic2011 => "M11",
            SetCode::Magic2011Promos => "PM11",
            SetCode::Magic2012 => "M12",
            SetCode::Magic2012Promos => "PM12",
            SetCode::Magic2013 => "M13",
            SetCode::Magic2013Promos => "PM13",
            SetCode::Magic2014 => "M14",
            SetCode::Magic2014Promos => "PM14",
            SetCode::Magic2015 => "M15",
            SetCode::Magic2015ClashPack => "CP1",
            SetCode::Magic2015Promos => "PM15",
            SetCode::MagicFest2019 => "PF19",
            SetCode::MagicFest2020 => "PF20",
            SetCode::MagicFest2021 => "PF21",
            SetCode::MagicOnlineAvatars => "PMOA",
            SetCode::MagicOnlinePromos => "PRM",
            SetCode::MagicOnlineThemeDecks => "TD0",
            SetCode::MagicOrigins => "ORI",
            SetCode::MagicOriginsClashPack => "CP3",
            SetCode::MagicOriginsPromos => "PORI",
            SetCode::MagicPlayerRewards2001 => "MPR",
            SetCode::MagicPlayerRewards2002 => "PR2",
            SetCode::MagicPlayerRewards2003 => "P03",
            SetCode::MagicPlayerRewards2004 => "P04",
            SetCode::MagicPlayerRewards2005 => "P05",
            SetCode::MagicPlayerRewards2006 => "P06",
            SetCode::MagicPlayerRewards2007 => "P07",
            SetCode::MagicPlayerRewards2008 => "P08",
            SetCode::MagicPlayerRewards2009 => "P09",
            SetCode::MagicPlayerRewards2010 => "P10",
            SetCode::MagicPlayerRewards2011 => "P11",
            SetCode::MagicPremiereShop2005 => "PMPS",
            SetCode::MagicPremiereShop2006 => "PMPS06",
            SetCode::MagicPremiereShop2007 => "PMPS07",
            SetCode::MagicPremiereShop2008 => "PMPS08",
            SetCode::MagicPremiereShop2009 => "PMPS09",
            SetCode::MagicPremiereShop2010 => "PMPS10",
            SetCode::MagicPremiereShop2011 => "PMPS11",
            SetCode::MarchOfTheMachine => "MOM",
            SetCode::MarchOfTheMachineCommander => "MOC",
            SetCode::MarchOfTheMachineTheAftermath => "MAT",
            SetCode::Masters25 => "A25",
            SetCode::MastersEdition => "ME1",
            SetCode::MastersEditionII => "ME2",
            SetCode::MastersEditionIII => "ME3",
            SetCode::MastersEditionIV => "ME4",
            SetCode::MediaInserts => "PMEI",
            SetCode::MercadianMasques => "MMQ",
            SetCode::MercadianMasquesPromos => "PMMQ",
            SetCode::MicroProsePromos => "PMIC",
            SetCode::MidnightHuntArtSeries => "AMID",
            SetCode::MidnightHuntCommander => "MIC",
            SetCode::MidnightHuntCommanderDisplayCommanders => "OMIC",
            SetCode::Mirage => "MIR",
            SetCode::Mirrodin => "MRD",
            SetCode::MirrodinBesieged => "MBS",
            SetCode::MirrodinBesiegedPromos => "PMBS",
            SetCode::MirrodinPromos => "PMRD",
            SetCode::MiscellaneousBookPromos => "PBOOK",
            SetCode::ModernEventDeck2014 => "MD1",
            SetCode::ModernHorizons => "MH1",
            SetCode::ModernHorizons1Timeshifts => "H1R",
            SetCode::ModernHorizons2 => "MH2",
            SetCode::ModernHorizons2ArtSeries => "AMH2",
            SetCode::ModernHorizons2Minigames => "MMH2",
            SetCode::ModernHorizons2Promos => "PMH2",
            SetCode::ModernHorizonsArtSeries => "AMH1",
            SetCode::ModernHorizonsPromos => "PMH1",
            SetCode::ModernMasters => "MMA",
            SetCode::ModernMasters2015 => "MM2",
            SetCode::ModernMasters2017 => "MM3",
            SetCode::Morningtide => "MOR",
            SetCode::MorningtidePromos => "PMOR",
            SetCode::MultiverseGiftBox => "MGB",
            SetCode::MultiverseLegends => "MUL",
            SetCode::MysteryBooster => "MB1",
            SetCode::MysteryBoosterPlaytestCards2019 => "CMB1",
            SetCode::MysteryBoosterPlaytestCards2021 => "CMB2",
            SetCode::MysteryBoosterRetailEditionFoils => "FMB1",
            SetCode::MythicEdition => "MED",
            SetCode::NationalsPromos => "PNAT",
            SetCode::Nemesis => "NEM",
            SetCode::NemesisPromos => "PNEM",
            SetCode::NeonDynastyArtSeries => "ANEO",
            SetCode::NeonDynastyCommander => "NEC",
            SetCode::NewCapennaArtSeries => "ASNC",
            SetCode::NewCapennaCommander => "NCC",
            SetCode::NewCapennaCommanderPromos => "PNCC",
            SetCode::NewPhyrexia => "NPH",
            SetCode::NewPhyrexiaPromos => "PNPH",
            SetCode::NinthEdition => "9ED",
            SetCode::NinthEditionPromos => "P9ED",
            SetCode::OathOfTheGatewatch => "OGW",
            SetCode::OathOfTheGatewatchPromos => "POGW",
            SetCode::Odyssey => "ODY",
            SetCode::OdysseyPromos => "PODY",
            SetCode::Onslaught => "ONS",
            SetCode::OnslaughtPromos => "PONS",
            SetCode::OpenTheHelvault => "PHEL",
            SetCode::Oversized90SPromos => "O90P",
            SetCode::OversizedLeaguePrizes => "OLEP",
            SetCode::PhyrexiaAllWillBeOne => "ONE",
            SetCode::PhyrexiaAllWillBeOneArtSeries => "AONE",
            SetCode::PhyrexiaAllWillBeOneCommander => "ONC",
            SetCode::PhyrexiaAllWillBeOneJapanesePromoTokens => "WONE",
            SetCode::PhyrexiaAllWillBeOneJumpstartFrontCards => "FONE",
            SetCode::PhyrexiaAllWillBeOneMinigames => "MONE",
            SetCode::PhyrexiaAllWillBeOnePromos => "PONE",
            SetCode::PioneerChallengerDecks2021 => "Q06",
            SetCode::PioneerChallengerDecks2022 => "Q08",
            SetCode::PlanarChaos => "PLC",
            SetCode::PlanarChaosPromos => "PPLC",
            SetCode::Planechase => "HOP",
            SetCode::Planechase2012 => "PC2",
            SetCode::Planechase2012Planes => "OPC2",
            SetCode::PlanechaseAnthology => "PCA",
            SetCode::PlanechaseAnthologyPlanes => "OPCA",
            SetCode::PlanechasePlanes => "OHOP",
            SetCode::PlanechasePromos => "PHOP",
            SetCode::Planeshift => "PLS",
            SetCode::PlaneshiftPromos => "PPLS",
            SetCode::PlaneswalkerChampionshipPromos => "PWCS",
            SetCode::PoniesTheGalloping => "PTG",
            SetCode::Portal => "POR",
            SetCode::PortalSecondAge => "P02",
            SetCode::PortalThreeKingdoms => "PTK",
            SetCode::PortalThreeKingdomsPromos => "PPTK",
            SetCode::PremiumDeckSeriesFireAndLightning => "PD2",
            SetCode::PremiumDeckSeriesGraveborn => "PD3",
            SetCode::PremiumDeckSeriesSlivers => "H09",
            SetCode::ProTourCollectorSet => "PTC",
            SetCode::ProTourPromos => "PPRO",
            SetCode::Prophecy => "PCY",
            SetCode::ProphecyPromos => "PPCY",
            SetCode::RNAGuildKit => "GK2",
            SetCode::RNARavnicaWeekend => "PRW2",
            SetCode::RavnicaAllegiance => "RNA",
            SetCode::RavnicaAllegiancePromos => "PRNA",
            SetCode::RavnicaCityOfGuilds => "RAV",
            SetCode::RavnicaCityOfGuildsPromos => "PRAV",
            SetCode::RedemptionProgram => "PRED",
            SetCode::RegionalChampionshipQualifiers2022 => "PRCQ",
            SetCode::RegionalChampionshipQualifiers2023 => "PR23",
            SetCode::Renaissance => "REN",
            SetCode::ResalePromos => "PRES",
            SetCode::ReturnToRavnica => "RTR",
            SetCode::ReturnToRavnicaPromos => "PRTR",
            SetCode::RevisedEdition => "3ED",
            SetCode::Rinascimento => "RIN",
            SetCode::RiseOfTheEldrazi => "ROE",
            SetCode::RiseOfTheEldraziPromos => "PROE",
            SetCode::RivalsOfIxalan => "RIX",
            SetCode::RivalsOfIxalanPromos => "PRIX",
            SetCode::RivalsQuickStartSet => "RQS",
            SetCode::Salvat2005 => "PSAL",
            SetCode::Salvat2011 => "PS11",
            SetCode::SanDiegoComicCon2013 => "PSDC",
            SetCode::SanDiegoComicCon2014 => "PS14",
            SetCode::SanDiegoComicCon2015 => "PS15",
            SetCode::SanDiegoComicCon2016 => "PS16",
            SetCode::SanDiegoComicCon2017 => "PS17",
            SetCode::SanDiegoComicCon2018 => "PS18",
            SetCode::SanDiegoComicCon2019 => "PS19",
            SetCode::SaviorsOfKamigawa => "SOK",
            SetCode::SaviorsOfKamigawaPromos => "PSOK",
            SetCode::ScarsOfMirrodin => "SOM",
            SetCode::ScarsOfMirrodinPromos => "PSOM",
            SetCode::Scourge => "SCG",
            SetCode::ScourgePromos => "PSCG",
            SetCode::SecretLair30thAnniversaryCountdownKit => "SLC",
            SetCode::SecretLairDrop => "SLD",
            SetCode::SecretLairShowdown => "SLP",
            SetCode::SecretLairUltimateEdition => "SLU",
            SetCode::SegaDreamcastCards => "PSDG",
            SetCode::SeventhEdition => "7ED",
            SetCode::Shadowmoor => "SHM",
            SetCode::ShadowmoorPromos => "PSHM",
            SetCode::ShadowsOverInnistrad => "SOI",
            SetCode::ShadowsOverInnistradPromos => "PSOI",
            SetCode::ShadowsOverInnistradRemastered => "SIR",
            SetCode::ShardsOfAlara => "ALA",
            SetCode::ShardsOfAlaraPromos => "PALA",
            SetCode::SignatureSpellbookChandra => "SS3",
            SetCode::SignatureSpellbookGideon => "SS2",
            SetCode::SignatureSpellbookJace => "SS1",
            SetCode::Starter1999 => "S99",
            SetCode::Starter2000 => "S00",
            SetCode::StarterCommanderDecks => "SCD",
            SetCode::StoreChampionships => "SCH",
            SetCode::StreetsOfNewCapenna => "SNC",
            SetCode::StreetsOfNewCapennaMinigames => "MSNC",
            SetCode::StreetsOfNewCapennaPromos => "PSNC",
            SetCode::StreetsOfNewCapennaSoutheastAsiaTokens => "PTSNC",
            SetCode::StrixhavenArtSeries => "ASTX",
            SetCode::StrixhavenMysticalArchive => "STA",
            SetCode::StrixhavenSchoolOfMages => "STX",
            SetCode::StrixhavenSchoolOfMagesMinigames => "MSTX",
            SetCode::StrixhavenSchoolOfMagesPromos => "PSTX",
            SetCode::StrixhavenSchoolOfMagesSubstituteCards => "SSTX",
            SetCode::Stronghold => "STH",
            SetCode::StrongholdPromos => "PSTH",
            SetCode::SummerMagicEdgar => "SUM",
            SetCode::SummerOfMagic => "PSUM",
            SetCode::SummerVacationPromos2022 => "PSVC",
            SetCode::TarkirDragonfury => "PTKDF",
            SetCode::Tempest => "TMP",
            SetCode::TempestPromos => "PTMP",
            SetCode::TempestRemastered => "TPR",
            SetCode::TenthEdition => "10E",
            SetCode::TenthEditionPromos => "P10E",
            SetCode::TheBrothersWar => "BRO",
            SetCode::TheBrothersWarArtSeries => "ABRO",
            SetCode::TheBrothersWarCommander => "BRC",
            SetCode::TheBrothersWarMinigames => "MBRO",
            SetCode::TheBrothersWarPromos => "PBRO",
            SetCode::TheBrothersWarRetroArtifacts => "BRR",
            SetCode::TheDark => "DRK",
            SetCode::TheList => "PLIST",
            SetCode::TheListUnfinityFoilEdition => "UPLIST",
            SetCode::Theros => "THS",
            SetCode::TherosBeyondDeath => "THB",
            SetCode::TherosBeyondDeathPromos => "PTHB",
            SetCode::TherosHeroSPath => "THP1",
            SetCode::TherosPromos => "PTHS",
            SetCode::ThirtythAnniversaryEdition => "30A",
            SetCode::ThirtythAnniversaryHistoryPromos => "P30H",
            SetCode::ThirtythAnniversaryPlayPromos => "P30A",
            SetCode::ThroneOfEldraine => "ELD",
            SetCode::ThroneOfEldrainePromos => "PELD",
            SetCode::TimeSpiral => "TSP",
            SetCode::TimeSpiralPromos => "PTSP",
            SetCode::TimeSpiralRemastered => "TSR",
            SetCode::TimeSpiralTimeshifted => "TSB",
            SetCode::Torment => "TOR",
            SetCode::TormentPromos => "PTOR",
            SetCode::Transformers => "BOT",
            SetCode::TreasureChest => "PZ2",
            SetCode::TwoHeadedGiantTournament => "P2HG",
            SetCode::TwoThousandEighteenHeroesOfTheRealm => "PH18",
            SetCode::TwoThousandNineteenHeroesOfTheRealm => "PH19",
            SetCode::TwoThousandSeventeenGiftPack => "G17",
            SetCode::TwoThousandSeventeenHeroesOfTheRealm => "PH17",
            SetCode::TwoThousandSixteenHeroesOfTheRealm => "PHTR",
            SetCode::TwoThousandTwentyHeroesOfTheRealm => "PH20",
            SetCode::TwoThousandTwentyOneHeroesOfTheRealm => "PH21",
            SetCode::URLConventionPromos => "PURL",
            SetCode::UginSFate => "UGIN",
            SetCode::UltimateBoxTopper => "PUMA",
            SetCode::UltimateMasters => "UMA",
            SetCode::Unfinity => "UNF",
            SetCode::UnfinityStickerSheets => "SUNF",
            SetCode::Unglued => "UGL",
            SetCode::Unhinged => "UNH",
            SetCode::UnhingedPromos => "PUNH",
            SetCode::UniversesWithin => "SLX",
            SetCode::UnlimitedEdition => "2ED",
            SetCode::Unsanctioned => "UND",
            SetCode::Unstable => "UST",
            SetCode::UnstablePromos => "PUST",
            SetCode::UrzaSDestiny => "UDS",
            SetCode::UrzaSDestinyPromos => "PUDS",
            SetCode::UrzaSLegacy => "ULG",
            SetCode::UrzaSLegacyPromos => "PULG",
            SetCode::UrzaSSaga => "USG",
            SetCode::UrzaSSagaPromos => "PUSG",
            SetCode::VanguardSeries => "PVAN",
            SetCode::VintageChampionship => "OVNT",
            SetCode::VintageMasters => "VMA",
            SetCode::Visions => "VIS",
            SetCode::WarOfTheSpark => "WAR",
            SetCode::WarOfTheSparkPromos => "PWAR",
            SetCode::Warhammer40000Commander => "40K",
            SetCode::Weatherlight => "WTH",
            SetCode::WelcomeDeck2016 => "W16",
            SetCode::WelcomeDeck2017 => "W17",
            SetCode::WizardsOfTheCoastOnlineStore => "PWOS",
            SetCode::WizardsPlayNetwork2008 => "PWPN",
            SetCode::WizardsPlayNetwork2009 => "PW09",
            SetCode::WizardsPlayNetwork2010 => "PW10",
            SetCode::WizardsPlayNetwork2011 => "PW11",
            SetCode::WizardsPlayNetwork2012 => "PW12",
            SetCode::WizardsPlayNetwork2021 => "PW21",
            SetCode::WizardsPlayNetwork2022 => "PW22",
            SetCode::WizardsPlayNetwork2023 => "PW23",
            SetCode::WorldChampionshipDecks1997 => "WC97",
            SetCode::WorldChampionshipDecks1998 => "WC98",
            SetCode::WorldChampionshipDecks1999 => "WC99",
            SetCode::WorldChampionshipDecks2000 => "WC00",
            SetCode::WorldChampionshipDecks2001 => "WC01",
            SetCode::WorldChampionshipDecks2002 => "WC02",
            SetCode::WorldChampionshipDecks2003 => "WC03",
            SetCode::WorldChampionshipDecks2004 => "WC04",
            SetCode::WorldChampionshipPromos => "PWOR",
            SetCode::WorldMagicCupQualifiers => "WMC",
            SetCode::Worldwake => "WWK",
            SetCode::WorldwakePromos => "PWWK",
            SetCode::XLNStandardShowdown => "PSS2",
            SetCode::XLNTreasureChest => "PXTC",
            SetCode::YearOfTheOx2021 => "PL21",
            SetCode::YearOfTheRabbit2023 => "PL23",
            SetCode::YearOfTheTiger2022 => "PL22",
            SetCode::Zendikar => "ZEN",
            SetCode::ZendikarExpeditions => "EXP",
            SetCode::ZendikarPromos => "PZEN",
            SetCode::ZendikarRising => "ZNR",
            SetCode::ZendikarRisingArtSeries => "AZNR",
            SetCode::ZendikarRisingCommander => "ZNC",
            SetCode::ZendikarRisingExpeditions => "ZNE",
            SetCode::ZendikarRisingMinigames => "MZNR",
            SetCode::ZendikarRisingPromos => "PZNR",
            SetCode::ZendikarRisingSubstituteCards => "SZNR",
        }
        ;
    }

    public function getName(null|string $value = null): string
    {
        $value ??= $this->value;
        if (!isset(SetCode::CODE_NAME_MAP[$value])) {
            throw new \RuntimeException('Invalid code...');
        }
        return SetCode::CODE_NAME_MAP[$value];
    }

    public function fromName(string $name): self
    {
        $nameCodes = array_flip(SetCode::CODE_NAME_MAP);
        if (!isset($nameCodes[$name])) {
            throw new \RuntimeException('Invalid code...');
        }
        return SetCode::from($nameCodes[$name]);
    }
}
