<?php declare(strict_types=1);

namespace MallardDuck\MtgCardsSdk\Enums;

/**
 * @see \MallardDuck\MtgCardsSdk\Generator\Actions\GenerateSetCodeAction
 */
enum SetCode: string
{
	public const CODE_NAME_MAP = [
		'AFR' => 'Adventures in the Forgotten Realms',
		'AAFR' => 'Adventures in the Forgotten Realms Art Series',
		'MAFR' => 'Adventures in the Forgotten Realms Minigames',
		'PAFR' => 'Adventures in the Forgotten Realms Promos',
		'AER' => 'Aether Revolt',
		'PAER' => 'Aether Revolt Promos',
		'ARB' => 'Alara Reborn',
		'PARB' => 'Alara Reborn Promos',
		'YDMU' => 'Alchemy: Dominaria',
		'HBG' => 'Alchemy Horizons: Baldur\'s Gate',
		'YMID' => 'Alchemy: Innistrad',
		'YNEO' => 'Alchemy: Kamigawa',
		'YSNC' => 'Alchemy: New Capenna',
		'YONE' => 'Alchemy: Phyrexia',
		'YBRO' => 'Alchemy: The Brothers\' War',
		'ALL' => 'Alliances',
		'AKH' => 'Amonkhet',
		'MP2' => 'Amonkhet Invocations',
		'PAKH' => 'Amonkhet Promos',
		'AKR' => 'Amonkhet Remastered',
		'ATH' => 'Anthologies',
		'ATQ' => 'Antiquities',
		'APC' => 'Apocalypse',
		'PAPC' => 'Apocalypse Promos',
		'ARN' => 'Arabian Nights',
		'ARC' => 'Archenemy',
		'E01' => 'Archenemy: Nicol Bolas',
		'OE01' => 'Archenemy: Nicol Bolas Schemes',
		'PARC' => 'Archenemy Promos',
		'OARC' => 'Archenemy Schemes',
		'ANB' => 'Arena Beginner Set',
		'PARL' => 'Arena League 1996',
		'PAL99' => 'Arena League 1999',
		'PAL00' => 'Arena League 2000',
		'PAL01' => 'Arena League 2001',
		'PAL02' => 'Arena League 2002',
		'PAL03' => 'Arena League 2003',
		'PAL04' => 'Arena League 2004',
		'PAL05' => 'Arena League 2005',
		'PAL06' => 'Arena League 2006',
		'ANA' => 'Arena New Player Experience',
		'OANA' => 'Arena New Player Experience Cards',
		'XANA' => 'Arena New Player Experience Extras',
		'PALP' => 'Asia Pacific Land Program',
		'PAST' => 'Astral Cards',
		'AVR' => 'Avacyn Restored',
		'PAVR' => 'Avacyn Restored Promos',
		'PSS1' => 'BFZ Standard Series',
		'ACLB' => 'Battle for Baldur\'s Gate Art Series',
		'PCLB' => 'Battle for Baldur\'s Gate Promos',
		'BFZ' => 'Battle for Zendikar',
		'PBFZ' => 'Battle for Zendikar Promos',
		'BRB' => 'Battle Royale Box Set',
		'TBTH' => 'Battle the Horde',
		'BBD' => 'Battlebond',
		'PBBD' => 'Battlebond Promos',
		'BTD' => 'Beatdown Box Set',
		'BOK' => 'Betrayers of Kamigawa',
		'PBOK' => 'Betrayers of Kamigawa Promos',
		'BNG' => 'Born of the Gods',
		'THP2' => 'Born of the Gods Hero\'s Path',
		'PBNG' => 'Born of the Gods Promos',
		'PCEL' => 'Celebration Cards',
		'Q07' => 'Challenger Decks 2022',
		'CHK' => 'Champions of Kamigawa',
		'PCHK' => 'Champions of Kamigawa Promos',
		'PCMP' => 'Champs and States',
		'CHR' => 'Chronicles',
		'6ED' => 'Classic Sixth Edition',
		'CSP' => 'Coldsnap',
		'PCSP' => 'Coldsnap Promos',
		'CST' => 'Coldsnap Theme Decks',
		'CED' => 'Collectors’ Edition',
		'CMD' => 'Commander 2011',
		'PCMD' => 'Commander 2011 Launch Party',
		'OCMD' => 'Commander 2011 Oversized',
		'C13' => 'Commander 2013',
		'OC13' => 'Commander 2013 Oversized',
		'C14' => 'Commander 2014',
		'OC14' => 'Commander 2014 Oversized',
		'C15' => 'Commander 2015',
		'OC15' => 'Commander 2015 Oversized',
		'C16' => 'Commander 2016',
		'OC16' => 'Commander 2016 Oversized',
		'C17' => 'Commander 2017',
		'OC17' => 'Commander 2017 Oversized',
		'C18' => 'Commander 2018',
		'OC18' => 'Commander 2018 Oversized',
		'C19' => 'Commander 2019',
		'OC19' => 'Commander 2019 Oversized',
		'C20' => 'Commander 2020',
		'OC20' => 'Commander 2020 Oversized',
		'C21' => 'Commander 2021',
		'OC21' => 'Commander 2021 Display Commanders',
		'CMA' => 'Commander Anthology',
		'CM2' => 'Commander Anthology Volume II',
		'CC2' => 'Commander Collection: Black',
		'CC1' => 'Commander Collection: Green',
		'CMR' => 'Commander Legends',
		'CLB' => 'Commander Legends: Battle for Baldur\'s Gate',
		'MCLB' => 'Commander Legends: Battle for Baldur\'s Gate Minigames',
		'CMM' => 'Commander Masters',
		'CM1' => 'Commander\'s Arsenal',
		'OCM1' => 'Commander\'s Arsenal Oversized',
		'CON' => 'Conflux',
		'PCON' => 'Conflux Promos',
		'CNS' => 'Conspiracy',
		'PCNS' => 'Conspiracy Promos',
		'CN2' => 'Conspiracy: Take the Crown',
		'M19' => 'Core Set 2019',
		'PM19' => 'Core Set 2019 Promos',
		'M20' => 'Core Set 2020',
		'PM20' => 'Core Set 2020 Promos',
		'M21' => 'Core Set 2021',
		'PM21' => 'Core Set 2021 Promos',
		'AVOW' => 'Crimson Vow Art Series',
		'VOC' => 'Crimson Vow Commander',
		'OVOC' => 'Crimson Vow Commander Display Commanders',
		'PLGM' => 'DCI Legend Membership',
		'PDCI' => 'DCI Promos',
		'DKA' => 'Dark Ascension',
		'PDKA' => 'Dark Ascension Promos',
		'DST' => 'Darksteel',
		'PDST' => 'Darksteel Promos',
		'DKM' => 'Deckmasters',
		'TDAG' => 'Defeat a God',
		'DIS' => 'Dissension',
		'PDIS' => 'Dissension Promos',
		'DOM' => 'Dominaria',
		'PDOM' => 'Dominaria Promos',
		'DMR' => 'Dominaria Remastered',
		'DMU' => 'Dominaria United',
		'ADMU' => 'Dominaria United Art Series',
		'DMC' => 'Dominaria United Commander',
		'WDMU' => 'Dominaria United Japanese Promo Tokens',
		'MDMU' => 'Dominaria United Minigames',
		'PDMU' => 'Dominaria United Promos',
		'2XM' => 'Double Masters',
		'2X2' => 'Double Masters 2022',
		'PDRC' => 'Dragon Con',
		'DGM' => 'Dragon\'s Maze',
		'PDGM' => 'Dragon\'s Maze Promos',
		'DTK' => 'Dragons of Tarkir',
		'PDTK' => 'Dragons of Tarkir Promos',
		'DDH' => 'Duel Decks: Ajani vs. Nicol Bolas',
		'DVD' => 'Duel Decks Anthology: Divine vs. Demonic',
		'EVG' => 'Duel Decks Anthology: Elves vs. Goblins',
		'GVL' => 'Duel Decks Anthology: Garruk vs. Liliana',
		'JVC' => 'Duel Decks Anthology: Jace vs. Chandra',
		'DDQ' => 'Duel Decks: Blessed vs. Cursed',
		'DDC' => 'Duel Decks: Divine vs. Demonic',
		'DDO' => 'Duel Decks: Elspeth vs. Kiora',
		'DDF' => 'Duel Decks: Elspeth vs. Tezzeret',
		'DD1' => 'Duel Decks: Elves vs. Goblins',
		'DDU' => 'Duel Decks: Elves vs. Inventors',
		'DDD' => 'Duel Decks: Garruk vs. Liliana',
		'DDL' => 'Duel Decks: Heroes vs. Monsters',
		'DDJ' => 'Duel Decks: Izzet vs. Golgari',
		'DD2' => 'Duel Decks: Jace vs. Chandra',
		'DDM' => 'Duel Decks: Jace vs. Vraska',
		'DDG' => 'Duel Decks: Knights vs. Dragons',
		'DDT' => 'Duel Decks: Merfolk vs. Goblins',
		'DDS' => 'Duel Decks: Mind vs. Might',
		'TD2' => 'Duel Decks: Mirrodin Pure vs. New Phyrexia',
		'DDR' => 'Duel Decks: Nissa vs. Ob Nixilis',
		'DDE' => 'Duel Decks: Phyrexia vs. the Coalition',
		'DDK' => 'Duel Decks: Sorin vs. Tibalt',
		'DDN' => 'Duel Decks: Speed vs. Cunning',
		'DDI' => 'Duel Decks: Venser vs. Koth',
		'DDP' => 'Duel Decks: Zendikar vs. Eldrazi',
		'DPA' => 'Duels of the Planeswalkers',
		'PDTP' => 'Duels of the Planeswalkers 2009 Promos',
		'PDP10' => 'Duels of the Planeswalkers 2010 Promos',
		'PDP12' => 'Duels of the Planeswalkers 2012 Promos',
		'PDP13' => 'Duels of the Planeswalkers 2013 Promos',
		'PDP14' => 'Duels of the Planeswalkers 2014 Promos',
		'PDP15' => 'Duels of the Planeswalkers 2015 Promos',
		'8ED' => 'Eighth Edition',
		'P8ED' => 'Eighth Edition Promos',
		'EMN' => 'Eldritch Moon',
		'PEMN' => 'Eldritch Moon Promos',
		'EMA' => 'Eternal Masters',
		'PEWK' => 'Eternal Weekend 2022',
		'PELP' => 'European Land Program',
		'EVE' => 'Eventide',
		'PEVE' => 'Eventide Promos',
		'EXO' => 'Exodus',
		'PEXO' => 'Exodus Promos',
		'EA1' => 'Explorer Anthology 1',
		'EA2' => 'Explorer Anthology 2',
		'E02' => 'Explorers of Ixalan',
		'BCHR' => 'FBB Chronicles',
		'TFTH' => 'Face the Hydra',
		'FEM' => 'Fallen Empires',
		'FRF' => 'Fate Reforged',
		'CP2' => 'Fate Reforged Clash Pack',
		'PFRF' => 'Fate Reforged Promos',
		'P15A' => '15th Anniversary Cards',
		'5DN' => 'Fifth Dawn',
		'P5DN' => 'Fifth Dawn Promos',
		'5ED' => 'Fifth Edition',
		'FBB' => 'Foreign Black Border',
		'AFC' => 'Forgotten Realms Commander',
		'OAFC' => 'Forgotten Realms Commander Display Commanders',
		'4ED' => 'Fourth Edition',
		'4BB' => 'Fourth Edition Foreign Black Border',
		'FNM' => 'Friday Night Magic 2000',
		'F01' => 'Friday Night Magic 2001',
		'F02' => 'Friday Night Magic 2002',
		'F03' => 'Friday Night Magic 2003',
		'F04' => 'Friday Night Magic 2004',
		'F05' => 'Friday Night Magic 2005',
		'F06' => 'Friday Night Magic 2006',
		'F07' => 'Friday Night Magic 2007',
		'F08' => 'Friday Night Magic 2008',
		'F09' => 'Friday Night Magic 2009',
		'F10' => 'Friday Night Magic 2010',
		'F11' => 'Friday Night Magic 2011',
		'F12' => 'Friday Night Magic 2012',
		'F13' => 'Friday Night Magic 2013',
		'F14' => 'Friday Night Magic 2014',
		'F15' => 'Friday Night Magic 2015',
		'F16' => 'Friday Night Magic 2016',
		'F17' => 'Friday Night Magic 2017',
		'F18' => 'Friday Night Magic 2018',
		'V15' => 'From the Vault: Angels',
		'V14' => 'From the Vault: Annihilation',
		'DRB' => 'From the Vault: Dragons',
		'V09' => 'From the Vault: Exiled',
		'V11' => 'From the Vault: Legends',
		'V16' => 'From the Vault: Lore',
		'V12' => 'From the Vault: Realms',
		'V10' => 'From the Vault: Relics',
		'V17' => 'From the Vault: Transform',
		'V13' => 'From the Vault: Twenty',
		'FUT' => 'Future Sight',
		'PFUT' => 'Future Sight Promos',
		'GK1' => 'GRN Guild Kit',
		'PRWK' => 'GRN Ravnica Weekend',
		'GDY' => 'Game Day Promos',
		'GNT' => 'Game Night',
		'GN2' => 'Game Night 2019',
		'GN3' => 'Game Night: Free-for-All',
		'GTC' => 'Gatecrash',
		'PGTC' => 'Gatecrash Promos',
		'PGTW' => 'Gateway 2006',
		'PG07' => 'Gateway 2007',
		'PG08' => 'Gateway 2008',
		'GS1' => 'Global Series Jiang Yanggu & Mu Yanling',
		'PGPX' => 'Grand Prix Promos',
		'GPT' => 'Guildpact',
		'PGPT' => 'Guildpact Promos',
		'GRN' => 'Guilds of Ravnica',
		'PGRN' => 'Guilds of Ravnica Promos',
		'PGRU' => 'Guru',
		'PHUK' => 'Hachette UK',
		'HHO' => 'Happy Holidays',
		'PHPR' => 'HarperPrism Book Promos',
		'H17' => 'HasCon 2017',
		'PHED' => 'Heads I Win, Tails You Lose',
		'HA1' => 'Historic Anthology 1',
		'HA2' => 'Historic Anthology 2',
		'HA3' => 'Historic Anthology 3',
		'HA4' => 'Historic Anthology 4',
		'HA5' => 'Historic Anthology 5',
		'HA6' => 'Historic Anthology 6',
		'PHJ' => 'Hobby Japan Promos',
		'HML' => 'Homelands',
		'HOU' => 'Hour of Devastation',
		'PHOU' => 'Hour of Devastation Promos',
		'PI13' => 'IDW Comics 2013',
		'PI14' => 'IDW Comics 2014',
		'PIDW' => 'IDW Comics Inserts',
		'ICE' => 'Ice Age',
		'IMA' => 'Iconic Masters',
		'IKO' => 'Ikoria: Lair of Behemoths',
		'PIKO' => 'Ikoria: Lair of Behemoths Promos',
		'ISD' => 'Innistrad',
		'VOW' => 'Innistrad: Crimson Vow',
		'MVOW' => 'Innistrad: Crimson Vow Minigames',
		'PVOW' => 'Innistrad: Crimson Vow Promos',
		'SVOW' => 'Innistrad: Crimson Vow Substitute Cards',
		'DBL' => 'Innistrad: Double Feature',
		'MID' => 'Innistrad: Midnight Hunt',
		'MMID' => 'Innistrad: Midnight Hunt Minigames',
		'PMID' => 'Innistrad: Midnight Hunt Promos',
		'SMID' => 'Innistrad: Midnight Hunt Substitute Cards',
		'PISD' => 'Innistrad Promos',
		'CEI' => 'Intl. Collectors’ Edition',
		'ITP' => 'Introductory Two-Player Set',
		'INV' => 'Invasion',
		'PINV' => 'Invasion Promos',
		'XLN' => 'Ixalan',
		'PXLN' => 'Ixalan Promos',
		'PJJT' => 'Japan Junior Tournament',
		'JOU' => 'Journey into Nyx',
		'THP3' => 'Journey into Nyx Hero\'s Path',
		'PJOU' => 'Journey into Nyx Promos',
		'JGP' => 'Judge Gift Cards 1998',
		'G99' => 'Judge Gift Cards 1999',
		'G00' => 'Judge Gift Cards 2000',
		'G01' => 'Judge Gift Cards 2001',
		'G02' => 'Judge Gift Cards 2002',
		'G03' => 'Judge Gift Cards 2003',
		'G04' => 'Judge Gift Cards 2004',
		'G05' => 'Judge Gift Cards 2005',
		'G06' => 'Judge Gift Cards 2006',
		'G07' => 'Judge Gift Cards 2007',
		'G08' => 'Judge Gift Cards 2008',
		'G09' => 'Judge Gift Cards 2009',
		'G10' => 'Judge Gift Cards 2010',
		'G11' => 'Judge Gift Cards 2011',
		'J12' => 'Judge Gift Cards 2012',
		'J13' => 'Judge Gift Cards 2013',
		'J14' => 'Judge Gift Cards 2014',
		'J15' => 'Judge Gift Cards 2015',
		'J16' => 'Judge Gift Cards 2016',
		'J17' => 'Judge Gift Cards 2017',
		'J18' => 'Judge Gift Cards 2018',
		'J19' => 'Judge Gift Cards 2019',
		'J20' => 'Judge Gift Cards 2020',
		'PJ21' => 'Judge Gift Cards 2021',
		'P22' => 'Judge Gift Cards 2022',
		'P23' => 'Judge Gift Cards 2023',
		'JUD' => 'Judgment',
		'PJUD' => 'Judgment Promos',
		'JMP' => 'Jumpstart',
		'J22' => 'Jumpstart 2022',
		'FJ22' => 'Jumpstart 2022 Front Cards',
		'AJMP' => 'Jumpstart Arena Exclusives',
		'FJMP' => 'Jumpstart Front Cards',
		'J21' => 'Jumpstart: Historic Horizons',
		'PJAS' => 'Junior APAC Series',
		'PJSE' => 'Junior Series Europe',
		'PSUS' => 'Junior Super Series',
		'KLD' => 'Kaladesh',
		'MPS' => 'Kaladesh Inventions',
		'PKLD' => 'Kaladesh Promos',
		'KLR' => 'Kaladesh Remastered',
		'KHM' => 'Kaldheim',
		'AKHM' => 'Kaldheim Art Series',
		'KHC' => 'Kaldheim Commander',
		'MKHM' => 'Kaldheim Minigames',
		'PKHM' => 'Kaldheim Promos',
		'SKHM' => 'Kaldheim Substitute Cards',
		'NEO' => 'Kamigawa: Neon Dynasty',
		'MNEO' => 'Kamigawa: Neon Dynasty Minigames',
		'PNEO' => 'Kamigawa: Neon Dynasty Promos',
		'SNEO' => 'Kamigawa: Neon Dynasty Substitute Cards',
		'KTK' => 'Khans of Tarkir',
		'PKTK' => 'Khans of Tarkir Promos',
		'L12' => 'League Tokens 2012',
		'L13' => 'League Tokens 2013',
		'L14' => 'League Tokens 2014',
		'L15' => 'League Tokens 2015',
		'L16' => 'League Tokens 2016',
		'L17' => 'League Tokens 2017',
		'OLGC' => 'Legacy Championship',
		'PZ1' => 'Legendary Cube Prize Pack',
		'LEG' => 'Legends',
		'LGN' => 'Legions',
		'PLGN' => 'Legions Promos',
		'LEA' => 'Limited Edition Alpha',
		'LEB' => 'Limited Edition Beta',
		'LTR' => 'Lord of the Rings: Tales of Middle-Earth',
		'LRW' => 'Lorwyn',
		'PLRW' => 'Lorwyn Promos',
		'PLG20' => 'Love Your LGS 2020',
		'PLG21' => 'Love Your LGS 2021',
		'PLG22' => 'Love Your LGS 2022',
		'PLNY' => 'Lunar New Year 2018',
		'PPC1' => 'M15 Prerelease Challenge',
		'G18' => 'M19 Gift Pack',
		'PSS3' => 'M19 Standard Showdown',
		'PPP1' => 'M20 Promo Packs',
		'PANA' => 'MTG Arena Promos',
		'M10' => 'Magic 2010',
		'PM10' => 'Magic 2010 Promos',
		'M11' => 'Magic 2011',
		'PM11' => 'Magic 2011 Promos',
		'M12' => 'Magic 2012',
		'PM12' => 'Magic 2012 Promos',
		'M13' => 'Magic 2013',
		'PM13' => 'Magic 2013 Promos',
		'M14' => 'Magic 2014',
		'PM14' => 'Magic 2014 Promos',
		'M15' => 'Magic 2015',
		'CP1' => 'Magic 2015 Clash Pack',
		'PM15' => 'Magic 2015 Promos',
		'PF19' => 'MagicFest 2019',
		'PF20' => 'MagicFest 2020',
		'PF21' => 'MagicFest 2021',
		'PMOA' => 'Magic Online Avatars',
		'PRM' => 'Magic Online Promos',
		'TD0' => 'Magic Online Theme Decks',
		'ORI' => 'Magic Origins',
		'CP3' => 'Magic Origins Clash Pack',
		'PORI' => 'Magic Origins Promos',
		'MPR' => 'Magic Player Rewards 2001',
		'PR2' => 'Magic Player Rewards 2002',
		'P03' => 'Magic Player Rewards 2003',
		'P04' => 'Magic Player Rewards 2004',
		'P05' => 'Magic Player Rewards 2005',
		'P06' => 'Magic Player Rewards 2006',
		'P07' => 'Magic Player Rewards 2007',
		'P08' => 'Magic Player Rewards 2008',
		'P09' => 'Magic Player Rewards 2009',
		'P10' => 'Magic Player Rewards 2010',
		'P11' => 'Magic Player Rewards 2011',
		'PMPS' => 'Magic Premiere Shop 2005',
		'PMPS06' => 'Magic Premiere Shop 2006',
		'PMPS07' => 'Magic Premiere Shop 2007',
		'PMPS08' => 'Magic Premiere Shop 2008',
		'PMPS09' => 'Magic Premiere Shop 2009',
		'PMPS10' => 'Magic Premiere Shop 2010',
		'PMPS11' => 'Magic Premiere Shop 2011',
		'MOM' => 'March of the Machine',
		'MOC' => 'March of the Machine Commander',
		'MAT' => 'March of the Machine: The Aftermath',
		'A25' => 'Masters 25',
		'ME1' => 'Masters Edition',
		'ME2' => 'Masters Edition II',
		'ME3' => 'Masters Edition III',
		'ME4' => 'Masters Edition IV',
		'PMEI' => 'Media Inserts',
		'MMQ' => 'Mercadian Masques',
		'PMMQ' => 'Mercadian Masques Promos',
		'PMIC' => 'MicroProse Promos',
		'AMID' => 'Midnight Hunt Art Series',
		'MIC' => 'Midnight Hunt Commander',
		'OMIC' => 'Midnight Hunt Commander Display Commanders',
		'MIR' => 'Mirage',
		'MRD' => 'Mirrodin',
		'MBS' => 'Mirrodin Besieged',
		'PMBS' => 'Mirrodin Besieged Promos',
		'PMRD' => 'Mirrodin Promos',
		'PBOOK' => 'Miscellaneous Book Promos',
		'MD1' => 'Modern Event Deck 2014',
		'MH1' => 'Modern Horizons',
		'H1R' => 'Modern Horizons 1 Timeshifts',
		'MH2' => 'Modern Horizons 2',
		'AMH2' => 'Modern Horizons 2 Art Series',
		'MMH2' => 'Modern Horizons 2 Minigames',
		'PMH2' => 'Modern Horizons 2 Promos',
		'AMH1' => 'Modern Horizons Art Series',
		'PMH1' => 'Modern Horizons Promos',
		'MMA' => 'Modern Masters',
		'MM2' => 'Modern Masters 2015',
		'MM3' => 'Modern Masters 2017',
		'MOR' => 'Morningtide',
		'PMOR' => 'Morningtide Promos',
		'MGB' => 'Multiverse Gift Box',
		'MUL' => 'Multiverse Legends',
		'MB1' => 'Mystery Booster',
		'CMB1' => 'Mystery Booster Playtest Cards 2019',
		'CMB2' => 'Mystery Booster Playtest Cards 2021',
		'FMB1' => 'Mystery Booster Retail Edition Foils',
		'MED' => 'Mythic Edition',
		'PNAT' => 'Nationals Promos',
		'NEM' => 'Nemesis',
		'PNEM' => 'Nemesis Promos',
		'ANEO' => 'Neon Dynasty Art Series',
		'NEC' => 'Neon Dynasty Commander',
		'ASNC' => 'New Capenna Art Series',
		'NCC' => 'New Capenna Commander',
		'PNCC' => 'New Capenna Commander Promos',
		'NPH' => 'New Phyrexia',
		'PNPH' => 'New Phyrexia Promos',
		'9ED' => 'Ninth Edition',
		'P9ED' => 'Ninth Edition Promos',
		'OGW' => 'Oath of the Gatewatch',
		'POGW' => 'Oath of the Gatewatch Promos',
		'ODY' => 'Odyssey',
		'PODY' => 'Odyssey Promos',
		'ONS' => 'Onslaught',
		'PONS' => 'Onslaught Promos',
		'PHEL' => 'Open the Helvault',
		'O90P' => 'Oversized 90\'s Promos',
		'OLEP' => 'Oversized League Prizes',
		'ONE' => 'Phyrexia: All Will Be One',
		'AONE' => 'Phyrexia: All Will Be One Art Series',
		'ONC' => 'Phyrexia: All Will Be One Commander',
		'WONE' => 'Phyrexia: All Will Be One Japanese Promo Tokens',
		'FONE' => 'Phyrexia: All Will Be One Jumpstart Front Cards',
		'MONE' => 'Phyrexia: All Will Be One Minigames',
		'PONE' => 'Phyrexia: All Will Be One Promos',
		'Q06' => 'Pioneer Challenger Decks 2021',
		'Q08' => 'Pioneer Challenger Decks 2022',
		'PLC' => 'Planar Chaos',
		'PPLC' => 'Planar Chaos Promos',
		'HOP' => 'Planechase',
		'PC2' => 'Planechase 2012',
		'OPC2' => 'Planechase 2012 Planes',
		'PCA' => 'Planechase Anthology',
		'OPCA' => 'Planechase Anthology Planes',
		'OHOP' => 'Planechase Planes',
		'PHOP' => 'Planechase Promos',
		'PLS' => 'Planeshift',
		'PPLS' => 'Planeshift Promos',
		'PWCS' => 'Planeswalker Championship Promos',
		'PTG' => 'Ponies: The Galloping',
		'POR' => 'Portal',
		'P02' => 'Portal Second Age',
		'PTK' => 'Portal Three Kingdoms',
		'PPTK' => 'Portal: Three Kingdoms Promos',
		'PD2' => 'Premium Deck Series: Fire and Lightning',
		'PD3' => 'Premium Deck Series: Graveborn',
		'H09' => 'Premium Deck Series: Slivers',
		'PTC' => 'Pro Tour Collector Set',
		'PPRO' => 'Pro Tour Promos',
		'PCY' => 'Prophecy',
		'PPCY' => 'Prophecy Promos',
		'GK2' => 'RNA Guild Kit',
		'PRW2' => 'RNA Ravnica Weekend',
		'RNA' => 'Ravnica Allegiance',
		'PRNA' => 'Ravnica Allegiance Promos',
		'RAV' => 'Ravnica: City of Guilds',
		'PRAV' => 'Ravnica: City of Guilds Promos',
		'PRED' => 'Redemption Program',
		'PRCQ' => 'Regional Championship Qualifiers 2022',
		'PR23' => 'Regional Championship Qualifiers 2023',
		'REN' => 'Renaissance',
		'PRES' => 'Resale Promos',
		'RTR' => 'Return to Ravnica',
		'PRTR' => 'Return to Ravnica Promos',
		'3ED' => 'Revised Edition',
		'RIN' => 'Rinascimento',
		'ROE' => 'Rise of the Eldrazi',
		'PROE' => 'Rise of the Eldrazi Promos',
		'RIX' => 'Rivals of Ixalan',
		'PRIX' => 'Rivals of Ixalan Promos',
		'RQS' => 'Rivals Quick Start Set',
		'PSAL' => 'Salvat 2005',
		'PS11' => 'Salvat 2011',
		'PSDC' => 'San Diego Comic-Con 2013',
		'PS14' => 'San Diego Comic-Con 2014',
		'PS15' => 'San Diego Comic-Con 2015',
		'PS16' => 'San Diego Comic-Con 2016',
		'PS17' => 'San Diego Comic-Con 2017',
		'PS18' => 'San Diego Comic-Con 2018',
		'PS19' => 'San Diego Comic-Con 2019',
		'SOK' => 'Saviors of Kamigawa',
		'PSOK' => 'Saviors of Kamigawa Promos',
		'SOM' => 'Scars of Mirrodin',
		'PSOM' => 'Scars of Mirrodin Promos',
		'SCG' => 'Scourge',
		'PSCG' => 'Scourge Promos',
		'SLC' => 'Secret Lair 30th Anniversary Countdown Kit',
		'SLD' => 'Secret Lair Drop',
		'SLP' => 'Secret Lair Showdown',
		'SLU' => 'Secret Lair: Ultimate Edition',
		'PSDG' => 'Sega Dreamcast Cards',
		'7ED' => 'Seventh Edition',
		'SHM' => 'Shadowmoor',
		'PSHM' => 'Shadowmoor Promos',
		'SOI' => 'Shadows over Innistrad',
		'PSOI' => 'Shadows over Innistrad Promos',
		'SIR' => 'Shadows Over Innistrad Remastered',
		'ALA' => 'Shards of Alara',
		'PALA' => 'Shards of Alara Promos',
		'SS3' => 'Signature Spellbook: Chandra',
		'SS2' => 'Signature Spellbook: Gideon',
		'SS1' => 'Signature Spellbook: Jace',
		'S99' => 'Starter 1999',
		'S00' => 'Starter 2000',
		'SCD' => 'Starter Commander Decks',
		'SCH' => 'Store Championships',
		'SNC' => 'Streets of New Capenna',
		'MSNC' => 'Streets of New Capenna Minigames',
		'PSNC' => 'Streets of New Capenna Promos',
		'PTSNC' => 'Streets of New Capenna Southeast Asia Tokens',
		'ASTX' => 'Strixhaven Art Series',
		'STA' => 'Strixhaven Mystical Archive',
		'STX' => 'Strixhaven: School of Mages',
		'MSTX' => 'Strixhaven: School of Mages Minigames',
		'PSTX' => 'Strixhaven: School of Mages Promos',
		'SSTX' => 'Strixhaven: School of Mages Substitute Cards',
		'STH' => 'Stronghold',
		'PSTH' => 'Stronghold Promos',
		'SUM' => 'Summer Magic / Edgar',
		'PSUM' => 'Summer of Magic',
		'PSVC' => 'Summer Vacation Promos 2022',
		'PTKDF' => 'Tarkir Dragonfury',
		'TMP' => 'Tempest',
		'PTMP' => 'Tempest Promos',
		'TPR' => 'Tempest Remastered',
		'10E' => 'Tenth Edition',
		'P10E' => 'Tenth Edition Promos',
		'BRO' => 'The Brothers\' War',
		'ABRO' => 'The Brothers\' War Art Series',
		'BRC' => 'The Brothers\' War Commander',
		'MBRO' => 'The Brothers\' War Minigames',
		'PBRO' => 'The Brothers\' War Promos',
		'BRR' => 'The Brothers\' War Retro Artifacts',
		'DRK' => 'The Dark',
		'PLIST' => 'The List',
		'UPLIST' => 'The List (Unfinity Foil Edition)',
		'THS' => 'Theros',
		'THB' => 'Theros Beyond Death',
		'PTHB' => 'Theros Beyond Death Promos',
		'THP1' => 'Theros Hero\'s Path',
		'PTHS' => 'Theros Promos',
		'30A' => '30th Anniversary Edition',
		'P30H' => '30th Anniversary History Promos',
		'P30A' => '30th Anniversary Play Promos',
		'ELD' => 'Throne of Eldraine',
		'PELD' => 'Throne of Eldraine Promos',
		'TSP' => 'Time Spiral',
		'PTSP' => 'Time Spiral Promos',
		'TSR' => 'Time Spiral Remastered',
		'TSB' => 'Time Spiral Timeshifted',
		'TOR' => 'Torment',
		'PTOR' => 'Torment Promos',
		'BOT' => 'Transformers',
		'PZ2' => 'Treasure Chest',
		'P2HG' => 'Two-Headed Giant Tournament',
		'PH18' => '2018 Heroes of the Realm',
		'PH19' => '2019 Heroes of the Realm',
		'G17' => '2017 Gift Pack',
		'PH17' => '2017 Heroes of the Realm',
		'PHTR' => '2016 Heroes of the Realm',
		'PH20' => '2020 Heroes of the Realm',
		'PH21' => '2021 Heroes of the Realm',
		'PURL' => 'URL/Convention Promos',
		'UGIN' => 'Ugin\'s Fate',
		'PUMA' => 'Ultimate Box Topper',
		'UMA' => 'Ultimate Masters',
		'UNF' => 'Unfinity',
		'SUNF' => 'Unfinity Sticker Sheets',
		'UGL' => 'Unglued',
		'UNH' => 'Unhinged',
		'PUNH' => 'Unhinged Promos',
		'SLX' => 'Universes Within',
		'2ED' => 'Unlimited Edition',
		'UND' => 'Unsanctioned',
		'UST' => 'Unstable',
		'PUST' => 'Unstable Promos',
		'UDS' => 'Urza\'s Destiny',
		'PUDS' => 'Urza\'s Destiny Promos',
		'ULG' => 'Urza\'s Legacy',
		'PULG' => 'Urza\'s Legacy Promos',
		'USG' => 'Urza\'s Saga',
		'PUSG' => 'Urza\'s Saga Promos',
		'PVAN' => 'Vanguard Series',
		'OVNT' => 'Vintage Championship',
		'VMA' => 'Vintage Masters',
		'VIS' => 'Visions',
		'WAR' => 'War of the Spark',
		'PWAR' => 'War of the Spark Promos',
		'40K' => 'Warhammer 40,000 Commander',
		'WTH' => 'Weatherlight',
		'W16' => 'Welcome Deck 2016',
		'W17' => 'Welcome Deck 2017',
		'PWOS' => 'Wizards of the Coast Online Store',
		'PWPN' => 'Wizards Play Network 2008',
		'PW09' => 'Wizards Play Network 2009',
		'PW10' => 'Wizards Play Network 2010',
		'PW11' => 'Wizards Play Network 2011',
		'PW12' => 'Wizards Play Network 2012',
		'PW21' => 'Wizards Play Network 2021',
		'PW22' => 'Wizards Play Network 2022',
		'PW23' => 'Wizards Play Network 2023',
		'WC97' => 'World Championship Decks 1997',
		'WC98' => 'World Championship Decks 1998',
		'WC99' => 'World Championship Decks 1999',
		'WC00' => 'World Championship Decks 2000',
		'WC01' => 'World Championship Decks 2001',
		'WC02' => 'World Championship Decks 2002',
		'WC03' => 'World Championship Decks 2003',
		'WC04' => 'World Championship Decks 2004',
		'PWOR' => 'World Championship Promos',
		'WMC' => 'World Magic Cup Qualifiers',
		'WWK' => 'Worldwake',
		'PWWK' => 'Worldwake Promos',
		'PSS2' => 'XLN Standard Showdown',
		'PXTC' => 'XLN Treasure Chest',
		'PL21' => 'Year of the Ox 2021',
		'PL23' => 'Year of the Rabbit 2023',
		'PL22' => 'Year of the Tiger 2022',
		'ZEN' => 'Zendikar',
		'EXP' => 'Zendikar Expeditions',
		'PZEN' => 'Zendikar Promos',
		'ZNR' => 'Zendikar Rising',
		'AZNR' => 'Zendikar Rising Art Series',
		'ZNC' => 'Zendikar Rising Commander',
		'ZNE' => 'Zendikar Rising Expeditions',
		'MZNR' => 'Zendikar Rising Minigames',
		'PZNR' => 'Zendikar Rising Promos',
		'SZNR' => 'Zendikar Rising Substitute Cards',
	];

	case AdventuresInTheForgottenRealms = 'AFR';
	case AdventuresInTheForgottenRealmsArtSeries = 'AAFR';
	case AdventuresInTheForgottenRealmsMinigames = 'MAFR';
	case AdventuresInTheForgottenRealmsPromos = 'PAFR';
	case AetherRevolt = 'AER';
	case AetherRevoltPromos = 'PAER';
	case AlaraReborn = 'ARB';
	case AlaraRebornPromos = 'PARB';
	case AlchemyDominaria = 'YDMU';
	case AlchemyHorizonsBaldurSGate = 'HBG';
	case AlchemyInnistrad = 'YMID';
	case AlchemyKamigawa = 'YNEO';
	case AlchemyNewCapenna = 'YSNC';
	case AlchemyPhyrexia = 'YONE';
	case AlchemyTheBrothersWar = 'YBRO';
	case Alliances = 'ALL';
	case Amonkhet = 'AKH';
	case AmonkhetInvocations = 'MP2';
	case AmonkhetPromos = 'PAKH';
	case AmonkhetRemastered = 'AKR';
	case Anthologies = 'ATH';
	case Antiquities = 'ATQ';
	case Apocalypse = 'APC';
	case ApocalypsePromos = 'PAPC';
	case ArabianNights = 'ARN';
	case Archenemy = 'ARC';
	case ArchenemyNicolBolas = 'E01';
	case ArchenemyNicolBolasSchemes = 'OE01';
	case ArchenemyPromos = 'PARC';
	case ArchenemySchemes = 'OARC';
	case ArenaBeginnerSet = 'ANB';
	case ArenaLeague1996 = 'PARL';
	case ArenaLeague1999 = 'PAL99';
	case ArenaLeague2000 = 'PAL00';
	case ArenaLeague2001 = 'PAL01';
	case ArenaLeague2002 = 'PAL02';
	case ArenaLeague2003 = 'PAL03';
	case ArenaLeague2004 = 'PAL04';
	case ArenaLeague2005 = 'PAL05';
	case ArenaLeague2006 = 'PAL06';
	case ArenaNewPlayerExperience = 'ANA';
	case ArenaNewPlayerExperienceCards = 'OANA';
	case ArenaNewPlayerExperienceExtras = 'XANA';
	case AsiaPacificLandProgram = 'PALP';
	case AstralCards = 'PAST';
	case AvacynRestored = 'AVR';
	case AvacynRestoredPromos = 'PAVR';
	case BFZStandardSeries = 'PSS1';
	case BattleForBaldurSGateArtSeries = 'ACLB';
	case BattleForBaldurSGatePromos = 'PCLB';
	case BattleForZendikar = 'BFZ';
	case BattleForZendikarPromos = 'PBFZ';
	case BattleRoyaleBoxSet = 'BRB';
	case BattleTheHorde = 'TBTH';
	case Battlebond = 'BBD';
	case BattlebondPromos = 'PBBD';
	case BeatdownBoxSet = 'BTD';
	case BetrayersOfKamigawa = 'BOK';
	case BetrayersOfKamigawaPromos = 'PBOK';
	case BornOfTheGods = 'BNG';
	case BornOfTheGodsHeroSPath = 'THP2';
	case BornOfTheGodsPromos = 'PBNG';
	case CelebrationCards = 'PCEL';
	case ChallengerDecks2022 = 'Q07';
	case ChampionsOfKamigawa = 'CHK';
	case ChampionsOfKamigawaPromos = 'PCHK';
	case ChampsAndStates = 'PCMP';
	case Chronicles = 'CHR';
	case ClassicSixthEdition = '6ED';
	case Coldsnap = 'CSP';
	case ColdsnapPromos = 'PCSP';
	case ColdsnapThemeDecks = 'CST';
	case CollectorsEdition = 'CED';
	case Commander2011 = 'CMD';
	case Commander2011LaunchParty = 'PCMD';
	case Commander2011Oversized = 'OCMD';
	case Commander2013 = 'C13';
	case Commander2013Oversized = 'OC13';
	case Commander2014 = 'C14';
	case Commander2014Oversized = 'OC14';
	case Commander2015 = 'C15';
	case Commander2015Oversized = 'OC15';
	case Commander2016 = 'C16';
	case Commander2016Oversized = 'OC16';
	case Commander2017 = 'C17';
	case Commander2017Oversized = 'OC17';
	case Commander2018 = 'C18';
	case Commander2018Oversized = 'OC18';
	case Commander2019 = 'C19';
	case Commander2019Oversized = 'OC19';
	case Commander2020 = 'C20';
	case Commander2020Oversized = 'OC20';
	case Commander2021 = 'C21';
	case Commander2021DisplayCommanders = 'OC21';
	case CommanderAnthology = 'CMA';
	case CommanderAnthologyVolumeII = 'CM2';
	case CommanderCollectionBlack = 'CC2';
	case CommanderCollectionGreen = 'CC1';
	case CommanderLegends = 'CMR';
	case CommanderLegendsBattleForBaldurSGate = 'CLB';
	case CommanderLegendsBattleForBaldurSGateMinigames = 'MCLB';
	case CommanderMasters = 'CMM';
	case CommanderSArsenal = 'CM1';
	case CommanderSArsenalOversized = 'OCM1';
	case Conflux = 'CON';
	case ConfluxPromos = 'PCON';
	case Conspiracy = 'CNS';
	case ConspiracyPromos = 'PCNS';
	case ConspiracyTakeTheCrown = 'CN2';
	case CoreSet2019 = 'M19';
	case CoreSet2019Promos = 'PM19';
	case CoreSet2020 = 'M20';
	case CoreSet2020Promos = 'PM20';
	case CoreSet2021 = 'M21';
	case CoreSet2021Promos = 'PM21';
	case CrimsonVowArtSeries = 'AVOW';
	case CrimsonVowCommander = 'VOC';
	case CrimsonVowCommanderDisplayCommanders = 'OVOC';
	case DCILegendMembership = 'PLGM';
	case DCIPromos = 'PDCI';
	case DarkAscension = 'DKA';
	case DarkAscensionPromos = 'PDKA';
	case Darksteel = 'DST';
	case DarksteelPromos = 'PDST';
	case Deckmasters = 'DKM';
	case DefeatAGod = 'TDAG';
	case Dissension = 'DIS';
	case DissensionPromos = 'PDIS';
	case Dominaria = 'DOM';
	case DominariaPromos = 'PDOM';
	case DominariaRemastered = 'DMR';
	case DominariaUnited = 'DMU';
	case DominariaUnitedArtSeries = 'ADMU';
	case DominariaUnitedCommander = 'DMC';
	case DominariaUnitedJapanesePromoTokens = 'WDMU';
	case DominariaUnitedMinigames = 'MDMU';
	case DominariaUnitedPromos = 'PDMU';
	case DoubleMasters = '2XM';
	case DoubleMasters2022 = '2X2';
	case DragonCon = 'PDRC';
	case DragonSMaze = 'DGM';
	case DragonSMazePromos = 'PDGM';
	case DragonsOfTarkir = 'DTK';
	case DragonsOfTarkirPromos = 'PDTK';
	case DuelDecksAjaniVsNicolBolas = 'DDH';
	case DuelDecksAnthologyDivineVsDemonic = 'DVD';
	case DuelDecksAnthologyElvesVsGoblins = 'EVG';
	case DuelDecksAnthologyGarrukVsLiliana = 'GVL';
	case DuelDecksAnthologyJaceVsChandra = 'JVC';
	case DuelDecksBlessedVsCursed = 'DDQ';
	case DuelDecksDivineVsDemonic = 'DDC';
	case DuelDecksElspethVsKiora = 'DDO';
	case DuelDecksElspethVsTezzeret = 'DDF';
	case DuelDecksElvesVsGoblins = 'DD1';
	case DuelDecksElvesVsInventors = 'DDU';
	case DuelDecksGarrukVsLiliana = 'DDD';
	case DuelDecksHeroesVsMonsters = 'DDL';
	case DuelDecksIzzetVsGolgari = 'DDJ';
	case DuelDecksJaceVsChandra = 'DD2';
	case DuelDecksJaceVsVraska = 'DDM';
	case DuelDecksKnightsVsDragons = 'DDG';
	case DuelDecksMerfolkVsGoblins = 'DDT';
	case DuelDecksMindVsMight = 'DDS';
	case DuelDecksMirrodinPureVsNewPhyrexia = 'TD2';
	case DuelDecksNissaVsObNixilis = 'DDR';
	case DuelDecksPhyrexiaVsTheCoalition = 'DDE';
	case DuelDecksSorinVsTibalt = 'DDK';
	case DuelDecksSpeedVsCunning = 'DDN';
	case DuelDecksVenserVsKoth = 'DDI';
	case DuelDecksZendikarVsEldrazi = 'DDP';
	case DuelsOfThePlaneswalkers = 'DPA';
	case DuelsOfThePlaneswalkers2009Promos = 'PDTP';
	case DuelsOfThePlaneswalkers2010Promos = 'PDP10';
	case DuelsOfThePlaneswalkers2012Promos = 'PDP12';
	case DuelsOfThePlaneswalkers2013Promos = 'PDP13';
	case DuelsOfThePlaneswalkers2014Promos = 'PDP14';
	case DuelsOfThePlaneswalkers2015Promos = 'PDP15';
	case EighthEdition = '8ED';
	case EighthEditionPromos = 'P8ED';
	case EldritchMoon = 'EMN';
	case EldritchMoonPromos = 'PEMN';
	case EternalMasters = 'EMA';
	case EternalWeekend2022 = 'PEWK';
	case EuropeanLandProgram = 'PELP';
	case Eventide = 'EVE';
	case EventidePromos = 'PEVE';
	case Exodus = 'EXO';
	case ExodusPromos = 'PEXO';
	case ExplorerAnthology1 = 'EA1';
	case ExplorerAnthology2 = 'EA2';
	case ExplorersOfIxalan = 'E02';
	case FBBChronicles = 'BCHR';
	case FaceTheHydra = 'TFTH';
	case FallenEmpires = 'FEM';
	case FateReforged = 'FRF';
	case FateReforgedClashPack = 'CP2';
	case FateReforgedPromos = 'PFRF';
	case FifteenthAnniversaryCards = 'P15A';
	case FifthDawn = '5DN';
	case FifthDawnPromos = 'P5DN';
	case FifthEdition = '5ED';
	case ForeignBlackBorder = 'FBB';
	case ForgottenRealmsCommander = 'AFC';
	case ForgottenRealmsCommanderDisplayCommanders = 'OAFC';
	case FourthEdition = '4ED';
	case FourthEditionForeignBlackBorder = '4BB';
	case FridayNightMagic2000 = 'FNM';
	case FridayNightMagic2001 = 'F01';
	case FridayNightMagic2002 = 'F02';
	case FridayNightMagic2003 = 'F03';
	case FridayNightMagic2004 = 'F04';
	case FridayNightMagic2005 = 'F05';
	case FridayNightMagic2006 = 'F06';
	case FridayNightMagic2007 = 'F07';
	case FridayNightMagic2008 = 'F08';
	case FridayNightMagic2009 = 'F09';
	case FridayNightMagic2010 = 'F10';
	case FridayNightMagic2011 = 'F11';
	case FridayNightMagic2012 = 'F12';
	case FridayNightMagic2013 = 'F13';
	case FridayNightMagic2014 = 'F14';
	case FridayNightMagic2015 = 'F15';
	case FridayNightMagic2016 = 'F16';
	case FridayNightMagic2017 = 'F17';
	case FridayNightMagic2018 = 'F18';
	case FromTheVaultAngels = 'V15';
	case FromTheVaultAnnihilation = 'V14';
	case FromTheVaultDragons = 'DRB';
	case FromTheVaultExiled = 'V09';
	case FromTheVaultLegends = 'V11';
	case FromTheVaultLore = 'V16';
	case FromTheVaultRealms = 'V12';
	case FromTheVaultRelics = 'V10';
	case FromTheVaultTransform = 'V17';
	case FromTheVaultTwenty = 'V13';
	case FutureSight = 'FUT';
	case FutureSightPromos = 'PFUT';
	case GRNGuildKit = 'GK1';
	case GRNRavnicaWeekend = 'PRWK';
	case GameDayPromos = 'GDY';
	case GameNight = 'GNT';
	case GameNight2019 = 'GN2';
	case GameNightFreeForAll = 'GN3';
	case Gatecrash = 'GTC';
	case GatecrashPromos = 'PGTC';
	case Gateway2006 = 'PGTW';
	case Gateway2007 = 'PG07';
	case Gateway2008 = 'PG08';
	case GlobalSeriesJiangYangguMuYanling = 'GS1';
	case GrandPrixPromos = 'PGPX';
	case Guildpact = 'GPT';
	case GuildpactPromos = 'PGPT';
	case GuildsOfRavnica = 'GRN';
	case GuildsOfRavnicaPromos = 'PGRN';
	case Guru = 'PGRU';
	case HachetteUK = 'PHUK';
	case HappyHolidays = 'HHO';
	case HarperPrismBookPromos = 'PHPR';
	case HasCon2017 = 'H17';
	case HeadsIWinTailsYouLose = 'PHED';
	case HistoricAnthology1 = 'HA1';
	case HistoricAnthology2 = 'HA2';
	case HistoricAnthology3 = 'HA3';
	case HistoricAnthology4 = 'HA4';
	case HistoricAnthology5 = 'HA5';
	case HistoricAnthology6 = 'HA6';
	case HobbyJapanPromos = 'PHJ';
	case Homelands = 'HML';
	case HourOfDevastation = 'HOU';
	case HourOfDevastationPromos = 'PHOU';
	case IDWComics2013 = 'PI13';
	case IDWComics2014 = 'PI14';
	case IDWComicsInserts = 'PIDW';
	case IceAge = 'ICE';
	case IconicMasters = 'IMA';
	case IkoriaLairOfBehemoths = 'IKO';
	case IkoriaLairOfBehemothsPromos = 'PIKO';
	case Innistrad = 'ISD';
	case InnistradCrimsonVow = 'VOW';
	case InnistradCrimsonVowMinigames = 'MVOW';
	case InnistradCrimsonVowPromos = 'PVOW';
	case InnistradCrimsonVowSubstituteCards = 'SVOW';
	case InnistradDoubleFeature = 'DBL';
	case InnistradMidnightHunt = 'MID';
	case InnistradMidnightHuntMinigames = 'MMID';
	case InnistradMidnightHuntPromos = 'PMID';
	case InnistradMidnightHuntSubstituteCards = 'SMID';
	case InnistradPromos = 'PISD';
	case IntlCollectorsEdition = 'CEI';
	case IntroductoryTwoPlayerSet = 'ITP';
	case Invasion = 'INV';
	case InvasionPromos = 'PINV';
	case Ixalan = 'XLN';
	case IxalanPromos = 'PXLN';
	case JapanJuniorTournament = 'PJJT';
	case JourneyIntoNyx = 'JOU';
	case JourneyIntoNyxHeroSPath = 'THP3';
	case JourneyIntoNyxPromos = 'PJOU';
	case JudgeGiftCards1998 = 'JGP';
	case JudgeGiftCards1999 = 'G99';
	case JudgeGiftCards2000 = 'G00';
	case JudgeGiftCards2001 = 'G01';
	case JudgeGiftCards2002 = 'G02';
	case JudgeGiftCards2003 = 'G03';
	case JudgeGiftCards2004 = 'G04';
	case JudgeGiftCards2005 = 'G05';
	case JudgeGiftCards2006 = 'G06';
	case JudgeGiftCards2007 = 'G07';
	case JudgeGiftCards2008 = 'G08';
	case JudgeGiftCards2009 = 'G09';
	case JudgeGiftCards2010 = 'G10';
	case JudgeGiftCards2011 = 'G11';
	case JudgeGiftCards2012 = 'J12';
	case JudgeGiftCards2013 = 'J13';
	case JudgeGiftCards2014 = 'J14';
	case JudgeGiftCards2015 = 'J15';
	case JudgeGiftCards2016 = 'J16';
	case JudgeGiftCards2017 = 'J17';
	case JudgeGiftCards2018 = 'J18';
	case JudgeGiftCards2019 = 'J19';
	case JudgeGiftCards2020 = 'J20';
	case JudgeGiftCards2021 = 'PJ21';
	case JudgeGiftCards2022 = 'P22';
	case JudgeGiftCards2023 = 'P23';
	case Judgment = 'JUD';
	case JudgmentPromos = 'PJUD';
	case Jumpstart = 'JMP';
	case Jumpstart2022 = 'J22';
	case Jumpstart2022FrontCards = 'FJ22';
	case JumpstartArenaExclusives = 'AJMP';
	case JumpstartFrontCards = 'FJMP';
	case JumpstartHistoricHorizons = 'J21';
	case JuniorAPACSeries = 'PJAS';
	case JuniorSeriesEurope = 'PJSE';
	case JuniorSuperSeries = 'PSUS';
	case Kaladesh = 'KLD';
	case KaladeshInventions = 'MPS';
	case KaladeshPromos = 'PKLD';
	case KaladeshRemastered = 'KLR';
	case Kaldheim = 'KHM';
	case KaldheimArtSeries = 'AKHM';
	case KaldheimCommander = 'KHC';
	case KaldheimMinigames = 'MKHM';
	case KaldheimPromos = 'PKHM';
	case KaldheimSubstituteCards = 'SKHM';
	case KamigawaNeonDynasty = 'NEO';
	case KamigawaNeonDynastyMinigames = 'MNEO';
	case KamigawaNeonDynastyPromos = 'PNEO';
	case KamigawaNeonDynastySubstituteCards = 'SNEO';
	case KhansOfTarkir = 'KTK';
	case KhansOfTarkirPromos = 'PKTK';
	case LeagueTokens2012 = 'L12';
	case LeagueTokens2013 = 'L13';
	case LeagueTokens2014 = 'L14';
	case LeagueTokens2015 = 'L15';
	case LeagueTokens2016 = 'L16';
	case LeagueTokens2017 = 'L17';
	case LegacyChampionship = 'OLGC';
	case LegendaryCubePrizePack = 'PZ1';
	case Legends = 'LEG';
	case Legions = 'LGN';
	case LegionsPromos = 'PLGN';
	case LimitedEditionAlpha = 'LEA';
	case LimitedEditionBeta = 'LEB';
	case LordOfTheRingsTalesOfMiddleEarth = 'LTR';
	case Lorwyn = 'LRW';
	case LorwynPromos = 'PLRW';
	case LoveYourLGS2020 = 'PLG20';
	case LoveYourLGS2021 = 'PLG21';
	case LoveYourLGS2022 = 'PLG22';
	case LunarNewYear2018 = 'PLNY';
	case M15PrereleaseChallenge = 'PPC1';
	case M19GiftPack = 'G18';
	case M19StandardShowdown = 'PSS3';
	case M20PromoPacks = 'PPP1';
	case MTGArenaPromos = 'PANA';
	case Magic2010 = 'M10';
	case Magic2010Promos = 'PM10';
	case Magic2011 = 'M11';
	case Magic2011Promos = 'PM11';
	case Magic2012 = 'M12';
	case Magic2012Promos = 'PM12';
	case Magic2013 = 'M13';
	case Magic2013Promos = 'PM13';
	case Magic2014 = 'M14';
	case Magic2014Promos = 'PM14';
	case Magic2015 = 'M15';
	case Magic2015ClashPack = 'CP1';
	case Magic2015Promos = 'PM15';
	case MagicFest2019 = 'PF19';
	case MagicFest2020 = 'PF20';
	case MagicFest2021 = 'PF21';
	case MagicOnlineAvatars = 'PMOA';
	case MagicOnlinePromos = 'PRM';
	case MagicOnlineThemeDecks = 'TD0';
	case MagicOrigins = 'ORI';
	case MagicOriginsClashPack = 'CP3';
	case MagicOriginsPromos = 'PORI';
	case MagicPlayerRewards2001 = 'MPR';
	case MagicPlayerRewards2002 = 'PR2';
	case MagicPlayerRewards2003 = 'P03';
	case MagicPlayerRewards2004 = 'P04';
	case MagicPlayerRewards2005 = 'P05';
	case MagicPlayerRewards2006 = 'P06';
	case MagicPlayerRewards2007 = 'P07';
	case MagicPlayerRewards2008 = 'P08';
	case MagicPlayerRewards2009 = 'P09';
	case MagicPlayerRewards2010 = 'P10';
	case MagicPlayerRewards2011 = 'P11';
	case MagicPremiereShop2005 = 'PMPS';
	case MagicPremiereShop2006 = 'PMPS06';
	case MagicPremiereShop2007 = 'PMPS07';
	case MagicPremiereShop2008 = 'PMPS08';
	case MagicPremiereShop2009 = 'PMPS09';
	case MagicPremiereShop2010 = 'PMPS10';
	case MagicPremiereShop2011 = 'PMPS11';
	case MarchOfTheMachine = 'MOM';
	case MarchOfTheMachineCommander = 'MOC';
	case MarchOfTheMachineTheAftermath = 'MAT';
	case Masters25 = 'A25';
	case MastersEdition = 'ME1';
	case MastersEditionII = 'ME2';
	case MastersEditionIII = 'ME3';
	case MastersEditionIV = 'ME4';
	case MediaInserts = 'PMEI';
	case MercadianMasques = 'MMQ';
	case MercadianMasquesPromos = 'PMMQ';
	case MicroProsePromos = 'PMIC';
	case MidnightHuntArtSeries = 'AMID';
	case MidnightHuntCommander = 'MIC';
	case MidnightHuntCommanderDisplayCommanders = 'OMIC';
	case Mirage = 'MIR';
	case Mirrodin = 'MRD';
	case MirrodinBesieged = 'MBS';
	case MirrodinBesiegedPromos = 'PMBS';
	case MirrodinPromos = 'PMRD';
	case MiscellaneousBookPromos = 'PBOOK';
	case ModernEventDeck2014 = 'MD1';
	case ModernHorizons = 'MH1';
	case ModernHorizons1Timeshifts = 'H1R';
	case ModernHorizons2 = 'MH2';
	case ModernHorizons2ArtSeries = 'AMH2';
	case ModernHorizons2Minigames = 'MMH2';
	case ModernHorizons2Promos = 'PMH2';
	case ModernHorizonsArtSeries = 'AMH1';
	case ModernHorizonsPromos = 'PMH1';
	case ModernMasters = 'MMA';
	case ModernMasters2015 = 'MM2';
	case ModernMasters2017 = 'MM3';
	case Morningtide = 'MOR';
	case MorningtidePromos = 'PMOR';
	case MultiverseGiftBox = 'MGB';
	case MultiverseLegends = 'MUL';
	case MysteryBooster = 'MB1';
	case MysteryBoosterPlaytestCards2019 = 'CMB1';
	case MysteryBoosterPlaytestCards2021 = 'CMB2';
	case MysteryBoosterRetailEditionFoils = 'FMB1';
	case MythicEdition = 'MED';
	case NationalsPromos = 'PNAT';
	case Nemesis = 'NEM';
	case NemesisPromos = 'PNEM';
	case NeonDynastyArtSeries = 'ANEO';
	case NeonDynastyCommander = 'NEC';
	case NewCapennaArtSeries = 'ASNC';
	case NewCapennaCommander = 'NCC';
	case NewCapennaCommanderPromos = 'PNCC';
	case NewPhyrexia = 'NPH';
	case NewPhyrexiaPromos = 'PNPH';
	case NinthEdition = '9ED';
	case NinthEditionPromos = 'P9ED';
	case OathOfTheGatewatch = 'OGW';
	case OathOfTheGatewatchPromos = 'POGW';
	case Odyssey = 'ODY';
	case OdysseyPromos = 'PODY';
	case Onslaught = 'ONS';
	case OnslaughtPromos = 'PONS';
	case OpenTheHelvault = 'PHEL';
	case Oversized90SPromos = 'O90P';
	case OversizedLeaguePrizes = 'OLEP';
	case PhyrexiaAllWillBeOne = 'ONE';
	case PhyrexiaAllWillBeOneArtSeries = 'AONE';
	case PhyrexiaAllWillBeOneCommander = 'ONC';
	case PhyrexiaAllWillBeOneJapanesePromoTokens = 'WONE';
	case PhyrexiaAllWillBeOneJumpstartFrontCards = 'FONE';
	case PhyrexiaAllWillBeOneMinigames = 'MONE';
	case PhyrexiaAllWillBeOnePromos = 'PONE';
	case PioneerChallengerDecks2021 = 'Q06';
	case PioneerChallengerDecks2022 = 'Q08';
	case PlanarChaos = 'PLC';
	case PlanarChaosPromos = 'PPLC';
	case Planechase = 'HOP';
	case Planechase2012 = 'PC2';
	case Planechase2012Planes = 'OPC2';
	case PlanechaseAnthology = 'PCA';
	case PlanechaseAnthologyPlanes = 'OPCA';
	case PlanechasePlanes = 'OHOP';
	case PlanechasePromos = 'PHOP';
	case Planeshift = 'PLS';
	case PlaneshiftPromos = 'PPLS';
	case PlaneswalkerChampionshipPromos = 'PWCS';
	case PoniesTheGalloping = 'PTG';
	case Portal = 'POR';
	case PortalSecondAge = 'P02';
	case PortalThreeKingdoms = 'PTK';
	case PortalThreeKingdomsPromos = 'PPTK';
	case PremiumDeckSeriesFireAndLightning = 'PD2';
	case PremiumDeckSeriesGraveborn = 'PD3';
	case PremiumDeckSeriesSlivers = 'H09';
	case ProTourCollectorSet = 'PTC';
	case ProTourPromos = 'PPRO';
	case Prophecy = 'PCY';
	case ProphecyPromos = 'PPCY';
	case RNAGuildKit = 'GK2';
	case RNARavnicaWeekend = 'PRW2';
	case RavnicaAllegiance = 'RNA';
	case RavnicaAllegiancePromos = 'PRNA';
	case RavnicaCityOfGuilds = 'RAV';
	case RavnicaCityOfGuildsPromos = 'PRAV';
	case RedemptionProgram = 'PRED';
	case RegionalChampionshipQualifiers2022 = 'PRCQ';
	case RegionalChampionshipQualifiers2023 = 'PR23';
	case Renaissance = 'REN';
	case ResalePromos = 'PRES';
	case ReturnToRavnica = 'RTR';
	case ReturnToRavnicaPromos = 'PRTR';
	case RevisedEdition = '3ED';
	case Rinascimento = 'RIN';
	case RiseOfTheEldrazi = 'ROE';
	case RiseOfTheEldraziPromos = 'PROE';
	case RivalsOfIxalan = 'RIX';
	case RivalsOfIxalanPromos = 'PRIX';
	case RivalsQuickStartSet = 'RQS';
	case Salvat2005 = 'PSAL';
	case Salvat2011 = 'PS11';
	case SanDiegoComicCon2013 = 'PSDC';
	case SanDiegoComicCon2014 = 'PS14';
	case SanDiegoComicCon2015 = 'PS15';
	case SanDiegoComicCon2016 = 'PS16';
	case SanDiegoComicCon2017 = 'PS17';
	case SanDiegoComicCon2018 = 'PS18';
	case SanDiegoComicCon2019 = 'PS19';
	case SaviorsOfKamigawa = 'SOK';
	case SaviorsOfKamigawaPromos = 'PSOK';
	case ScarsOfMirrodin = 'SOM';
	case ScarsOfMirrodinPromos = 'PSOM';
	case Scourge = 'SCG';
	case ScourgePromos = 'PSCG';
	case SecretLair30thAnniversaryCountdownKit = 'SLC';
	case SecretLairDrop = 'SLD';
	case SecretLairShowdown = 'SLP';
	case SecretLairUltimateEdition = 'SLU';
	case SegaDreamcastCards = 'PSDG';
	case SeventhEdition = '7ED';
	case Shadowmoor = 'SHM';
	case ShadowmoorPromos = 'PSHM';
	case ShadowsOverInnistrad = 'SOI';
	case ShadowsOverInnistradPromos = 'PSOI';
	case ShadowsOverInnistradRemastered = 'SIR';
	case ShardsOfAlara = 'ALA';
	case ShardsOfAlaraPromos = 'PALA';
	case SignatureSpellbookChandra = 'SS3';
	case SignatureSpellbookGideon = 'SS2';
	case SignatureSpellbookJace = 'SS1';
	case Starter1999 = 'S99';
	case Starter2000 = 'S00';
	case StarterCommanderDecks = 'SCD';
	case StoreChampionships = 'SCH';
	case StreetsOfNewCapenna = 'SNC';
	case StreetsOfNewCapennaMinigames = 'MSNC';
	case StreetsOfNewCapennaPromos = 'PSNC';
	case StreetsOfNewCapennaSoutheastAsiaTokens = 'PTSNC';
	case StrixhavenArtSeries = 'ASTX';
	case StrixhavenMysticalArchive = 'STA';
	case StrixhavenSchoolOfMages = 'STX';
	case StrixhavenSchoolOfMagesMinigames = 'MSTX';
	case StrixhavenSchoolOfMagesPromos = 'PSTX';
	case StrixhavenSchoolOfMagesSubstituteCards = 'SSTX';
	case Stronghold = 'STH';
	case StrongholdPromos = 'PSTH';
	case SummerMagicEdgar = 'SUM';
	case SummerOfMagic = 'PSUM';
	case SummerVacationPromos2022 = 'PSVC';
	case TarkirDragonfury = 'PTKDF';
	case Tempest = 'TMP';
	case TempestPromos = 'PTMP';
	case TempestRemastered = 'TPR';
	case TenthEdition = '10E';
	case TenthEditionPromos = 'P10E';
	case TheBrothersWar = 'BRO';
	case TheBrothersWarArtSeries = 'ABRO';
	case TheBrothersWarCommander = 'BRC';
	case TheBrothersWarMinigames = 'MBRO';
	case TheBrothersWarPromos = 'PBRO';
	case TheBrothersWarRetroArtifacts = 'BRR';
	case TheDark = 'DRK';
	case TheList = 'PLIST';
	case TheListUnfinityFoilEdition = 'UPLIST';
	case Theros = 'THS';
	case TherosBeyondDeath = 'THB';
	case TherosBeyondDeathPromos = 'PTHB';
	case TherosHeroSPath = 'THP1';
	case TherosPromos = 'PTHS';
	case ThirtythAnniversaryEdition = '30A';
	case ThirtythAnniversaryHistoryPromos = 'P30H';
	case ThirtythAnniversaryPlayPromos = 'P30A';
	case ThroneOfEldraine = 'ELD';
	case ThroneOfEldrainePromos = 'PELD';
	case TimeSpiral = 'TSP';
	case TimeSpiralPromos = 'PTSP';
	case TimeSpiralRemastered = 'TSR';
	case TimeSpiralTimeshifted = 'TSB';
	case Torment = 'TOR';
	case TormentPromos = 'PTOR';
	case Transformers = 'BOT';
	case TreasureChest = 'PZ2';
	case TwoHeadedGiantTournament = 'P2HG';
	case TwoThousandEighteenHeroesOfTheRealm = 'PH18';
	case TwoThousandNineteenHeroesOfTheRealm = 'PH19';
	case TwoThousandSeventeenGiftPack = 'G17';
	case TwoThousandSeventeenHeroesOfTheRealm = 'PH17';
	case TwoThousandSixteenHeroesOfTheRealm = 'PHTR';
	case TwoThousandTwentyHeroesOfTheRealm = 'PH20';
	case TwoThousandTwentyOneHeroesOfTheRealm = 'PH21';
	case URLConventionPromos = 'PURL';
	case UginSFate = 'UGIN';
	case UltimateBoxTopper = 'PUMA';
	case UltimateMasters = 'UMA';
	case Unfinity = 'UNF';
	case UnfinityStickerSheets = 'SUNF';
	case Unglued = 'UGL';
	case Unhinged = 'UNH';
	case UnhingedPromos = 'PUNH';
	case UniversesWithin = 'SLX';
	case UnlimitedEdition = '2ED';
	case Unsanctioned = 'UND';
	case Unstable = 'UST';
	case UnstablePromos = 'PUST';
	case UrzaSDestiny = 'UDS';
	case UrzaSDestinyPromos = 'PUDS';
	case UrzaSLegacy = 'ULG';
	case UrzaSLegacyPromos = 'PULG';
	case UrzaSSaga = 'USG';
	case UrzaSSagaPromos = 'PUSG';
	case VanguardSeries = 'PVAN';
	case VintageChampionship = 'OVNT';
	case VintageMasters = 'VMA';
	case Visions = 'VIS';
	case WarOfTheSpark = 'WAR';
	case WarOfTheSparkPromos = 'PWAR';
	case Warhammer40000Commander = '40K';
	case Weatherlight = 'WTH';
	case WelcomeDeck2016 = 'W16';
	case WelcomeDeck2017 = 'W17';
	case WizardsOfTheCoastOnlineStore = 'PWOS';
	case WizardsPlayNetwork2008 = 'PWPN';
	case WizardsPlayNetwork2009 = 'PW09';
	case WizardsPlayNetwork2010 = 'PW10';
	case WizardsPlayNetwork2011 = 'PW11';
	case WizardsPlayNetwork2012 = 'PW12';
	case WizardsPlayNetwork2021 = 'PW21';
	case WizardsPlayNetwork2022 = 'PW22';
	case WizardsPlayNetwork2023 = 'PW23';
	case WorldChampionshipDecks1997 = 'WC97';
	case WorldChampionshipDecks1998 = 'WC98';
	case WorldChampionshipDecks1999 = 'WC99';
	case WorldChampionshipDecks2000 = 'WC00';
	case WorldChampionshipDecks2001 = 'WC01';
	case WorldChampionshipDecks2002 = 'WC02';
	case WorldChampionshipDecks2003 = 'WC03';
	case WorldChampionshipDecks2004 = 'WC04';
	case WorldChampionshipPromos = 'PWOR';
	case WorldMagicCupQualifiers = 'WMC';
	case Worldwake = 'WWK';
	case WorldwakePromos = 'PWWK';
	case XLNStandardShowdown = 'PSS2';
	case XLNTreasureChest = 'PXTC';
	case YearOfTheOx2021 = 'PL21';
	case YearOfTheRabbit2023 = 'PL23';
	case YearOfTheTiger2022 = 'PL22';
	case Zendikar = 'ZEN';
	case ZendikarExpeditions = 'EXP';
	case ZendikarPromos = 'PZEN';
	case ZendikarRising = 'ZNR';
	case ZendikarRisingArtSeries = 'AZNR';
	case ZendikarRisingCommander = 'ZNC';
	case ZendikarRisingExpeditions = 'ZNE';
	case ZendikarRisingMinigames = 'MZNR';
	case ZendikarRisingPromos = 'PZNR';
	case ZendikarRisingSubstituteCards = 'SZNR';

	public function label(): string
	{
		return static::getLabel($this);
	}


	public static function getLabel(self $value): string
	{
		return match ($value) {
			SetCode::AdventuresInTheForgottenRealms => "AFR",
			SetCode::AdventuresInTheForgottenRealmsArtSeries => "AAFR",
			SetCode::AdventuresInTheForgottenRealmsMinigames => "MAFR",
			SetCode::AdventuresInTheForgottenRealmsPromos => "PAFR",
			SetCode::AetherRevolt => "AER",
			SetCode::AetherRevoltPromos => "PAER",
			SetCode::AlaraReborn => "ARB",
			SetCode::AlaraRebornPromos => "PARB",
			SetCode::AlchemyDominaria => "YDMU",
			SetCode::AlchemyHorizonsBaldurSGate => "HBG",
			SetCode::AlchemyInnistrad => "YMID",
			SetCode::AlchemyKamigawa => "YNEO",
			SetCode::AlchemyNewCapenna => "YSNC",
			SetCode::AlchemyPhyrexia => "YONE",
			SetCode::AlchemyTheBrothersWar => "YBRO",
			SetCode::Alliances => "ALL",
			SetCode::Amonkhet => "AKH",
			SetCode::AmonkhetInvocations => "MP2",
			SetCode::AmonkhetPromos => "PAKH",
			SetCode::AmonkhetRemastered => "AKR",
			SetCode::Anthologies => "ATH",
			SetCode::Antiquities => "ATQ",
			SetCode::Apocalypse => "APC",
			SetCode::ApocalypsePromos => "PAPC",
			SetCode::ArabianNights => "ARN",
			SetCode::Archenemy => "ARC",
			SetCode::ArchenemyNicolBolas => "E01",
			SetCode::ArchenemyNicolBolasSchemes => "OE01",
			SetCode::ArchenemyPromos => "PARC",
			SetCode::ArchenemySchemes => "OARC",
			SetCode::ArenaBeginnerSet => "ANB",
			SetCode::ArenaLeague1996 => "PARL",
			SetCode::ArenaLeague1999 => "PAL99",
			SetCode::ArenaLeague2000 => "PAL00",
			SetCode::ArenaLeague2001 => "PAL01",
			SetCode::ArenaLeague2002 => "PAL02",
			SetCode::ArenaLeague2003 => "PAL03",
			SetCode::ArenaLeague2004 => "PAL04",
			SetCode::ArenaLeague2005 => "PAL05",
			SetCode::ArenaLeague2006 => "PAL06",
			SetCode::ArenaNewPlayerExperience => "ANA",
			SetCode::ArenaNewPlayerExperienceCards => "OANA",
			SetCode::ArenaNewPlayerExperienceExtras => "XANA",
			SetCode::AsiaPacificLandProgram => "PALP",
			SetCode::AstralCards => "PAST",
			SetCode::AvacynRestored => "AVR",
			SetCode::AvacynRestoredPromos => "PAVR",
			SetCode::BFZStandardSeries => "PSS1",
			SetCode::BattleForBaldurSGateArtSeries => "ACLB",
			SetCode::BattleForBaldurSGatePromos => "PCLB",
			SetCode::BattleForZendikar => "BFZ",
			SetCode::BattleForZendikarPromos => "PBFZ",
			SetCode::BattleRoyaleBoxSet => "BRB",
			SetCode::BattleTheHorde => "TBTH",
			SetCode::Battlebond => "BBD",
			SetCode::BattlebondPromos => "PBBD",
			SetCode::BeatdownBoxSet => "BTD",
			SetCode::BetrayersOfKamigawa => "BOK",
			SetCode::BetrayersOfKamigawaPromos => "PBOK",
			SetCode::BornOfTheGods => "BNG",
			SetCode::BornOfTheGodsHeroSPath => "THP2",
			SetCode::BornOfTheGodsPromos => "PBNG",
			SetCode::CelebrationCards => "PCEL",
			SetCode::ChallengerDecks2022 => "Q07",
			SetCode::ChampionsOfKamigawa => "CHK",
			SetCode::ChampionsOfKamigawaPromos => "PCHK",
			SetCode::ChampsAndStates => "PCMP",
			SetCode::Chronicles => "CHR",
			SetCode::ClassicSixthEdition => "6ED",
			SetCode::Coldsnap => "CSP",
			SetCode::ColdsnapPromos => "PCSP",
			SetCode::ColdsnapThemeDecks => "CST",
			SetCode::CollectorsEdition => "CED",
			SetCode::Commander2011 => "CMD",
			SetCode::Commander2011LaunchParty => "PCMD",
			SetCode::Commander2011Oversized => "OCMD",
			SetCode::Commander2013 => "C13",
			SetCode::Commander2013Oversized => "OC13",
			SetCode::Commander2014 => "C14",
			SetCode::Commander2014Oversized => "OC14",
			SetCode::Commander2015 => "C15",
			SetCode::Commander2015Oversized => "OC15",
			SetCode::Commander2016 => "C16",
			SetCode::Commander2016Oversized => "OC16",
			SetCode::Commander2017 => "C17",
			SetCode::Commander2017Oversized => "OC17",
			SetCode::Commander2018 => "C18",
			SetCode::Commander2018Oversized => "OC18",
			SetCode::Commander2019 => "C19",
			SetCode::Commander2019Oversized => "OC19",
			SetCode::Commander2020 => "C20",
			SetCode::Commander2020Oversized => "OC20",
			SetCode::Commander2021 => "C21",
			SetCode::Commander2021DisplayCommanders => "OC21",
			SetCode::CommanderAnthology => "CMA",
			SetCode::CommanderAnthologyVolumeII => "CM2",
			SetCode::CommanderCollectionBlack => "CC2",
			SetCode::CommanderCollectionGreen => "CC1",
			SetCode::CommanderLegends => "CMR",
			SetCode::CommanderLegendsBattleForBaldurSGate => "CLB",
			SetCode::CommanderLegendsBattleForBaldurSGateMinigames => "MCLB",
			SetCode::CommanderMasters => "CMM",
			SetCode::CommanderSArsenal => "CM1",
			SetCode::CommanderSArsenalOversized => "OCM1",
			SetCode::Conflux => "CON",
			SetCode::ConfluxPromos => "PCON",
			SetCode::Conspiracy => "CNS",
			SetCode::ConspiracyPromos => "PCNS",
			SetCode::ConspiracyTakeTheCrown => "CN2",
			SetCode::CoreSet2019 => "M19",
			SetCode::CoreSet2019Promos => "PM19",
			SetCode::CoreSet2020 => "M20",
			SetCode::CoreSet2020Promos => "PM20",
			SetCode::CoreSet2021 => "M21",
			SetCode::CoreSet2021Promos => "PM21",
			SetCode::CrimsonVowArtSeries => "AVOW",
			SetCode::CrimsonVowCommander => "VOC",
			SetCode::CrimsonVowCommanderDisplayCommanders => "OVOC",
			SetCode::DCILegendMembership => "PLGM",
			SetCode::DCIPromos => "PDCI",
			SetCode::DarkAscension => "DKA",
			SetCode::DarkAscensionPromos => "PDKA",
			SetCode::Darksteel => "DST",
			SetCode::DarksteelPromos => "PDST",
			SetCode::Deckmasters => "DKM",
			SetCode::DefeatAGod => "TDAG",
			SetCode::Dissension => "DIS",
			SetCode::DissensionPromos => "PDIS",
			SetCode::Dominaria => "DOM",
			SetCode::DominariaPromos => "PDOM",
			SetCode::DominariaRemastered => "DMR",
			SetCode::DominariaUnited => "DMU",
			SetCode::DominariaUnitedArtSeries => "ADMU",
			SetCode::DominariaUnitedCommander => "DMC",
			SetCode::DominariaUnitedJapanesePromoTokens => "WDMU",
			SetCode::DominariaUnitedMinigames => "MDMU",
			SetCode::DominariaUnitedPromos => "PDMU",
			SetCode::DoubleMasters => "2XM",
			SetCode::DoubleMasters2022 => "2X2",
			SetCode::DragonCon => "PDRC",
			SetCode::DragonSMaze => "DGM",
			SetCode::DragonSMazePromos => "PDGM",
			SetCode::DragonsOfTarkir => "DTK",
			SetCode::DragonsOfTarkirPromos => "PDTK",
			SetCode::DuelDecksAjaniVsNicolBolas => "DDH",
			SetCode::DuelDecksAnthologyDivineVsDemonic => "DVD",
			SetCode::DuelDecksAnthologyElvesVsGoblins => "EVG",
			SetCode::DuelDecksAnthologyGarrukVsLiliana => "GVL",
			SetCode::DuelDecksAnthologyJaceVsChandra => "JVC",
			SetCode::DuelDecksBlessedVsCursed => "DDQ",
			SetCode::DuelDecksDivineVsDemonic => "DDC",
			SetCode::DuelDecksElspethVsKiora => "DDO",
			SetCode::DuelDecksElspethVsTezzeret => "DDF",
			SetCode::DuelDecksElvesVsGoblins => "DD1",
			SetCode::DuelDecksElvesVsInventors => "DDU",
			SetCode::DuelDecksGarrukVsLiliana => "DDD",
			SetCode::DuelDecksHeroesVsMonsters => "DDL",
			SetCode::DuelDecksIzzetVsGolgari => "DDJ",
			SetCode::DuelDecksJaceVsChandra => "DD2",
			SetCode::DuelDecksJaceVsVraska => "DDM",
			SetCode::DuelDecksKnightsVsDragons => "DDG",
			SetCode::DuelDecksMerfolkVsGoblins => "DDT",
			SetCode::DuelDecksMindVsMight => "DDS",
			SetCode::DuelDecksMirrodinPureVsNewPhyrexia => "TD2",
			SetCode::DuelDecksNissaVsObNixilis => "DDR",
			SetCode::DuelDecksPhyrexiaVsTheCoalition => "DDE",
			SetCode::DuelDecksSorinVsTibalt => "DDK",
			SetCode::DuelDecksSpeedVsCunning => "DDN",
			SetCode::DuelDecksVenserVsKoth => "DDI",
			SetCode::DuelDecksZendikarVsEldrazi => "DDP",
			SetCode::DuelsOfThePlaneswalkers => "DPA",
			SetCode::DuelsOfThePlaneswalkers2009Promos => "PDTP",
			SetCode::DuelsOfThePlaneswalkers2010Promos => "PDP10",
			SetCode::DuelsOfThePlaneswalkers2012Promos => "PDP12",
			SetCode::DuelsOfThePlaneswalkers2013Promos => "PDP13",
			SetCode::DuelsOfThePlaneswalkers2014Promos => "PDP14",
			SetCode::DuelsOfThePlaneswalkers2015Promos => "PDP15",
			SetCode::EighthEdition => "8ED",
			SetCode::EighthEditionPromos => "P8ED",
			SetCode::EldritchMoon => "EMN",
			SetCode::EldritchMoonPromos => "PEMN",
			SetCode::EternalMasters => "EMA",
			SetCode::EternalWeekend2022 => "PEWK",
			SetCode::EuropeanLandProgram => "PELP",
			SetCode::Eventide => "EVE",
			SetCode::EventidePromos => "PEVE",
			SetCode::Exodus => "EXO",
			SetCode::ExodusPromos => "PEXO",
			SetCode::ExplorerAnthology1 => "EA1",
			SetCode::ExplorerAnthology2 => "EA2",
			SetCode::ExplorersOfIxalan => "E02",
			SetCode::FBBChronicles => "BCHR",
			SetCode::FaceTheHydra => "TFTH",
			SetCode::FallenEmpires => "FEM",
			SetCode::FateReforged => "FRF",
			SetCode::FateReforgedClashPack => "CP2",
			SetCode::FateReforgedPromos => "PFRF",
			SetCode::FifteenthAnniversaryCards => "P15A",
			SetCode::FifthDawn => "5DN",
			SetCode::FifthDawnPromos => "P5DN",
			SetCode::FifthEdition => "5ED",
			SetCode::ForeignBlackBorder => "FBB",
			SetCode::ForgottenRealmsCommander => "AFC",
			SetCode::ForgottenRealmsCommanderDisplayCommanders => "OAFC",
			SetCode::FourthEdition => "4ED",
			SetCode::FourthEditionForeignBlackBorder => "4BB",
			SetCode::FridayNightMagic2000 => "FNM",
			SetCode::FridayNightMagic2001 => "F01",
			SetCode::FridayNightMagic2002 => "F02",
			SetCode::FridayNightMagic2003 => "F03",
			SetCode::FridayNightMagic2004 => "F04",
			SetCode::FridayNightMagic2005 => "F05",
			SetCode::FridayNightMagic2006 => "F06",
			SetCode::FridayNightMagic2007 => "F07",
			SetCode::FridayNightMagic2008 => "F08",
			SetCode::FridayNightMagic2009 => "F09",
			SetCode::FridayNightMagic2010 => "F10",
			SetCode::FridayNightMagic2011 => "F11",
			SetCode::FridayNightMagic2012 => "F12",
			SetCode::FridayNightMagic2013 => "F13",
			SetCode::FridayNightMagic2014 => "F14",
			SetCode::FridayNightMagic2015 => "F15",
			SetCode::FridayNightMagic2016 => "F16",
			SetCode::FridayNightMagic2017 => "F17",
			SetCode::FridayNightMagic2018 => "F18",
			SetCode::FromTheVaultAngels => "V15",
			SetCode::FromTheVaultAnnihilation => "V14",
			SetCode::FromTheVaultDragons => "DRB",
			SetCode::FromTheVaultExiled => "V09",
			SetCode::FromTheVaultLegends => "V11",
			SetCode::FromTheVaultLore => "V16",
			SetCode::FromTheVaultRealms => "V12",
			SetCode::FromTheVaultRelics => "V10",
			SetCode::FromTheVaultTransform => "V17",
			SetCode::FromTheVaultTwenty => "V13",
			SetCode::FutureSight => "FUT",
			SetCode::FutureSightPromos => "PFUT",
			SetCode::GRNGuildKit => "GK1",
			SetCode::GRNRavnicaWeekend => "PRWK",
			SetCode::GameDayPromos => "GDY",
			SetCode::GameNight => "GNT",
			SetCode::GameNight2019 => "GN2",
			SetCode::GameNightFreeForAll => "GN3",
			SetCode::Gatecrash => "GTC",
			SetCode::GatecrashPromos => "PGTC",
			SetCode::Gateway2006 => "PGTW",
			SetCode::Gateway2007 => "PG07",
			SetCode::Gateway2008 => "PG08",
			SetCode::GlobalSeriesJiangYangguMuYanling => "GS1",
			SetCode::GrandPrixPromos => "PGPX",
			SetCode::Guildpact => "GPT",
			SetCode::GuildpactPromos => "PGPT",
			SetCode::GuildsOfRavnica => "GRN",
			SetCode::GuildsOfRavnicaPromos => "PGRN",
			SetCode::Guru => "PGRU",
			SetCode::HachetteUK => "PHUK",
			SetCode::HappyHolidays => "HHO",
			SetCode::HarperPrismBookPromos => "PHPR",
			SetCode::HasCon2017 => "H17",
			SetCode::HeadsIWinTailsYouLose => "PHED",
			SetCode::HistoricAnthology1 => "HA1",
			SetCode::HistoricAnthology2 => "HA2",
			SetCode::HistoricAnthology3 => "HA3",
			SetCode::HistoricAnthology4 => "HA4",
			SetCode::HistoricAnthology5 => "HA5",
			SetCode::HistoricAnthology6 => "HA6",
			SetCode::HobbyJapanPromos => "PHJ",
			SetCode::Homelands => "HML",
			SetCode::HourOfDevastation => "HOU",
			SetCode::HourOfDevastationPromos => "PHOU",
			SetCode::IDWComics2013 => "PI13",
			SetCode::IDWComics2014 => "PI14",
			SetCode::IDWComicsInserts => "PIDW",
			SetCode::IceAge => "ICE",
			SetCode::IconicMasters => "IMA",
			SetCode::IkoriaLairOfBehemoths => "IKO",
			SetCode::IkoriaLairOfBehemothsPromos => "PIKO",
			SetCode::Innistrad => "ISD",
			SetCode::InnistradCrimsonVow => "VOW",
			SetCode::InnistradCrimsonVowMinigames => "MVOW",
			SetCode::InnistradCrimsonVowPromos => "PVOW",
			SetCode::InnistradCrimsonVowSubstituteCards => "SVOW",
			SetCode::InnistradDoubleFeature => "DBL",
			SetCode::InnistradMidnightHunt => "MID",
			SetCode::InnistradMidnightHuntMinigames => "MMID",
			SetCode::InnistradMidnightHuntPromos => "PMID",
			SetCode::InnistradMidnightHuntSubstituteCards => "SMID",
			SetCode::InnistradPromos => "PISD",
			SetCode::IntlCollectorsEdition => "CEI",
			SetCode::IntroductoryTwoPlayerSet => "ITP",
			SetCode::Invasion => "INV",
			SetCode::InvasionPromos => "PINV",
			SetCode::Ixalan => "XLN",
			SetCode::IxalanPromos => "PXLN",
			SetCode::JapanJuniorTournament => "PJJT",
			SetCode::JourneyIntoNyx => "JOU",
			SetCode::JourneyIntoNyxHeroSPath => "THP3",
			SetCode::JourneyIntoNyxPromos => "PJOU",
			SetCode::JudgeGiftCards1998 => "JGP",
			SetCode::JudgeGiftCards1999 => "G99",
			SetCode::JudgeGiftCards2000 => "G00",
			SetCode::JudgeGiftCards2001 => "G01",
			SetCode::JudgeGiftCards2002 => "G02",
			SetCode::JudgeGiftCards2003 => "G03",
			SetCode::JudgeGiftCards2004 => "G04",
			SetCode::JudgeGiftCards2005 => "G05",
			SetCode::JudgeGiftCards2006 => "G06",
			SetCode::JudgeGiftCards2007 => "G07",
			SetCode::JudgeGiftCards2008 => "G08",
			SetCode::JudgeGiftCards2009 => "G09",
			SetCode::JudgeGiftCards2010 => "G10",
			SetCode::JudgeGiftCards2011 => "G11",
			SetCode::JudgeGiftCards2012 => "J12",
			SetCode::JudgeGiftCards2013 => "J13",
			SetCode::JudgeGiftCards2014 => "J14",
			SetCode::JudgeGiftCards2015 => "J15",
			SetCode::JudgeGiftCards2016 => "J16",
			SetCode::JudgeGiftCards2017 => "J17",
			SetCode::JudgeGiftCards2018 => "J18",
			SetCode::JudgeGiftCards2019 => "J19",
			SetCode::JudgeGiftCards2020 => "J20",
			SetCode::JudgeGiftCards2021 => "PJ21",
			SetCode::JudgeGiftCards2022 => "P22",
			SetCode::JudgeGiftCards2023 => "P23",
			SetCode::Judgment => "JUD",
			SetCode::JudgmentPromos => "PJUD",
			SetCode::Jumpstart => "JMP",
			SetCode::Jumpstart2022 => "J22",
			SetCode::Jumpstart2022FrontCards => "FJ22",
			SetCode::JumpstartArenaExclusives => "AJMP",
			SetCode::JumpstartFrontCards => "FJMP",
			SetCode::JumpstartHistoricHorizons => "J21",
			SetCode::JuniorAPACSeries => "PJAS",
			SetCode::JuniorSeriesEurope => "PJSE",
			SetCode::JuniorSuperSeries => "PSUS",
			SetCode::Kaladesh => "KLD",
			SetCode::KaladeshInventions => "MPS",
			SetCode::KaladeshPromos => "PKLD",
			SetCode::KaladeshRemastered => "KLR",
			SetCode::Kaldheim => "KHM",
			SetCode::KaldheimArtSeries => "AKHM",
			SetCode::KaldheimCommander => "KHC",
			SetCode::KaldheimMinigames => "MKHM",
			SetCode::KaldheimPromos => "PKHM",
			SetCode::KaldheimSubstituteCards => "SKHM",
			SetCode::KamigawaNeonDynasty => "NEO",
			SetCode::KamigawaNeonDynastyMinigames => "MNEO",
			SetCode::KamigawaNeonDynastyPromos => "PNEO",
			SetCode::KamigawaNeonDynastySubstituteCards => "SNEO",
			SetCode::KhansOfTarkir => "KTK",
			SetCode::KhansOfTarkirPromos => "PKTK",
			SetCode::LeagueTokens2012 => "L12",
			SetCode::LeagueTokens2013 => "L13",
			SetCode::LeagueTokens2014 => "L14",
			SetCode::LeagueTokens2015 => "L15",
			SetCode::LeagueTokens2016 => "L16",
			SetCode::LeagueTokens2017 => "L17",
			SetCode::LegacyChampionship => "OLGC",
			SetCode::LegendaryCubePrizePack => "PZ1",
			SetCode::Legends => "LEG",
			SetCode::Legions => "LGN",
			SetCode::LegionsPromos => "PLGN",
			SetCode::LimitedEditionAlpha => "LEA",
			SetCode::LimitedEditionBeta => "LEB",
			SetCode::LordOfTheRingsTalesOfMiddleEarth => "LTR",
			SetCode::Lorwyn => "LRW",
			SetCode::LorwynPromos => "PLRW",
			SetCode::LoveYourLGS2020 => "PLG20",
			SetCode::LoveYourLGS2021 => "PLG21",
			SetCode::LoveYourLGS2022 => "PLG22",
			SetCode::LunarNewYear2018 => "PLNY",
			SetCode::M15PrereleaseChallenge => "PPC1",
			SetCode::M19GiftPack => "G18",
			SetCode::M19StandardShowdown => "PSS3",
			SetCode::M20PromoPacks => "PPP1",
			SetCode::MTGArenaPromos => "PANA",
			SetCode::Magic2010 => "M10",
			SetCode::Magic2010Promos => "PM10",
			SetCode::Magic2011 => "M11",
			SetCode::Magic2011Promos => "PM11",
			SetCode::Magic2012 => "M12",
			SetCode::Magic2012Promos => "PM12",
			SetCode::Magic2013 => "M13",
			SetCode::Magic2013Promos => "PM13",
			SetCode::Magic2014 => "M14",
			SetCode::Magic2014Promos => "PM14",
			SetCode::Magic2015 => "M15",
			SetCode::Magic2015ClashPack => "CP1",
			SetCode::Magic2015Promos => "PM15",
			SetCode::MagicFest2019 => "PF19",
			SetCode::MagicFest2020 => "PF20",
			SetCode::MagicFest2021 => "PF21",
			SetCode::MagicOnlineAvatars => "PMOA",
			SetCode::MagicOnlinePromos => "PRM",
			SetCode::MagicOnlineThemeDecks => "TD0",
			SetCode::MagicOrigins => "ORI",
			SetCode::MagicOriginsClashPack => "CP3",
			SetCode::MagicOriginsPromos => "PORI",
			SetCode::MagicPlayerRewards2001 => "MPR",
			SetCode::MagicPlayerRewards2002 => "PR2",
			SetCode::MagicPlayerRewards2003 => "P03",
			SetCode::MagicPlayerRewards2004 => "P04",
			SetCode::MagicPlayerRewards2005 => "P05",
			SetCode::MagicPlayerRewards2006 => "P06",
			SetCode::MagicPlayerRewards2007 => "P07",
			SetCode::MagicPlayerRewards2008 => "P08",
			SetCode::MagicPlayerRewards2009 => "P09",
			SetCode::MagicPlayerRewards2010 => "P10",
			SetCode::MagicPlayerRewards2011 => "P11",
			SetCode::MagicPremiereShop2005 => "PMPS",
			SetCode::MagicPremiereShop2006 => "PMPS06",
			SetCode::MagicPremiereShop2007 => "PMPS07",
			SetCode::MagicPremiereShop2008 => "PMPS08",
			SetCode::MagicPremiereShop2009 => "PMPS09",
			SetCode::MagicPremiereShop2010 => "PMPS10",
			SetCode::MagicPremiereShop2011 => "PMPS11",
			SetCode::MarchOfTheMachine => "MOM",
			SetCode::MarchOfTheMachineCommander => "MOC",
			SetCode::MarchOfTheMachineTheAftermath => "MAT",
			SetCode::Masters25 => "A25",
			SetCode::MastersEdition => "ME1",
			SetCode::MastersEditionII => "ME2",
			SetCode::MastersEditionIII => "ME3",
			SetCode::MastersEditionIV => "ME4",
			SetCode::MediaInserts => "PMEI",
			SetCode::MercadianMasques => "MMQ",
			SetCode::MercadianMasquesPromos => "PMMQ",
			SetCode::MicroProsePromos => "PMIC",
			SetCode::MidnightHuntArtSeries => "AMID",
			SetCode::MidnightHuntCommander => "MIC",
			SetCode::MidnightHuntCommanderDisplayCommanders => "OMIC",
			SetCode::Mirage => "MIR",
			SetCode::Mirrodin => "MRD",
			SetCode::MirrodinBesieged => "MBS",
			SetCode::MirrodinBesiegedPromos => "PMBS",
			SetCode::MirrodinPromos => "PMRD",
			SetCode::MiscellaneousBookPromos => "PBOOK",
			SetCode::ModernEventDeck2014 => "MD1",
			SetCode::ModernHorizons => "MH1",
			SetCode::ModernHorizons1Timeshifts => "H1R",
			SetCode::ModernHorizons2 => "MH2",
			SetCode::ModernHorizons2ArtSeries => "AMH2",
			SetCode::ModernHorizons2Minigames => "MMH2",
			SetCode::ModernHorizons2Promos => "PMH2",
			SetCode::ModernHorizonsArtSeries => "AMH1",
			SetCode::ModernHorizonsPromos => "PMH1",
			SetCode::ModernMasters => "MMA",
			SetCode::ModernMasters2015 => "MM2",
			SetCode::ModernMasters2017 => "MM3",
			SetCode::Morningtide => "MOR",
			SetCode::MorningtidePromos => "PMOR",
			SetCode::MultiverseGiftBox => "MGB",
			SetCode::MultiverseLegends => "MUL",
			SetCode::MysteryBooster => "MB1",
			SetCode::MysteryBoosterPlaytestCards2019 => "CMB1",
			SetCode::MysteryBoosterPlaytestCards2021 => "CMB2",
			SetCode::MysteryBoosterRetailEditionFoils => "FMB1",
			SetCode::MythicEdition => "MED",
			SetCode::NationalsPromos => "PNAT",
			SetCode::Nemesis => "NEM",
			SetCode::NemesisPromos => "PNEM",
			SetCode::NeonDynastyArtSeries => "ANEO",
			SetCode::NeonDynastyCommander => "NEC",
			SetCode::NewCapennaArtSeries => "ASNC",
			SetCode::NewCapennaCommander => "NCC",
			SetCode::NewCapennaCommanderPromos => "PNCC",
			SetCode::NewPhyrexia => "NPH",
			SetCode::NewPhyrexiaPromos => "PNPH",
			SetCode::NinthEdition => "9ED",
			SetCode::NinthEditionPromos => "P9ED",
			SetCode::OathOfTheGatewatch => "OGW",
			SetCode::OathOfTheGatewatchPromos => "POGW",
			SetCode::Odyssey => "ODY",
			SetCode::OdysseyPromos => "PODY",
			SetCode::Onslaught => "ONS",
			SetCode::OnslaughtPromos => "PONS",
			SetCode::OpenTheHelvault => "PHEL",
			SetCode::Oversized90SPromos => "O90P",
			SetCode::OversizedLeaguePrizes => "OLEP",
			SetCode::PhyrexiaAllWillBeOne => "ONE",
			SetCode::PhyrexiaAllWillBeOneArtSeries => "AONE",
			SetCode::PhyrexiaAllWillBeOneCommander => "ONC",
			SetCode::PhyrexiaAllWillBeOneJapanesePromoTokens => "WONE",
			SetCode::PhyrexiaAllWillBeOneJumpstartFrontCards => "FONE",
			SetCode::PhyrexiaAllWillBeOneMinigames => "MONE",
			SetCode::PhyrexiaAllWillBeOnePromos => "PONE",
			SetCode::PioneerChallengerDecks2021 => "Q06",
			SetCode::PioneerChallengerDecks2022 => "Q08",
			SetCode::PlanarChaos => "PLC",
			SetCode::PlanarChaosPromos => "PPLC",
			SetCode::Planechase => "HOP",
			SetCode::Planechase2012 => "PC2",
			SetCode::Planechase2012Planes => "OPC2",
			SetCode::PlanechaseAnthology => "PCA",
			SetCode::PlanechaseAnthologyPlanes => "OPCA",
			SetCode::PlanechasePlanes => "OHOP",
			SetCode::PlanechasePromos => "PHOP",
			SetCode::Planeshift => "PLS",
			SetCode::PlaneshiftPromos => "PPLS",
			SetCode::PlaneswalkerChampionshipPromos => "PWCS",
			SetCode::PoniesTheGalloping => "PTG",
			SetCode::Portal => "POR",
			SetCode::PortalSecondAge => "P02",
			SetCode::PortalThreeKingdoms => "PTK",
			SetCode::PortalThreeKingdomsPromos => "PPTK",
			SetCode::PremiumDeckSeriesFireAndLightning => "PD2",
			SetCode::PremiumDeckSeriesGraveborn => "PD3",
			SetCode::PremiumDeckSeriesSlivers => "H09",
			SetCode::ProTourCollectorSet => "PTC",
			SetCode::ProTourPromos => "PPRO",
			SetCode::Prophecy => "PCY",
			SetCode::ProphecyPromos => "PPCY",
			SetCode::RNAGuildKit => "GK2",
			SetCode::RNARavnicaWeekend => "PRW2",
			SetCode::RavnicaAllegiance => "RNA",
			SetCode::RavnicaAllegiancePromos => "PRNA",
			SetCode::RavnicaCityOfGuilds => "RAV",
			SetCode::RavnicaCityOfGuildsPromos => "PRAV",
			SetCode::RedemptionProgram => "PRED",
			SetCode::RegionalChampionshipQualifiers2022 => "PRCQ",
			SetCode::RegionalChampionshipQualifiers2023 => "PR23",
			SetCode::Renaissance => "REN",
			SetCode::ResalePromos => "PRES",
			SetCode::ReturnToRavnica => "RTR",
			SetCode::ReturnToRavnicaPromos => "PRTR",
			SetCode::RevisedEdition => "3ED",
			SetCode::Rinascimento => "RIN",
			SetCode::RiseOfTheEldrazi => "ROE",
			SetCode::RiseOfTheEldraziPromos => "PROE",
			SetCode::RivalsOfIxalan => "RIX",
			SetCode::RivalsOfIxalanPromos => "PRIX",
			SetCode::RivalsQuickStartSet => "RQS",
			SetCode::Salvat2005 => "PSAL",
			SetCode::Salvat2011 => "PS11",
			SetCode::SanDiegoComicCon2013 => "PSDC",
			SetCode::SanDiegoComicCon2014 => "PS14",
			SetCode::SanDiegoComicCon2015 => "PS15",
			SetCode::SanDiegoComicCon2016 => "PS16",
			SetCode::SanDiegoComicCon2017 => "PS17",
			SetCode::SanDiegoComicCon2018 => "PS18",
			SetCode::SanDiegoComicCon2019 => "PS19",
			SetCode::SaviorsOfKamigawa => "SOK",
			SetCode::SaviorsOfKamigawaPromos => "PSOK",
			SetCode::ScarsOfMirrodin => "SOM",
			SetCode::ScarsOfMirrodinPromos => "PSOM",
			SetCode::Scourge => "SCG",
			SetCode::ScourgePromos => "PSCG",
			SetCode::SecretLair30thAnniversaryCountdownKit => "SLC",
			SetCode::SecretLairDrop => "SLD",
			SetCode::SecretLairShowdown => "SLP",
			SetCode::SecretLairUltimateEdition => "SLU",
			SetCode::SegaDreamcastCards => "PSDG",
			SetCode::SeventhEdition => "7ED",
			SetCode::Shadowmoor => "SHM",
			SetCode::ShadowmoorPromos => "PSHM",
			SetCode::ShadowsOverInnistrad => "SOI",
			SetCode::ShadowsOverInnistradPromos => "PSOI",
			SetCode::ShadowsOverInnistradRemastered => "SIR",
			SetCode::ShardsOfAlara => "ALA",
			SetCode::ShardsOfAlaraPromos => "PALA",
			SetCode::SignatureSpellbookChandra => "SS3",
			SetCode::SignatureSpellbookGideon => "SS2",
			SetCode::SignatureSpellbookJace => "SS1",
			SetCode::Starter1999 => "S99",
			SetCode::Starter2000 => "S00",
			SetCode::StarterCommanderDecks => "SCD",
			SetCode::StoreChampionships => "SCH",
			SetCode::StreetsOfNewCapenna => "SNC",
			SetCode::StreetsOfNewCapennaMinigames => "MSNC",
			SetCode::StreetsOfNewCapennaPromos => "PSNC",
			SetCode::StreetsOfNewCapennaSoutheastAsiaTokens => "PTSNC",
			SetCode::StrixhavenArtSeries => "ASTX",
			SetCode::StrixhavenMysticalArchive => "STA",
			SetCode::StrixhavenSchoolOfMages => "STX",
			SetCode::StrixhavenSchoolOfMagesMinigames => "MSTX",
			SetCode::StrixhavenSchoolOfMagesPromos => "PSTX",
			SetCode::StrixhavenSchoolOfMagesSubstituteCards => "SSTX",
			SetCode::Stronghold => "STH",
			SetCode::StrongholdPromos => "PSTH",
			SetCode::SummerMagicEdgar => "SUM",
			SetCode::SummerOfMagic => "PSUM",
			SetCode::SummerVacationPromos2022 => "PSVC",
			SetCode::TarkirDragonfury => "PTKDF",
			SetCode::Tempest => "TMP",
			SetCode::TempestPromos => "PTMP",
			SetCode::TempestRemastered => "TPR",
			SetCode::TenthEdition => "10E",
			SetCode::TenthEditionPromos => "P10E",
			SetCode::TheBrothersWar => "BRO",
			SetCode::TheBrothersWarArtSeries => "ABRO",
			SetCode::TheBrothersWarCommander => "BRC",
			SetCode::TheBrothersWarMinigames => "MBRO",
			SetCode::TheBrothersWarPromos => "PBRO",
			SetCode::TheBrothersWarRetroArtifacts => "BRR",
			SetCode::TheDark => "DRK",
			SetCode::TheList => "PLIST",
			SetCode::TheListUnfinityFoilEdition => "UPLIST",
			SetCode::Theros => "THS",
			SetCode::TherosBeyondDeath => "THB",
			SetCode::TherosBeyondDeathPromos => "PTHB",
			SetCode::TherosHeroSPath => "THP1",
			SetCode::TherosPromos => "PTHS",
			SetCode::ThirtythAnniversaryEdition => "30A",
			SetCode::ThirtythAnniversaryHistoryPromos => "P30H",
			SetCode::ThirtythAnniversaryPlayPromos => "P30A",
			SetCode::ThroneOfEldraine => "ELD",
			SetCode::ThroneOfEldrainePromos => "PELD",
			SetCode::TimeSpiral => "TSP",
			SetCode::TimeSpiralPromos => "PTSP",
			SetCode::TimeSpiralRemastered => "TSR",
			SetCode::TimeSpiralTimeshifted => "TSB",
			SetCode::Torment => "TOR",
			SetCode::TormentPromos => "PTOR",
			SetCode::Transformers => "BOT",
			SetCode::TreasureChest => "PZ2",
			SetCode::TwoHeadedGiantTournament => "P2HG",
			SetCode::TwoThousandEighteenHeroesOfTheRealm => "PH18",
			SetCode::TwoThousandNineteenHeroesOfTheRealm => "PH19",
			SetCode::TwoThousandSeventeenGiftPack => "G17",
			SetCode::TwoThousandSeventeenHeroesOfTheRealm => "PH17",
			SetCode::TwoThousandSixteenHeroesOfTheRealm => "PHTR",
			SetCode::TwoThousandTwentyHeroesOfTheRealm => "PH20",
			SetCode::TwoThousandTwentyOneHeroesOfTheRealm => "PH21",
			SetCode::URLConventionPromos => "PURL",
			SetCode::UginSFate => "UGIN",
			SetCode::UltimateBoxTopper => "PUMA",
			SetCode::UltimateMasters => "UMA",
			SetCode::Unfinity => "UNF",
			SetCode::UnfinityStickerSheets => "SUNF",
			SetCode::Unglued => "UGL",
			SetCode::Unhinged => "UNH",
			SetCode::UnhingedPromos => "PUNH",
			SetCode::UniversesWithin => "SLX",
			SetCode::UnlimitedEdition => "2ED",
			SetCode::Unsanctioned => "UND",
			SetCode::Unstable => "UST",
			SetCode::UnstablePromos => "PUST",
			SetCode::UrzaSDestiny => "UDS",
			SetCode::UrzaSDestinyPromos => "PUDS",
			SetCode::UrzaSLegacy => "ULG",
			SetCode::UrzaSLegacyPromos => "PULG",
			SetCode::UrzaSSaga => "USG",
			SetCode::UrzaSSagaPromos => "PUSG",
			SetCode::VanguardSeries => "PVAN",
			SetCode::VintageChampionship => "OVNT",
			SetCode::VintageMasters => "VMA",
			SetCode::Visions => "VIS",
			SetCode::WarOfTheSpark => "WAR",
			SetCode::WarOfTheSparkPromos => "PWAR",
			SetCode::Warhammer40000Commander => "40K",
			SetCode::Weatherlight => "WTH",
			SetCode::WelcomeDeck2016 => "W16",
			SetCode::WelcomeDeck2017 => "W17",
			SetCode::WizardsOfTheCoastOnlineStore => "PWOS",
			SetCode::WizardsPlayNetwork2008 => "PWPN",
			SetCode::WizardsPlayNetwork2009 => "PW09",
			SetCode::WizardsPlayNetwork2010 => "PW10",
			SetCode::WizardsPlayNetwork2011 => "PW11",
			SetCode::WizardsPlayNetwork2012 => "PW12",
			SetCode::WizardsPlayNetwork2021 => "PW21",
			SetCode::WizardsPlayNetwork2022 => "PW22",
			SetCode::WizardsPlayNetwork2023 => "PW23",
			SetCode::WorldChampionshipDecks1997 => "WC97",
			SetCode::WorldChampionshipDecks1998 => "WC98",
			SetCode::WorldChampionshipDecks1999 => "WC99",
			SetCode::WorldChampionshipDecks2000 => "WC00",
			SetCode::WorldChampionshipDecks2001 => "WC01",
			SetCode::WorldChampionshipDecks2002 => "WC02",
			SetCode::WorldChampionshipDecks2003 => "WC03",
			SetCode::WorldChampionshipDecks2004 => "WC04",
			SetCode::WorldChampionshipPromos => "PWOR",
			SetCode::WorldMagicCupQualifiers => "WMC",
			SetCode::Worldwake => "WWK",
			SetCode::WorldwakePromos => "PWWK",
			SetCode::XLNStandardShowdown => "PSS2",
			SetCode::XLNTreasureChest => "PXTC",
			SetCode::YearOfTheOx2021 => "PL21",
			SetCode::YearOfTheRabbit2023 => "PL23",
			SetCode::YearOfTheTiger2022 => "PL22",
			SetCode::Zendikar => "ZEN",
			SetCode::ZendikarExpeditions => "EXP",
			SetCode::ZendikarPromos => "PZEN",
			SetCode::ZendikarRising => "ZNR",
			SetCode::ZendikarRisingArtSeries => "AZNR",
			SetCode::ZendikarRisingCommander => "ZNC",
			SetCode::ZendikarRisingExpeditions => "ZNE",
			SetCode::ZendikarRisingMinigames => "MZNR",
			SetCode::ZendikarRisingPromos => "PZNR",
			SetCode::ZendikarRisingSubstituteCards => "SZNR",
		}
		;
	}


	public function getName(null|string $value = null): string
	{
		$value ??= $this->value;
		if (!isset(SetCode::CODE_NAME_MAP[$value])) {
		    throw new \RuntimeException('Invalid code...');
		}
		return SetCode::CODE_NAME_MAP[$value];
	}


	public function fromName(string $name): self
	{
		$nameCodes = array_flip(SetCode::CODE_NAME_MAP);
		if (!isset($nameCodes[$name])) {
		    throw new \RuntimeException('Invalid code...');
		}
		return SetCode::from($nameCodes[$name]);
	}
}
